package ir.mservices.market.theme;

import defpackage.js3;
import java.io.Serializable;

/* JADX INFO: loaded from: classes3.dex */
public final class ThemeData implements Serializable {
    public final int A;
    public final int B;
    public final int C;
    public final int D;
    public final int E;
    public final int F;
    public final int G;
    public final int H;
    public final AlphaColor I;
    public final AlphaColor J;
    public final int K;
    public final int L;
    public final int M;
    public final int N;
    public final Ripple O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final ThemeMode a;
    public final MyketColor b;
    public final int c;
    public final int d;
    public final int e;
    public final int f;
    public final int g;
    public final int h;
    public final int i;
    public final int j;
    public final int k;
    public final int l;
    public final int m;
    public final int n;
    public final int o;
    public final int p;
    public final int q;
    public final int r;
    public final int s;
    public final int t;
    public final int u;
    public final int v;
    public final int w;
    public final int x;
    public final int y;
    public final int z;

    public ThemeData(ThemeMode themeMode, MyketColor myketColor, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, int i14, int i15, int i16, int i17, int i18, int i19, int i20, int i21, int i22, int i23, int i24, int i25, int i26, int i27, int i28, int i29, int i30, int i31, int i32, AlphaColor alphaColor, AlphaColor alphaColor2, int i33, int i34, int i35, int i36, Ripple ripple, int i37, int i38, int i39, int i40) {
        js3.p(alphaColor, "white");
        js3.p(alphaColor2, "black");
        this.a = themeMode;
        this.b = myketColor;
        this.c = i;
        this.d = i2;
        this.e = i3;
        this.f = i4;
        this.g = i5;
        this.h = i6;
        this.i = i7;
        this.j = i8;
        this.k = i9;
        this.l = i10;
        this.m = i11;
        this.n = i12;
        this.o = i13;
        this.p = i14;
        this.q = i15;
        this.r = i16;
        this.s = i17;
        this.t = i18;
        this.u = i19;
        this.v = i20;
        this.w = i21;
        this.x = i22;
        this.y = i23;
        this.z = i24;
        this.A = i25;
        this.B = i26;
        this.C = i27;
        this.D = i28;
        this.E = i29;
        this.F = i30;
        this.G = i31;
        this.H = i32;
        this.I = alphaColor;
        this.J = alphaColor2;
        this.K = i33;
        this.L = i34;
        this.M = i35;
        this.N = i36;
        this.O = ripple;
        this.P = i37;
        this.Q = i38;
        this.R = i39;
        this.S = i40;
    }
}
