package org.pcap4j.packet.namednumber;

import defpackage.o40;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes4.dex */
public final class DnsResourceRecordType extends NamedNumber<Short, DnsResourceRecordType> {
    public static final DnsResourceRecordType A;
    public static final DnsResourceRecordType A6;
    public static final DnsResourceRecordType AAAA;
    public static final DnsResourceRecordType AFSDB;
    public static final DnsResourceRecordType ALL_RECORDS;
    public static final DnsResourceRecordType APL;
    public static final DnsResourceRecordType ATMA;
    public static final DnsResourceRecordType AVC;
    public static final DnsResourceRecordType AXFR;
    public static final DnsResourceRecordType CAA;
    public static final DnsResourceRecordType CDNSKEY;
    public static final DnsResourceRecordType CDS;
    public static final DnsResourceRecordType CERT;
    public static final DnsResourceRecordType CNAME;
    public static final DnsResourceRecordType CSYNC;
    public static final DnsResourceRecordType DHCID;
    public static final DnsResourceRecordType DLV;
    public static final DnsResourceRecordType DNAME;
    public static final DnsResourceRecordType DNSKEY;
    public static final DnsResourceRecordType DS;
    public static final DnsResourceRecordType EID;
    public static final DnsResourceRecordType EUI48;
    public static final DnsResourceRecordType EUI64;
    public static final DnsResourceRecordType GID;
    public static final DnsResourceRecordType GPOS;
    public static final DnsResourceRecordType HINFO;
    public static final DnsResourceRecordType HIP;
    public static final DnsResourceRecordType IPSECKEY;
    public static final DnsResourceRecordType ISDN;
    public static final DnsResourceRecordType IXFR;
    public static final DnsResourceRecordType KEY;
    public static final DnsResourceRecordType KX;
    public static final DnsResourceRecordType L32;
    public static final DnsResourceRecordType L64;
    public static final DnsResourceRecordType LOC;
    public static final DnsResourceRecordType LP;
    public static final DnsResourceRecordType MAILA;
    public static final DnsResourceRecordType MAILB;
    public static final DnsResourceRecordType MB;
    public static final DnsResourceRecordType MD;
    public static final DnsResourceRecordType MF;
    public static final DnsResourceRecordType MG;
    public static final DnsResourceRecordType MINFO;
    public static final DnsResourceRecordType MR;
    public static final DnsResourceRecordType MX;
    public static final DnsResourceRecordType NAPTR;
    public static final DnsResourceRecordType NID;
    public static final DnsResourceRecordType NIMLOC;
    public static final DnsResourceRecordType NINFO;
    public static final DnsResourceRecordType NS;
    public static final DnsResourceRecordType NSAP;
    public static final DnsResourceRecordType NSAP_PTR;
    public static final DnsResourceRecordType NSEC;
    public static final DnsResourceRecordType NSEC3;
    public static final DnsResourceRecordType NSEC3PARAM;
    public static final DnsResourceRecordType NULL;
    public static final DnsResourceRecordType NXT;
    public static final DnsResourceRecordType OPENPGPKEY;
    public static final DnsResourceRecordType OPT;
    public static final DnsResourceRecordType PTR;
    public static final DnsResourceRecordType PX;
    public static final DnsResourceRecordType RKEY;
    public static final DnsResourceRecordType RP;
    public static final DnsResourceRecordType RRSIG;
    public static final DnsResourceRecordType RT;
    public static final DnsResourceRecordType SIG;
    public static final DnsResourceRecordType SINK;
    public static final DnsResourceRecordType SMIMEA;
    public static final DnsResourceRecordType SOA;
    public static final DnsResourceRecordType SPF;
    public static final DnsResourceRecordType SRV;
    public static final DnsResourceRecordType SSHFP;
    public static final DnsResourceRecordType TA;
    public static final DnsResourceRecordType TALINK;
    public static final DnsResourceRecordType TKEY;
    public static final DnsResourceRecordType TLSA;
    public static final DnsResourceRecordType TSIG;
    public static final DnsResourceRecordType TXT;
    public static final DnsResourceRecordType UID;
    public static final DnsResourceRecordType UINFO;
    public static final DnsResourceRecordType UNSPEC;
    public static final DnsResourceRecordType URI;
    public static final DnsResourceRecordType WKS;
    public static final DnsResourceRecordType X25;
    private static final Map<Short, DnsResourceRecordType> registry;
    private static final long serialVersionUID = 513163065994381046L;

    static {
        DnsResourceRecordType dnsResourceRecordType = new DnsResourceRecordType((short) 1, "A (Host address)");
        A = dnsResourceRecordType;
        DnsResourceRecordType dnsResourceRecordType2 = new DnsResourceRecordType((short) 2, "NS (Authoritative name server)");
        NS = dnsResourceRecordType2;
        DnsResourceRecordType dnsResourceRecordType3 = new DnsResourceRecordType((short) 3, "MD (Mail destination)");
        MD = dnsResourceRecordType3;
        DnsResourceRecordType dnsResourceRecordType4 = new DnsResourceRecordType((short) 4, "MF (Mail forwarder)");
        MF = dnsResourceRecordType4;
        DnsResourceRecordType dnsResourceRecordType5 = new DnsResourceRecordType((short) 5, "CNAME (Canonical name for an alias)");
        CNAME = dnsResourceRecordType5;
        DnsResourceRecordType dnsResourceRecordType6 = new DnsResourceRecordType((short) 6, "SOA (Start of a zone of authority)");
        SOA = dnsResourceRecordType6;
        DnsResourceRecordType dnsResourceRecordType7 = new DnsResourceRecordType((short) 7, "MB (Mailbox domain name)");
        MB = dnsResourceRecordType7;
        DnsResourceRecordType dnsResourceRecordType8 = new DnsResourceRecordType((short) 8, "MG (Mail group member)");
        MG = dnsResourceRecordType8;
        DnsResourceRecordType dnsResourceRecordType9 = new DnsResourceRecordType((short) 9, "MR (Mail rename domain name)");
        MR = dnsResourceRecordType9;
        DnsResourceRecordType dnsResourceRecordType10 = new DnsResourceRecordType((short) 10, "NULL (Null RR)");
        NULL = dnsResourceRecordType10;
        DnsResourceRecordType dnsResourceRecordType11 = new DnsResourceRecordType((short) 11, "WKS (Well known service description)");
        WKS = dnsResourceRecordType11;
        DnsResourceRecordType dnsResourceRecordType12 = new DnsResourceRecordType((short) 12, "PTR (Domain name pointer)");
        PTR = dnsResourceRecordType12;
        DnsResourceRecordType dnsResourceRecordType13 = new DnsResourceRecordType((short) 13, "HINFO (Host information)");
        HINFO = dnsResourceRecordType13;
        DnsResourceRecordType dnsResourceRecordType14 = new DnsResourceRecordType((short) 14, "MINFO (Mailbox or mail list information)");
        MINFO = dnsResourceRecordType14;
        DnsResourceRecordType dnsResourceRecordType15 = new DnsResourceRecordType((short) 15, "MX (Mail exchange)");
        MX = dnsResourceRecordType15;
        DnsResourceRecordType dnsResourceRecordType16 = new DnsResourceRecordType((short) 16, "TXT (Text strings)");
        TXT = dnsResourceRecordType16;
        DnsResourceRecordType dnsResourceRecordType17 = new DnsResourceRecordType((short) 17, "RP (Responsible Person)");
        RP = dnsResourceRecordType17;
        DnsResourceRecordType dnsResourceRecordType18 = new DnsResourceRecordType((short) 18, "AFSDB (AFS Data Base location)");
        AFSDB = dnsResourceRecordType18;
        DnsResourceRecordType dnsResourceRecordType19 = new DnsResourceRecordType((short) 19, "X25 (X.25 PSDN address)");
        X25 = dnsResourceRecordType19;
        DnsResourceRecordType dnsResourceRecordType20 = new DnsResourceRecordType((short) 20, "ISDN (ISDN address)");
        ISDN = dnsResourceRecordType20;
        DnsResourceRecordType dnsResourceRecordType21 = new DnsResourceRecordType((short) 21, "RT (Route Through)");
        RT = dnsResourceRecordType21;
        DnsResourceRecordType dnsResourceRecordType22 = new DnsResourceRecordType((short) 22, "NSAP (NSAP address)");
        NSAP = dnsResourceRecordType22;
        DnsResourceRecordType dnsResourceRecordType23 = new DnsResourceRecordType((short) 23, "NSAP-PTR (NSAP style domain name pointer)");
        NSAP_PTR = dnsResourceRecordType23;
        DnsResourceRecordType dnsResourceRecordType24 = new DnsResourceRecordType((short) 24, "SIG (Security signature)");
        SIG = dnsResourceRecordType24;
        DnsResourceRecordType dnsResourceRecordType25 = new DnsResourceRecordType((short) 25, "KEY (Security key)");
        KEY = dnsResourceRecordType25;
        DnsResourceRecordType dnsResourceRecordType26 = new DnsResourceRecordType((short) 26, "PX (X.400 mail mapping information)");
        PX = dnsResourceRecordType26;
        DnsResourceRecordType dnsResourceRecordType27 = new DnsResourceRecordType((short) 27, "GPOS (Geographical Position)");
        GPOS = dnsResourceRecordType27;
        DnsResourceRecordType dnsResourceRecordType28 = new DnsResourceRecordType((short) 28, "AAAA (IP6 Address)");
        AAAA = dnsResourceRecordType28;
        DnsResourceRecordType dnsResourceRecordType29 = new DnsResourceRecordType((short) 29, "LOC (Location Information)");
        LOC = dnsResourceRecordType29;
        DnsResourceRecordType dnsResourceRecordType30 = new DnsResourceRecordType((short) 30, "NXT (Next Domain)");
        NXT = dnsResourceRecordType30;
        DnsResourceRecordType dnsResourceRecordType31 = new DnsResourceRecordType((short) 31, "EID (Endpoint Identifier)");
        EID = dnsResourceRecordType31;
        DnsResourceRecordType dnsResourceRecordType32 = new DnsResourceRecordType((short) 32, "NIMLOC (Nimrod Locator)");
        NIMLOC = dnsResourceRecordType32;
        DnsResourceRecordType dnsResourceRecordType33 = new DnsResourceRecordType((short) 33, "SRV (Server Selection)");
        SRV = dnsResourceRecordType33;
        DnsResourceRecordType dnsResourceRecordType34 = new DnsResourceRecordType((short) 34, "ATMA (ATM Address)");
        ATMA = dnsResourceRecordType34;
        DnsResourceRecordType dnsResourceRecordType35 = new DnsResourceRecordType((short) 35, "NAPTR (Naming Authority Pointer)");
        NAPTR = dnsResourceRecordType35;
        DnsResourceRecordType dnsResourceRecordType36 = new DnsResourceRecordType((short) 36, "KX (Key Exchanger)");
        KX = dnsResourceRecordType36;
        DnsResourceRecordType dnsResourceRecordType37 = new DnsResourceRecordType((short) 37, "CERT");
        CERT = dnsResourceRecordType37;
        DnsResourceRecordType dnsResourceRecordType38 = new DnsResourceRecordType((short) 38, "A6");
        A6 = dnsResourceRecordType38;
        DnsResourceRecordType dnsResourceRecordType39 = new DnsResourceRecordType((short) 39, "DNAME");
        DNAME = dnsResourceRecordType39;
        DnsResourceRecordType dnsResourceRecordType40 = new DnsResourceRecordType((short) 40, "SINK");
        SINK = dnsResourceRecordType40;
        DnsResourceRecordType dnsResourceRecordType41 = new DnsResourceRecordType((short) 41, "OPT");
        OPT = dnsResourceRecordType41;
        DnsResourceRecordType dnsResourceRecordType42 = new DnsResourceRecordType((short) 42, "APL");
        APL = dnsResourceRecordType42;
        DnsResourceRecordType dnsResourceRecordType43 = new DnsResourceRecordType((short) 43, "DS (Delegation Signer)");
        DS = dnsResourceRecordType43;
        DnsResourceRecordType dnsResourceRecordType44 = new DnsResourceRecordType((short) 44, "SSHFP (SSH Key Fingerprint)");
        SSHFP = dnsResourceRecordType44;
        DnsResourceRecordType dnsResourceRecordType45 = new DnsResourceRecordType((short) 45, "IPSECKEY");
        IPSECKEY = dnsResourceRecordType45;
        DnsResourceRecordType dnsResourceRecordType46 = new DnsResourceRecordType((short) 46, "RRSIG");
        RRSIG = dnsResourceRecordType46;
        DnsResourceRecordType dnsResourceRecordType47 = new DnsResourceRecordType((short) 47, "NSEC");
        NSEC = dnsResourceRecordType47;
        DnsResourceRecordType dnsResourceRecordType48 = new DnsResourceRecordType((short) 48, "DNSKEY");
        DNSKEY = dnsResourceRecordType48;
        DnsResourceRecordType dnsResourceRecordType49 = new DnsResourceRecordType((short) 49, "DHCID");
        DHCID = dnsResourceRecordType49;
        DnsResourceRecordType dnsResourceRecordType50 = new DnsResourceRecordType((short) 50, "NSEC3");
        NSEC3 = dnsResourceRecordType50;
        DnsResourceRecordType dnsResourceRecordType51 = new DnsResourceRecordType((short) 51, "NSEC3PARAM");
        NSEC3PARAM = dnsResourceRecordType51;
        DnsResourceRecordType dnsResourceRecordType52 = new DnsResourceRecordType((short) 52, "TLSA");
        TLSA = dnsResourceRecordType52;
        DnsResourceRecordType dnsResourceRecordType53 = new DnsResourceRecordType((short) 53, "SMIMEA (S/MIME cert association)");
        SMIMEA = dnsResourceRecordType53;
        DnsResourceRecordType dnsResourceRecordType54 = new DnsResourceRecordType((short) 55, "HIP (Host Identity Protocol)");
        HIP = dnsResourceRecordType54;
        DnsResourceRecordType dnsResourceRecordType55 = new DnsResourceRecordType((short) 56, "NINFO");
        NINFO = dnsResourceRecordType55;
        DnsResourceRecordType dnsResourceRecordType56 = new DnsResourceRecordType((short) 57, "RKEY");
        RKEY = dnsResourceRecordType56;
        DnsResourceRecordType dnsResourceRecordType57 = new DnsResourceRecordType((short) 58, "TALINK (Trust Anchor LINK)");
        TALINK = dnsResourceRecordType57;
        DnsResourceRecordType dnsResourceRecordType58 = new DnsResourceRecordType((short) 59, "CDS (Child DS)");
        CDS = dnsResourceRecordType58;
        DnsResourceRecordType dnsResourceRecordType59 = new DnsResourceRecordType((short) 60, "CDNSKEY (DNSKEY(s) the Child wants reflected in DS)");
        CDNSKEY = dnsResourceRecordType59;
        DnsResourceRecordType dnsResourceRecordType60 = new DnsResourceRecordType((short) 61, "OPENPGPKEY (OpenPGP Key)");
        OPENPGPKEY = dnsResourceRecordType60;
        DnsResourceRecordType dnsResourceRecordType61 = new DnsResourceRecordType((short) 62, "CSYNC (Child-To-Parent Synchronization)");
        CSYNC = dnsResourceRecordType61;
        DnsResourceRecordType dnsResourceRecordType62 = new DnsResourceRecordType((short) 99, "SPF");
        SPF = dnsResourceRecordType62;
        DnsResourceRecordType dnsResourceRecordType63 = new DnsResourceRecordType((short) 100, "UINFO");
        UINFO = dnsResourceRecordType63;
        DnsResourceRecordType dnsResourceRecordType64 = new DnsResourceRecordType((short) 101, "UID");
        UID = dnsResourceRecordType64;
        DnsResourceRecordType dnsResourceRecordType65 = new DnsResourceRecordType((short) 102, "GID");
        GID = dnsResourceRecordType65;
        DnsResourceRecordType dnsResourceRecordType66 = new DnsResourceRecordType((short) 103, "UNSPEC");
        UNSPEC = dnsResourceRecordType66;
        DnsResourceRecordType dnsResourceRecordType67 = new DnsResourceRecordType((short) 104, "NID");
        NID = dnsResourceRecordType67;
        DnsResourceRecordType dnsResourceRecordType68 = new DnsResourceRecordType((short) 105, "L32");
        L32 = dnsResourceRecordType68;
        DnsResourceRecordType dnsResourceRecordType69 = new DnsResourceRecordType((short) 106, "L64");
        L64 = dnsResourceRecordType69;
        DnsResourceRecordType dnsResourceRecordType70 = new DnsResourceRecordType((short) 107, "LP");
        LP = dnsResourceRecordType70;
        DnsResourceRecordType dnsResourceRecordType71 = new DnsResourceRecordType((short) 108, "EUI48 (EUI-48 address)");
        EUI48 = dnsResourceRecordType71;
        DnsResourceRecordType dnsResourceRecordType72 = new DnsResourceRecordType((short) 109, "EUI64 (EUI-64 address)");
        EUI64 = dnsResourceRecordType72;
        DnsResourceRecordType dnsResourceRecordType73 = new DnsResourceRecordType((short) 249, "TKEY (Transaction Key)");
        TKEY = dnsResourceRecordType73;
        DnsResourceRecordType dnsResourceRecordType74 = new DnsResourceRecordType((short) 250, "TSIG (Transaction Signature)");
        TSIG = dnsResourceRecordType74;
        DnsResourceRecordType dnsResourceRecordType75 = new DnsResourceRecordType((short) 251, "IXFR (Incremental transfer)");
        IXFR = dnsResourceRecordType75;
        DnsResourceRecordType dnsResourceRecordType76 = new DnsResourceRecordType((short) 252, "AXFR (Transfer of an entire zone)");
        AXFR = dnsResourceRecordType76;
        DnsResourceRecordType dnsResourceRecordType77 = new DnsResourceRecordType((short) 253, "MAILB (Mailbox-related RRs (MB, MG or MR))");
        MAILB = dnsResourceRecordType77;
        DnsResourceRecordType dnsResourceRecordType78 = new DnsResourceRecordType((short) 254, "MAILA (Mail agent RRs)");
        MAILA = dnsResourceRecordType78;
        DnsResourceRecordType dnsResourceRecordType79 = new DnsResourceRecordType((short) 255, "* (All records)");
        ALL_RECORDS = dnsResourceRecordType79;
        DnsResourceRecordType dnsResourceRecordType80 = new DnsResourceRecordType((short) 256, "URI");
        URI = dnsResourceRecordType80;
        DnsResourceRecordType dnsResourceRecordType81 = new DnsResourceRecordType((short) 257, "CAA (Certification Authority Restriction)");
        CAA = dnsResourceRecordType81;
        DnsResourceRecordType dnsResourceRecordType82 = new DnsResourceRecordType((short) 258, "AVC (Application Visibility and Control)");
        AVC = dnsResourceRecordType82;
        DnsResourceRecordType dnsResourceRecordType83 = new DnsResourceRecordType(Short.MIN_VALUE, "TA (DNSSEC Trust Authorities)");
        TA = dnsResourceRecordType83;
        DnsResourceRecordType dnsResourceRecordType84 = new DnsResourceRecordType((short) -32767, "DLV (DNSSEC Lookaside Validation)");
        DLV = dnsResourceRecordType84;
        HashMap map = new HashMap();
        registry = map;
        o40.L(dnsResourceRecordType, map, dnsResourceRecordType, dnsResourceRecordType2, dnsResourceRecordType2);
        o40.L(dnsResourceRecordType3, map, dnsResourceRecordType3, dnsResourceRecordType4, dnsResourceRecordType4);
        o40.L(dnsResourceRecordType5, map, dnsResourceRecordType5, dnsResourceRecordType6, dnsResourceRecordType6);
        o40.L(dnsResourceRecordType7, map, dnsResourceRecordType7, dnsResourceRecordType8, dnsResourceRecordType8);
        o40.L(dnsResourceRecordType9, map, dnsResourceRecordType9, dnsResourceRecordType10, dnsResourceRecordType10);
        o40.L(dnsResourceRecordType11, map, dnsResourceRecordType11, dnsResourceRecordType12, dnsResourceRecordType12);
        o40.L(dnsResourceRecordType13, map, dnsResourceRecordType13, dnsResourceRecordType14, dnsResourceRecordType14);
        o40.L(dnsResourceRecordType15, map, dnsResourceRecordType15, dnsResourceRecordType16, dnsResourceRecordType16);
        o40.L(dnsResourceRecordType17, map, dnsResourceRecordType17, dnsResourceRecordType18, dnsResourceRecordType18);
        o40.L(dnsResourceRecordType19, map, dnsResourceRecordType19, dnsResourceRecordType20, dnsResourceRecordType20);
        o40.L(dnsResourceRecordType21, map, dnsResourceRecordType21, dnsResourceRecordType22, dnsResourceRecordType22);
        o40.L(dnsResourceRecordType23, map, dnsResourceRecordType23, dnsResourceRecordType24, dnsResourceRecordType24);
        o40.L(dnsResourceRecordType25, map, dnsResourceRecordType25, dnsResourceRecordType26, dnsResourceRecordType26);
        o40.L(dnsResourceRecordType27, map, dnsResourceRecordType27, dnsResourceRecordType28, dnsResourceRecordType28);
        o40.L(dnsResourceRecordType29, map, dnsResourceRecordType29, dnsResourceRecordType30, dnsResourceRecordType30);
        o40.L(dnsResourceRecordType31, map, dnsResourceRecordType31, dnsResourceRecordType32, dnsResourceRecordType32);
        o40.L(dnsResourceRecordType33, map, dnsResourceRecordType33, dnsResourceRecordType34, dnsResourceRecordType34);
        o40.L(dnsResourceRecordType35, map, dnsResourceRecordType35, dnsResourceRecordType36, dnsResourceRecordType36);
        o40.L(dnsResourceRecordType37, map, dnsResourceRecordType37, dnsResourceRecordType38, dnsResourceRecordType38);
        o40.L(dnsResourceRecordType39, map, dnsResourceRecordType39, dnsResourceRecordType40, dnsResourceRecordType40);
        o40.L(dnsResourceRecordType41, map, dnsResourceRecordType41, dnsResourceRecordType42, dnsResourceRecordType42);
        o40.L(dnsResourceRecordType43, map, dnsResourceRecordType43, dnsResourceRecordType44, dnsResourceRecordType44);
        o40.L(dnsResourceRecordType45, map, dnsResourceRecordType45, dnsResourceRecordType46, dnsResourceRecordType46);
        o40.L(dnsResourceRecordType47, map, dnsResourceRecordType47, dnsResourceRecordType48, dnsResourceRecordType48);
        o40.L(dnsResourceRecordType49, map, dnsResourceRecordType49, dnsResourceRecordType50, dnsResourceRecordType50);
        o40.L(dnsResourceRecordType51, map, dnsResourceRecordType51, dnsResourceRecordType52, dnsResourceRecordType52);
        o40.L(dnsResourceRecordType53, map, dnsResourceRecordType53, dnsResourceRecordType54, dnsResourceRecordType54);
        o40.L(dnsResourceRecordType55, map, dnsResourceRecordType55, dnsResourceRecordType56, dnsResourceRecordType56);
        o40.L(dnsResourceRecordType57, map, dnsResourceRecordType57, dnsResourceRecordType58, dnsResourceRecordType58);
        o40.L(dnsResourceRecordType59, map, dnsResourceRecordType59, dnsResourceRecordType60, dnsResourceRecordType60);
        o40.L(dnsResourceRecordType61, map, dnsResourceRecordType61, dnsResourceRecordType62, dnsResourceRecordType62);
        o40.L(dnsResourceRecordType63, map, dnsResourceRecordType63, dnsResourceRecordType64, dnsResourceRecordType64);
        o40.L(dnsResourceRecordType65, map, dnsResourceRecordType65, dnsResourceRecordType66, dnsResourceRecordType66);
        o40.L(dnsResourceRecordType67, map, dnsResourceRecordType67, dnsResourceRecordType68, dnsResourceRecordType68);
        o40.L(dnsResourceRecordType69, map, dnsResourceRecordType69, dnsResourceRecordType70, dnsResourceRecordType70);
        o40.L(dnsResourceRecordType71, map, dnsResourceRecordType71, dnsResourceRecordType72, dnsResourceRecordType72);
        o40.L(dnsResourceRecordType73, map, dnsResourceRecordType73, dnsResourceRecordType74, dnsResourceRecordType74);
        o40.L(dnsResourceRecordType75, map, dnsResourceRecordType75, dnsResourceRecordType76, dnsResourceRecordType76);
        o40.L(dnsResourceRecordType77, map, dnsResourceRecordType77, dnsResourceRecordType78, dnsResourceRecordType78);
        o40.L(dnsResourceRecordType79, map, dnsResourceRecordType79, dnsResourceRecordType80, dnsResourceRecordType80);
        o40.L(dnsResourceRecordType81, map, dnsResourceRecordType81, dnsResourceRecordType82, dnsResourceRecordType82);
        o40.L(dnsResourceRecordType83, map, dnsResourceRecordType83, dnsResourceRecordType84, dnsResourceRecordType84);
    }

    public DnsResourceRecordType(Short sh, String str) {
        super(sh, str);
    }

    public static DnsResourceRecordType getInstance(Short sh) {
        Map<Short, DnsResourceRecordType> map = registry;
        return map.containsKey(sh) ? map.get(sh) : new DnsResourceRecordType(sh, "unknown");
    }

    public static DnsResourceRecordType register(DnsResourceRecordType dnsResourceRecordType) {
        return registry.put(dnsResourceRecordType.value(), dnsResourceRecordType);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public String valueAsString() {
        return String.valueOf(value().shortValue() & 65535);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public int compareTo(DnsResourceRecordType dnsResourceRecordType) {
        return value().compareTo(dnsResourceRecordType.value());
    }
}
