package org.pcap4j.packet.namednumber;

import defpackage.o40;
import java.util.HashMap;
import java.util.Map;
import org.pcap4j.packet.Dot11LinkAdaptationControl;

/* JADX INFO: loaded from: classes4.dex */
public final class Dot11InformationElementId extends NamedNumber<Byte, Dot11InformationElementId> {
    public static final Dot11InformationElementId ADVERTISEMENT_PROTOCOL;
    public static final Dot11InformationElementId ANTENNA;
    public static final Dot11InformationElementId AP_CHANNEL_REPORT;
    public static final Dot11InformationElementId AUTHENTICATED_MESH_PEERING_EXCHANGE;
    public static final Dot11InformationElementId BEACON_TIMING;
    public static final Dot11InformationElementId BSS_AC_ACCESS_DELAY;
    public static final Dot11InformationElementId BSS_AVAILABLE_ADMISSION_CAPACITY;
    public static final Dot11InformationElementId BSS_AVERAGE_ACCESS_DELAY;
    public static final Dot11InformationElementId BSS_LOAD;
    public static final Dot11InformationElementId BSS_MAX_IDLE_PERIOD;
    public static final Dot11InformationElementId CF_PARAMETER_SET;
    public static final Dot11InformationElementId CHALLENGE_TEXT;
    public static final Dot11InformationElementId CHANNEL_SWITCH_ANNOUNCEMENT;
    public static final Dot11InformationElementId CHANNEL_SWITCH_TIMING;
    public static final Dot11InformationElementId CHANNEL_USAGE;
    public static final Dot11InformationElementId COLLOCATED_INTERFERENCE_REPORT;
    public static final Dot11InformationElementId CONGESTION_NOTIFICATION;
    public static final Dot11InformationElementId COUNTRY;
    public static final Dot11InformationElementId DESTINATION_URI;
    public static final Dot11InformationElementId DIAGNOSTIC_REPORT;
    public static final Dot11InformationElementId DIAGNOSTIC_REQUEST;
    public static final Dot11InformationElementId DMS_REQUEST;
    public static final Dot11InformationElementId DMS_RESPONSE;
    public static final Dot11InformationElementId DSE_REGISTERED_LOCATION;
    public static final Dot11InformationElementId DSSS_PARAMETER_SET;
    public static final Dot11InformationElementId EDCA_PARAMETER_SET;
    public static final Dot11InformationElementId EMERGENCY_ALERT_IDENTIFIER;
    public static final Dot11InformationElementId ERP;
    public static final Dot11InformationElementId EVENT_REPORT;
    public static final Dot11InformationElementId EVENT_REQUEST;
    public static final Dot11InformationElementId EXPEDITED_BANDWIDTH_REQUEST;
    public static final Dot11InformationElementId EXTENDED_CAPABILITIES;
    public static final Dot11InformationElementId EXTENDED_CHANNEL_SWITCH_ANNOUNCEMENT;
    public static final Dot11InformationElementId EXTENDED_SUPPORTED_RATES;
    public static final Dot11InformationElementId FAST_BSS_TRANSITION;
    public static final Dot11InformationElementId FH_PARAMETER_SET;
    public static final Dot11InformationElementId FMS_DESCRIPTOR;
    public static final Dot11InformationElementId FMS_REQUEST;
    public static final Dot11InformationElementId FMS_RESPONSE;
    public static final Dot11InformationElementId GANN;
    public static final Dot11InformationElementId HOPPING_PATTERN_PARAMETERS;
    public static final Dot11InformationElementId HOPPING_PATTERN_TABLE;
    public static final Dot11InformationElementId HT_CAPABILITIES;
    public static final Dot11InformationElementId HT_OPERATION;
    public static final Dot11InformationElementId IBSS_DFS;
    public static final Dot11InformationElementId IBSS_PARAMETER_SET;
    public static final Dot11InformationElementId IE_20_40_BSS_COEXISTENCE;
    public static final Dot11InformationElementId IE_20_40_BSS_INTOLERANT_CHANNEL_REPORT;
    public static final Dot11InformationElementId INTERWORKING;
    public static final Dot11InformationElementId LINK_IDENTIFIER;
    public static final Dot11InformationElementId LOCATION_PARAMETERS;
    public static final Dot11InformationElementId MANAGEMENT_MIC;
    public static final Dot11InformationElementId MCCAOP_ADVERTISEMENT;
    public static final Dot11InformationElementId MCCAOP_ADVERTISEMENT_OVERVIEW;
    public static final Dot11InformationElementId MCCAOP_SETUP_REPLY;
    public static final Dot11InformationElementId MCCAOP_SETUP_REQUEST;
    public static final Dot11InformationElementId MCCAOP_TEARDOWN;
    public static final Dot11InformationElementId MEASUREMENT_PILOT_TRANSMISSION;
    public static final Dot11InformationElementId MEASUREMENT_REPORT;
    public static final Dot11InformationElementId MEASUREMENT_REQUEST;
    public static final Dot11InformationElementId MESH_AWAKE_WINDOW;
    public static final Dot11InformationElementId MESH_CHANNEL_SWITCH_PARAMETERS;
    public static final Dot11InformationElementId MESH_CONFIGURATION;
    public static final Dot11InformationElementId MESH_ID;
    public static final Dot11InformationElementId MESH_LINK_METRIC_REPORT;
    public static final Dot11InformationElementId MESH_PEERING_MANAGEMENT;
    public static final Dot11InformationElementId MIC;
    public static final Dot11InformationElementId MOBILITY_DOMAIN;
    public static final Dot11InformationElementId MULTIPLE_BSSID;
    public static final Dot11InformationElementId MULTIPLE_BSSID_INDEX;
    public static final Dot11InformationElementId NEIGHBOR_REPORT;
    public static final Dot11InformationElementId NONTRANSMITTED_BSSID_CAPABILITY;
    public static final Dot11InformationElementId OVERLAPPING_BSS_SCAN_PARAMETERS;
    public static final Dot11InformationElementId PERR;
    public static final Dot11InformationElementId POWER_CAPABILITY;
    public static final Dot11InformationElementId POWER_CONSTRAINT;
    public static final Dot11InformationElementId PREP;
    public static final Dot11InformationElementId PREQ;
    public static final Dot11InformationElementId PTI_CONTROL;
    public static final Dot11InformationElementId PXU;
    public static final Dot11InformationElementId PXUC;
    public static final Dot11InformationElementId QOS_CAPABILITY;
    public static final Dot11InformationElementId QOS_MAP_SET;
    public static final Dot11InformationElementId QOS_TRAFFIC_CAPABILITY;
    public static final Dot11InformationElementId QUIET;
    public static final Dot11InformationElementId RANN;
    public static final Dot11InformationElementId RCPI;
    public static final Dot11InformationElementId REQUEST;
    public static final Dot11InformationElementId RIC_DATA;
    public static final Dot11InformationElementId RIC_DESCRIPTOR;
    public static final Dot11InformationElementId RM_ENABLED_CAPABILITIES;
    public static final Dot11InformationElementId ROAMING_CONSORTIUM;
    public static final Dot11InformationElementId RSN;
    public static final Dot11InformationElementId RSNI;
    public static final Dot11InformationElementId SCHEDULE;
    public static final Dot11InformationElementId SECONDARY_CHANNEL_OFFSET;
    public static final Dot11InformationElementId SSID;
    public static final Dot11InformationElementId SSID_LIST;
    public static final Dot11InformationElementId SUPPORTED_CHANNELS;
    public static final Dot11InformationElementId SUPPORTED_OPERATING_CLASSES;
    public static final Dot11InformationElementId SUPPORTED_RATES;
    public static final Dot11InformationElementId TCLAS;
    public static final Dot11InformationElementId TCLAS_PROCESSING;
    public static final Dot11InformationElementId TFS_REQUEST;
    public static final Dot11InformationElementId TFS_RESPONSE;
    public static final Dot11InformationElementId TIM;
    public static final Dot11InformationElementId TIMEOUT_INTERVAL;
    public static final Dot11InformationElementId TIME_ADVERTISEMENT;
    public static final Dot11InformationElementId TIME_ZONE;
    public static final Dot11InformationElementId TIM_BROADCAST_REQUEST;
    public static final Dot11InformationElementId TIM_BROADCAST_RESPONSE;
    public static final Dot11InformationElementId TPC_REPORT;
    public static final Dot11InformationElementId TPC_REQUEST;
    public static final Dot11InformationElementId TPU_BUFFER_STATUS;
    public static final Dot11InformationElementId TSPEC;
    public static final Dot11InformationElementId TS_DELAY;
    public static final Dot11InformationElementId U_APSD_COEXISTENCE;
    public static final Dot11InformationElementId VENDOR_SPECIFIC;
    public static final Dot11InformationElementId WAKEUP_SCHEDULE;
    public static final Dot11InformationElementId WNM_SLEEP_MODE;
    private static final Map<Byte, Dot11InformationElementId> registry;
    private static final long serialVersionUID = -7844508106198134349L;

    static {
        Dot11InformationElementId dot11InformationElementId = new Dot11InformationElementId((byte) 0, "SSID");
        SSID = dot11InformationElementId;
        Dot11InformationElementId dot11InformationElementId2 = new Dot11InformationElementId((byte) 1, "Supported rates");
        SUPPORTED_RATES = dot11InformationElementId2;
        Dot11InformationElementId dot11InformationElementId3 = new Dot11InformationElementId((byte) 2, "FH Parameter Set");
        FH_PARAMETER_SET = dot11InformationElementId3;
        Dot11InformationElementId dot11InformationElementId4 = new Dot11InformationElementId((byte) 3, "DSSS Parameter Set");
        DSSS_PARAMETER_SET = dot11InformationElementId4;
        Dot11InformationElementId dot11InformationElementId5 = new Dot11InformationElementId((byte) 4, "CF Parameter Set");
        CF_PARAMETER_SET = dot11InformationElementId5;
        Dot11InformationElementId dot11InformationElementId6 = new Dot11InformationElementId((byte) 5, "TIM");
        TIM = dot11InformationElementId6;
        Dot11InformationElementId dot11InformationElementId7 = new Dot11InformationElementId((byte) 6, "IBSS Parameter Set");
        IBSS_PARAMETER_SET = dot11InformationElementId7;
        Dot11InformationElementId dot11InformationElementId8 = new Dot11InformationElementId((byte) 7, "Country");
        COUNTRY = dot11InformationElementId8;
        Dot11InformationElementId dot11InformationElementId9 = new Dot11InformationElementId((byte) 8, "Hopping Pattern Parameters");
        HOPPING_PATTERN_PARAMETERS = dot11InformationElementId9;
        Dot11InformationElementId dot11InformationElementId10 = new Dot11InformationElementId((byte) 9, "Hopping Pattern Table");
        HOPPING_PATTERN_TABLE = dot11InformationElementId10;
        Dot11InformationElementId dot11InformationElementId11 = new Dot11InformationElementId((byte) 10, "Request");
        REQUEST = dot11InformationElementId11;
        Dot11InformationElementId dot11InformationElementId12 = new Dot11InformationElementId((byte) 11, "BSS Load");
        BSS_LOAD = dot11InformationElementId12;
        Dot11InformationElementId dot11InformationElementId13 = new Dot11InformationElementId((byte) 12, "EDCA Parameter Set");
        EDCA_PARAMETER_SET = dot11InformationElementId13;
        Dot11InformationElementId dot11InformationElementId14 = new Dot11InformationElementId((byte) 13, "TSPEC");
        TSPEC = dot11InformationElementId14;
        Dot11InformationElementId dot11InformationElementId15 = new Dot11InformationElementId(Byte.valueOf(Dot11LinkAdaptationControl.ASELI), "TCLAS");
        TCLAS = dot11InformationElementId15;
        Dot11InformationElementId dot11InformationElementId16 = new Dot11InformationElementId((byte) 15, "Schedule");
        SCHEDULE = dot11InformationElementId16;
        Dot11InformationElementId dot11InformationElementId17 = new Dot11InformationElementId((byte) 16, "Challenge text");
        CHALLENGE_TEXT = dot11InformationElementId17;
        Dot11InformationElementId dot11InformationElementId18 = new Dot11InformationElementId((byte) 32, "Power Constraint");
        POWER_CONSTRAINT = dot11InformationElementId18;
        Dot11InformationElementId dot11InformationElementId19 = new Dot11InformationElementId((byte) 33, "Power Capability");
        POWER_CAPABILITY = dot11InformationElementId19;
        Dot11InformationElementId dot11InformationElementId20 = new Dot11InformationElementId((byte) 34, "TPC Request");
        TPC_REQUEST = dot11InformationElementId20;
        Dot11InformationElementId dot11InformationElementId21 = new Dot11InformationElementId((byte) 35, "TPC Report");
        TPC_REPORT = dot11InformationElementId21;
        Dot11InformationElementId dot11InformationElementId22 = new Dot11InformationElementId((byte) 36, "Supported Channels");
        SUPPORTED_CHANNELS = dot11InformationElementId22;
        Dot11InformationElementId dot11InformationElementId23 = new Dot11InformationElementId((byte) 37, "Channel Switch Announcement");
        CHANNEL_SWITCH_ANNOUNCEMENT = dot11InformationElementId23;
        Dot11InformationElementId dot11InformationElementId24 = new Dot11InformationElementId((byte) 38, "Measurement Request");
        MEASUREMENT_REQUEST = dot11InformationElementId24;
        Dot11InformationElementId dot11InformationElementId25 = new Dot11InformationElementId((byte) 39, "Measurement Report");
        MEASUREMENT_REPORT = dot11InformationElementId25;
        Dot11InformationElementId dot11InformationElementId26 = new Dot11InformationElementId((byte) 40, "Quiet");
        QUIET = dot11InformationElementId26;
        Dot11InformationElementId dot11InformationElementId27 = new Dot11InformationElementId((byte) 41, "IBSS DFS");
        IBSS_DFS = dot11InformationElementId27;
        Dot11InformationElementId dot11InformationElementId28 = new Dot11InformationElementId((byte) 42, "ERP");
        ERP = dot11InformationElementId28;
        Dot11InformationElementId dot11InformationElementId29 = new Dot11InformationElementId((byte) 43, "TS Delay");
        TS_DELAY = dot11InformationElementId29;
        Dot11InformationElementId dot11InformationElementId30 = new Dot11InformationElementId((byte) 44, "TCLAS Processing");
        TCLAS_PROCESSING = dot11InformationElementId30;
        Dot11InformationElementId dot11InformationElementId31 = new Dot11InformationElementId((byte) 45, "HT Capabilities");
        HT_CAPABILITIES = dot11InformationElementId31;
        Dot11InformationElementId dot11InformationElementId32 = new Dot11InformationElementId((byte) 46, "QoS Capability");
        QOS_CAPABILITY = dot11InformationElementId32;
        Dot11InformationElementId dot11InformationElementId33 = new Dot11InformationElementId((byte) 48, "RSN");
        RSN = dot11InformationElementId33;
        Dot11InformationElementId dot11InformationElementId34 = new Dot11InformationElementId((byte) 50, "Extended Supported Rates");
        EXTENDED_SUPPORTED_RATES = dot11InformationElementId34;
        Dot11InformationElementId dot11InformationElementId35 = new Dot11InformationElementId((byte) 51, "AP Channel Report");
        AP_CHANNEL_REPORT = dot11InformationElementId35;
        Dot11InformationElementId dot11InformationElementId36 = new Dot11InformationElementId((byte) 52, "Neighbor Report");
        NEIGHBOR_REPORT = dot11InformationElementId36;
        Dot11InformationElementId dot11InformationElementId37 = new Dot11InformationElementId((byte) 53, "RCPI");
        RCPI = dot11InformationElementId37;
        Dot11InformationElementId dot11InformationElementId38 = new Dot11InformationElementId((byte) 54, "Mobility Domain (MDE)");
        MOBILITY_DOMAIN = dot11InformationElementId38;
        Dot11InformationElementId dot11InformationElementId39 = new Dot11InformationElementId((byte) 55, "Fast BSS Transition (FTE)");
        FAST_BSS_TRANSITION = dot11InformationElementId39;
        Dot11InformationElementId dot11InformationElementId40 = new Dot11InformationElementId((byte) 56, "Timeout Interval");
        TIMEOUT_INTERVAL = dot11InformationElementId40;
        Dot11InformationElementId dot11InformationElementId41 = new Dot11InformationElementId((byte) 57, "RIC Data (RDE)");
        RIC_DATA = dot11InformationElementId41;
        Dot11InformationElementId dot11InformationElementId42 = new Dot11InformationElementId((byte) 58, "DSE Registered Location");
        DSE_REGISTERED_LOCATION = dot11InformationElementId42;
        Dot11InformationElementId dot11InformationElementId43 = new Dot11InformationElementId((byte) 59, "Supported Operating Classes");
        SUPPORTED_OPERATING_CLASSES = dot11InformationElementId43;
        Dot11InformationElementId dot11InformationElementId44 = new Dot11InformationElementId((byte) 60, "Extended Channel Switch Announcement");
        EXTENDED_CHANNEL_SWITCH_ANNOUNCEMENT = dot11InformationElementId44;
        Dot11InformationElementId dot11InformationElementId45 = new Dot11InformationElementId((byte) 61, "HT Operation");
        HT_OPERATION = dot11InformationElementId45;
        Dot11InformationElementId dot11InformationElementId46 = new Dot11InformationElementId((byte) 62, "Secondary Channel Offset");
        SECONDARY_CHANNEL_OFFSET = dot11InformationElementId46;
        Dot11InformationElementId dot11InformationElementId47 = new Dot11InformationElementId((byte) 63, "BSS Average Access Delay");
        BSS_AVERAGE_ACCESS_DELAY = dot11InformationElementId47;
        Dot11InformationElementId dot11InformationElementId48 = new Dot11InformationElementId((byte) 64, "Antenna");
        ANTENNA = dot11InformationElementId48;
        Dot11InformationElementId dot11InformationElementId49 = new Dot11InformationElementId((byte) 65, "RSNI");
        RSNI = dot11InformationElementId49;
        Dot11InformationElementId dot11InformationElementId50 = new Dot11InformationElementId((byte) 66, "Measurement Pilot Transmission");
        MEASUREMENT_PILOT_TRANSMISSION = dot11InformationElementId50;
        Dot11InformationElementId dot11InformationElementId51 = new Dot11InformationElementId((byte) 67, "BSS Available Admission Capacity");
        BSS_AVAILABLE_ADMISSION_CAPACITY = dot11InformationElementId51;
        Dot11InformationElementId dot11InformationElementId52 = new Dot11InformationElementId((byte) 68, "BSS AC Access Delay");
        BSS_AC_ACCESS_DELAY = dot11InformationElementId52;
        Dot11InformationElementId dot11InformationElementId53 = new Dot11InformationElementId((byte) 69, "Time Advertisement");
        TIME_ADVERTISEMENT = dot11InformationElementId53;
        Dot11InformationElementId dot11InformationElementId54 = new Dot11InformationElementId((byte) 70, "RM Enabled Capabilities");
        RM_ENABLED_CAPABILITIES = dot11InformationElementId54;
        Dot11InformationElementId dot11InformationElementId55 = new Dot11InformationElementId((byte) 71, "Multiple BSSID");
        MULTIPLE_BSSID = dot11InformationElementId55;
        Dot11InformationElementId dot11InformationElementId56 = new Dot11InformationElementId((byte) 72, "20/40 BSS Coexistence");
        IE_20_40_BSS_COEXISTENCE = dot11InformationElementId56;
        Dot11InformationElementId dot11InformationElementId57 = new Dot11InformationElementId((byte) 73, "20/40 BSS Intolerant Channel Report");
        IE_20_40_BSS_INTOLERANT_CHANNEL_REPORT = dot11InformationElementId57;
        Dot11InformationElementId dot11InformationElementId58 = new Dot11InformationElementId((byte) 74, "Overlapping BSS Scan Parameters");
        OVERLAPPING_BSS_SCAN_PARAMETERS = dot11InformationElementId58;
        Dot11InformationElementId dot11InformationElementId59 = new Dot11InformationElementId((byte) 75, "RIC Descriptor");
        RIC_DESCRIPTOR = dot11InformationElementId59;
        Dot11InformationElementId dot11InformationElementId60 = new Dot11InformationElementId((byte) 76, "Management MIC");
        MANAGEMENT_MIC = dot11InformationElementId60;
        Dot11InformationElementId dot11InformationElementId61 = new Dot11InformationElementId((byte) 78, "Event Request");
        EVENT_REQUEST = dot11InformationElementId61;
        Dot11InformationElementId dot11InformationElementId62 = new Dot11InformationElementId((byte) 79, "Event Report");
        EVENT_REPORT = dot11InformationElementId62;
        Dot11InformationElementId dot11InformationElementId63 = new Dot11InformationElementId((byte) 80, "Diagnostic Request");
        DIAGNOSTIC_REQUEST = dot11InformationElementId63;
        Dot11InformationElementId dot11InformationElementId64 = new Dot11InformationElementId((byte) 81, "Diagnostic Report");
        DIAGNOSTIC_REPORT = dot11InformationElementId64;
        Dot11InformationElementId dot11InformationElementId65 = new Dot11InformationElementId((byte) 82, "Location Parameters");
        LOCATION_PARAMETERS = dot11InformationElementId65;
        Dot11InformationElementId dot11InformationElementId66 = new Dot11InformationElementId((byte) 83, "Nontransmitted BSSID Capability");
        NONTRANSMITTED_BSSID_CAPABILITY = dot11InformationElementId66;
        Dot11InformationElementId dot11InformationElementId67 = new Dot11InformationElementId((byte) 84, "SSID List");
        SSID_LIST = dot11InformationElementId67;
        Dot11InformationElementId dot11InformationElementId68 = new Dot11InformationElementId((byte) 85, "Multiple BSSID-Index");
        MULTIPLE_BSSID_INDEX = dot11InformationElementId68;
        Dot11InformationElementId dot11InformationElementId69 = new Dot11InformationElementId((byte) 86, "FMS Descriptor");
        FMS_DESCRIPTOR = dot11InformationElementId69;
        Dot11InformationElementId dot11InformationElementId70 = new Dot11InformationElementId((byte) 87, "FMS Request");
        FMS_REQUEST = dot11InformationElementId70;
        Dot11InformationElementId dot11InformationElementId71 = new Dot11InformationElementId((byte) 88, "FMS Response");
        FMS_RESPONSE = dot11InformationElementId71;
        Dot11InformationElementId dot11InformationElementId72 = new Dot11InformationElementId((byte) 89, "QoS Traffic Capability");
        QOS_TRAFFIC_CAPABILITY = dot11InformationElementId72;
        Dot11InformationElementId dot11InformationElementId73 = new Dot11InformationElementId((byte) 90, "BSS Max Idle Period");
        BSS_MAX_IDLE_PERIOD = dot11InformationElementId73;
        Dot11InformationElementId dot11InformationElementId74 = new Dot11InformationElementId((byte) 91, "TFS Request");
        TFS_REQUEST = dot11InformationElementId74;
        Dot11InformationElementId dot11InformationElementId75 = new Dot11InformationElementId((byte) 92, "TFS Response");
        TFS_RESPONSE = dot11InformationElementId75;
        Dot11InformationElementId dot11InformationElementId76 = new Dot11InformationElementId((byte) 93, "WNM-Sleep Mode");
        WNM_SLEEP_MODE = dot11InformationElementId76;
        Dot11InformationElementId dot11InformationElementId77 = new Dot11InformationElementId((byte) 94, "TIM Broadcast Request");
        TIM_BROADCAST_REQUEST = dot11InformationElementId77;
        Dot11InformationElementId dot11InformationElementId78 = new Dot11InformationElementId((byte) 95, "TIM Broadcast Response");
        TIM_BROADCAST_RESPONSE = dot11InformationElementId78;
        Dot11InformationElementId dot11InformationElementId79 = new Dot11InformationElementId((byte) 96, "Collocated Interference Report");
        COLLOCATED_INTERFERENCE_REPORT = dot11InformationElementId79;
        Dot11InformationElementId dot11InformationElementId80 = new Dot11InformationElementId((byte) 97, "Channel Usage");
        CHANNEL_USAGE = dot11InformationElementId80;
        Dot11InformationElementId dot11InformationElementId81 = new Dot11InformationElementId((byte) 98, "Time Zone");
        TIME_ZONE = dot11InformationElementId81;
        Dot11InformationElementId dot11InformationElementId82 = new Dot11InformationElementId((byte) 99, "DMS Request");
        DMS_REQUEST = dot11InformationElementId82;
        Dot11InformationElementId dot11InformationElementId83 = new Dot11InformationElementId((byte) 100, "DMS Response");
        DMS_RESPONSE = dot11InformationElementId83;
        Dot11InformationElementId dot11InformationElementId84 = new Dot11InformationElementId((byte) 101, "Link Identifier");
        LINK_IDENTIFIER = dot11InformationElementId84;
        Dot11InformationElementId dot11InformationElementId85 = new Dot11InformationElementId((byte) 102, "Wakeup Schedule");
        WAKEUP_SCHEDULE = dot11InformationElementId85;
        Dot11InformationElementId dot11InformationElementId86 = new Dot11InformationElementId((byte) 104, "Channel Switch Timing");
        CHANNEL_SWITCH_TIMING = dot11InformationElementId86;
        Dot11InformationElementId dot11InformationElementId87 = new Dot11InformationElementId((byte) 105, "PTI Control");
        PTI_CONTROL = dot11InformationElementId87;
        Dot11InformationElementId dot11InformationElementId88 = new Dot11InformationElementId((byte) 106, "TPU Buffer Status");
        TPU_BUFFER_STATUS = dot11InformationElementId88;
        Dot11InformationElementId dot11InformationElementId89 = new Dot11InformationElementId((byte) 107, "Interworking");
        INTERWORKING = dot11InformationElementId89;
        Dot11InformationElementId dot11InformationElementId90 = new Dot11InformationElementId((byte) 108, "Advertisement Protocol");
        ADVERTISEMENT_PROTOCOL = dot11InformationElementId90;
        Dot11InformationElementId dot11InformationElementId91 = new Dot11InformationElementId((byte) 109, "Expedited Bandwidth Request");
        EXPEDITED_BANDWIDTH_REQUEST = dot11InformationElementId91;
        Dot11InformationElementId dot11InformationElementId92 = new Dot11InformationElementId((byte) 110, "QoS Map Set");
        QOS_MAP_SET = dot11InformationElementId92;
        Dot11InformationElementId dot11InformationElementId93 = new Dot11InformationElementId((byte) 111, "Roaming Consortium");
        ROAMING_CONSORTIUM = dot11InformationElementId93;
        Dot11InformationElementId dot11InformationElementId94 = new Dot11InformationElementId((byte) 112, "Emergency Alert Identifier");
        EMERGENCY_ALERT_IDENTIFIER = dot11InformationElementId94;
        Dot11InformationElementId dot11InformationElementId95 = new Dot11InformationElementId((byte) 113, "Mesh Configuration");
        MESH_CONFIGURATION = dot11InformationElementId95;
        Dot11InformationElementId dot11InformationElementId96 = new Dot11InformationElementId((byte) 114, "Mesh ID");
        MESH_ID = dot11InformationElementId96;
        Dot11InformationElementId dot11InformationElementId97 = new Dot11InformationElementId((byte) 115, "Mesh Link Metric Report");
        MESH_LINK_METRIC_REPORT = dot11InformationElementId97;
        Dot11InformationElementId dot11InformationElementId98 = new Dot11InformationElementId((byte) 116, "Congestion Notification");
        CONGESTION_NOTIFICATION = dot11InformationElementId98;
        Dot11InformationElementId dot11InformationElementId99 = new Dot11InformationElementId((byte) 117, "Mesh Peering Management");
        MESH_PEERING_MANAGEMENT = dot11InformationElementId99;
        Dot11InformationElementId dot11InformationElementId100 = new Dot11InformationElementId((byte) 118, "Mesh Channel Switch Parameters");
        MESH_CHANNEL_SWITCH_PARAMETERS = dot11InformationElementId100;
        Dot11InformationElementId dot11InformationElementId101 = new Dot11InformationElementId((byte) 119, "Mesh Awake Window");
        MESH_AWAKE_WINDOW = dot11InformationElementId101;
        Dot11InformationElementId dot11InformationElementId102 = new Dot11InformationElementId((byte) 120, "Beacon Timing");
        BEACON_TIMING = dot11InformationElementId102;
        Dot11InformationElementId dot11InformationElementId103 = new Dot11InformationElementId((byte) 121, "MCCAOP Setup Request");
        MCCAOP_SETUP_REQUEST = dot11InformationElementId103;
        Dot11InformationElementId dot11InformationElementId104 = new Dot11InformationElementId((byte) 122, "MCCAOP Setup Reply");
        MCCAOP_SETUP_REPLY = dot11InformationElementId104;
        Dot11InformationElementId dot11InformationElementId105 = new Dot11InformationElementId((byte) 123, "MCCAOP Advertisement");
        MCCAOP_ADVERTISEMENT = dot11InformationElementId105;
        Dot11InformationElementId dot11InformationElementId106 = new Dot11InformationElementId((byte) 124, "MCCAOP Teardown");
        MCCAOP_TEARDOWN = dot11InformationElementId106;
        Dot11InformationElementId dot11InformationElementId107 = new Dot11InformationElementId((byte) 125, "GANN");
        GANN = dot11InformationElementId107;
        Dot11InformationElementId dot11InformationElementId108 = new Dot11InformationElementId((byte) 126, "RANN");
        RANN = dot11InformationElementId108;
        Dot11InformationElementId dot11InformationElementId109 = new Dot11InformationElementId((byte) 127, "Extended Capabilities");
        EXTENDED_CAPABILITIES = dot11InformationElementId109;
        Dot11InformationElementId dot11InformationElementId110 = new Dot11InformationElementId((byte) -126, "PREQ");
        PREQ = dot11InformationElementId110;
        Dot11InformationElementId dot11InformationElementId111 = new Dot11InformationElementId((byte) -125, "PREP");
        PREP = dot11InformationElementId111;
        Dot11InformationElementId dot11InformationElementId112 = new Dot11InformationElementId((byte) -124, "PERR");
        PERR = dot11InformationElementId112;
        Dot11InformationElementId dot11InformationElementId113 = new Dot11InformationElementId((byte) -119, "PXU");
        PXU = dot11InformationElementId113;
        Dot11InformationElementId dot11InformationElementId114 = new Dot11InformationElementId((byte) -118, "PXUC");
        PXUC = dot11InformationElementId114;
        Dot11InformationElementId dot11InformationElementId115 = new Dot11InformationElementId((byte) -117, "Authenticated Mesh Peering Exchange");
        AUTHENTICATED_MESH_PEERING_EXCHANGE = dot11InformationElementId115;
        Dot11InformationElementId dot11InformationElementId116 = new Dot11InformationElementId((byte) -116, "MIC");
        MIC = dot11InformationElementId116;
        Dot11InformationElementId dot11InformationElementId117 = new Dot11InformationElementId((byte) -115, "Destination URI");
        DESTINATION_URI = dot11InformationElementId117;
        Dot11InformationElementId dot11InformationElementId118 = new Dot11InformationElementId((byte) -114, "U-APSD Coexistence");
        U_APSD_COEXISTENCE = dot11InformationElementId118;
        Dot11InformationElementId dot11InformationElementId119 = new Dot11InformationElementId((byte) -82, "MCCAOP Advertisement Overview");
        MCCAOP_ADVERTISEMENT_OVERVIEW = dot11InformationElementId119;
        Dot11InformationElementId dot11InformationElementId120 = new Dot11InformationElementId((byte) -35, "Vendor Specific");
        VENDOR_SPECIFIC = dot11InformationElementId120;
        HashMap map = new HashMap();
        registry = map;
        o40.M(dot11InformationElementId, map, dot11InformationElementId, dot11InformationElementId2, dot11InformationElementId2);
        o40.M(dot11InformationElementId3, map, dot11InformationElementId3, dot11InformationElementId4, dot11InformationElementId4);
        o40.M(dot11InformationElementId5, map, dot11InformationElementId5, dot11InformationElementId6, dot11InformationElementId6);
        o40.M(dot11InformationElementId7, map, dot11InformationElementId7, dot11InformationElementId8, dot11InformationElementId8);
        o40.M(dot11InformationElementId9, map, dot11InformationElementId9, dot11InformationElementId10, dot11InformationElementId10);
        o40.M(dot11InformationElementId11, map, dot11InformationElementId11, dot11InformationElementId12, dot11InformationElementId12);
        o40.M(dot11InformationElementId13, map, dot11InformationElementId13, dot11InformationElementId14, dot11InformationElementId14);
        o40.M(dot11InformationElementId15, map, dot11InformationElementId15, dot11InformationElementId16, dot11InformationElementId16);
        o40.M(dot11InformationElementId17, map, dot11InformationElementId17, dot11InformationElementId18, dot11InformationElementId18);
        o40.M(dot11InformationElementId19, map, dot11InformationElementId19, dot11InformationElementId20, dot11InformationElementId20);
        o40.M(dot11InformationElementId21, map, dot11InformationElementId21, dot11InformationElementId22, dot11InformationElementId22);
        o40.M(dot11InformationElementId23, map, dot11InformationElementId23, dot11InformationElementId24, dot11InformationElementId24);
        o40.M(dot11InformationElementId25, map, dot11InformationElementId25, dot11InformationElementId26, dot11InformationElementId26);
        o40.M(dot11InformationElementId27, map, dot11InformationElementId27, dot11InformationElementId28, dot11InformationElementId28);
        o40.M(dot11InformationElementId29, map, dot11InformationElementId29, dot11InformationElementId30, dot11InformationElementId30);
        o40.M(dot11InformationElementId31, map, dot11InformationElementId31, dot11InformationElementId32, dot11InformationElementId32);
        o40.M(dot11InformationElementId33, map, dot11InformationElementId33, dot11InformationElementId34, dot11InformationElementId34);
        o40.M(dot11InformationElementId35, map, dot11InformationElementId35, dot11InformationElementId36, dot11InformationElementId36);
        o40.M(dot11InformationElementId37, map, dot11InformationElementId37, dot11InformationElementId38, dot11InformationElementId38);
        o40.M(dot11InformationElementId39, map, dot11InformationElementId39, dot11InformationElementId40, dot11InformationElementId40);
        o40.M(dot11InformationElementId41, map, dot11InformationElementId41, dot11InformationElementId42, dot11InformationElementId42);
        o40.M(dot11InformationElementId43, map, dot11InformationElementId43, dot11InformationElementId44, dot11InformationElementId44);
        o40.M(dot11InformationElementId45, map, dot11InformationElementId45, dot11InformationElementId46, dot11InformationElementId46);
        o40.M(dot11InformationElementId47, map, dot11InformationElementId47, dot11InformationElementId48, dot11InformationElementId48);
        o40.M(dot11InformationElementId49, map, dot11InformationElementId49, dot11InformationElementId50, dot11InformationElementId50);
        o40.M(dot11InformationElementId51, map, dot11InformationElementId51, dot11InformationElementId52, dot11InformationElementId52);
        o40.M(dot11InformationElementId53, map, dot11InformationElementId53, dot11InformationElementId54, dot11InformationElementId54);
        o40.M(dot11InformationElementId55, map, dot11InformationElementId55, dot11InformationElementId56, dot11InformationElementId56);
        o40.M(dot11InformationElementId57, map, dot11InformationElementId57, dot11InformationElementId58, dot11InformationElementId58);
        o40.M(dot11InformationElementId59, map, dot11InformationElementId59, dot11InformationElementId60, dot11InformationElementId60);
        o40.M(dot11InformationElementId61, map, dot11InformationElementId61, dot11InformationElementId62, dot11InformationElementId62);
        o40.M(dot11InformationElementId63, map, dot11InformationElementId63, dot11InformationElementId64, dot11InformationElementId64);
        o40.M(dot11InformationElementId65, map, dot11InformationElementId65, dot11InformationElementId66, dot11InformationElementId66);
        o40.M(dot11InformationElementId67, map, dot11InformationElementId67, dot11InformationElementId68, dot11InformationElementId68);
        o40.M(dot11InformationElementId69, map, dot11InformationElementId69, dot11InformationElementId70, dot11InformationElementId70);
        o40.M(dot11InformationElementId71, map, dot11InformationElementId71, dot11InformationElementId72, dot11InformationElementId72);
        o40.M(dot11InformationElementId73, map, dot11InformationElementId73, dot11InformationElementId74, dot11InformationElementId74);
        o40.M(dot11InformationElementId75, map, dot11InformationElementId75, dot11InformationElementId76, dot11InformationElementId76);
        o40.M(dot11InformationElementId77, map, dot11InformationElementId77, dot11InformationElementId78, dot11InformationElementId78);
        o40.M(dot11InformationElementId79, map, dot11InformationElementId79, dot11InformationElementId80, dot11InformationElementId80);
        o40.M(dot11InformationElementId81, map, dot11InformationElementId81, dot11InformationElementId82, dot11InformationElementId82);
        o40.M(dot11InformationElementId83, map, dot11InformationElementId83, dot11InformationElementId84, dot11InformationElementId84);
        o40.M(dot11InformationElementId85, map, dot11InformationElementId85, dot11InformationElementId86, dot11InformationElementId86);
        o40.M(dot11InformationElementId87, map, dot11InformationElementId87, dot11InformationElementId88, dot11InformationElementId88);
        o40.M(dot11InformationElementId89, map, dot11InformationElementId89, dot11InformationElementId90, dot11InformationElementId90);
        o40.M(dot11InformationElementId91, map, dot11InformationElementId91, dot11InformationElementId92, dot11InformationElementId92);
        o40.M(dot11InformationElementId93, map, dot11InformationElementId93, dot11InformationElementId94, dot11InformationElementId94);
        o40.M(dot11InformationElementId95, map, dot11InformationElementId95, dot11InformationElementId96, dot11InformationElementId96);
        o40.M(dot11InformationElementId97, map, dot11InformationElementId97, dot11InformationElementId98, dot11InformationElementId98);
        o40.M(dot11InformationElementId99, map, dot11InformationElementId99, dot11InformationElementId100, dot11InformationElementId100);
        o40.M(dot11InformationElementId101, map, dot11InformationElementId101, dot11InformationElementId102, dot11InformationElementId102);
        o40.M(dot11InformationElementId103, map, dot11InformationElementId103, dot11InformationElementId104, dot11InformationElementId104);
        o40.M(dot11InformationElementId105, map, dot11InformationElementId105, dot11InformationElementId106, dot11InformationElementId106);
        o40.M(dot11InformationElementId107, map, dot11InformationElementId107, dot11InformationElementId108, dot11InformationElementId108);
        o40.M(dot11InformationElementId109, map, dot11InformationElementId109, dot11InformationElementId110, dot11InformationElementId110);
        o40.M(dot11InformationElementId111, map, dot11InformationElementId111, dot11InformationElementId112, dot11InformationElementId112);
        o40.M(dot11InformationElementId113, map, dot11InformationElementId113, dot11InformationElementId114, dot11InformationElementId114);
        o40.M(dot11InformationElementId115, map, dot11InformationElementId115, dot11InformationElementId116, dot11InformationElementId116);
        o40.M(dot11InformationElementId117, map, dot11InformationElementId117, dot11InformationElementId118, dot11InformationElementId118);
        o40.M(dot11InformationElementId119, map, dot11InformationElementId119, dot11InformationElementId120, dot11InformationElementId120);
    }

    public Dot11InformationElementId(Byte b, String str) {
        super(b, str);
    }

    public static Dot11InformationElementId getInstance(Byte b) {
        Map<Byte, Dot11InformationElementId> map = registry;
        return map.containsKey(b) ? map.get(b) : new Dot11InformationElementId(b, "unknown");
    }

    public static Dot11InformationElementId register(Dot11InformationElementId dot11InformationElementId) {
        return registry.put(dot11InformationElementId.value(), dot11InformationElementId);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public String valueAsString() {
        return String.valueOf(value().byteValue() & 255);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public int compareTo(Dot11InformationElementId dot11InformationElementId) {
        return value().compareTo(dot11InformationElementId.value());
    }
}
