package org.pcap4j.packet.namednumber;

import defpackage.dw1;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes4.dex */
public class GtpV2MessageType extends NamedNumber<Byte, GtpV2MessageType> {
    public static final GtpV2MessageType BEARER_RESOURCE_COMMAND;
    public static final GtpV2MessageType BEARER_RESOURCE_FAILURE_INDICATION;
    public static final GtpV2MessageType CHANGE_NOTIFICATION_REQUEST;
    public static final GtpV2MessageType CHANGE_NOTIFICATION_RESPONSE;
    public static final GtpV2MessageType CONFIGURATION_TRANSFER_TUNNEL;
    public static final GtpV2MessageType CONTEXT_ACKNOWLEDGE;
    public static final GtpV2MessageType CONTEXT_REQUEST;
    public static final GtpV2MessageType CONTEXT_RESPONSE;
    public static final GtpV2MessageType CREATE_BEARER_REQUEST;
    public static final GtpV2MessageType CREATE_BEARER_RESPONSE;
    public static final GtpV2MessageType CREATE_FORWARDING_TUNNEL_REQUEST;
    public static final GtpV2MessageType CREATE_FORWARDING_TUNNEL_RESPONSE;
    public static final GtpV2MessageType CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST;
    public static final GtpV2MessageType CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE;
    public static final GtpV2MessageType CREATE_SESSION_REQUEST;
    public static final GtpV2MessageType CREATE_SESSION_RESPONSE;
    public static final GtpV2MessageType CS_PAGING_INDICATION;
    public static final GtpV2MessageType DELETE_BEARER_COMMAND;
    public static final GtpV2MessageType DELETE_BEARER_FAILURE_INDICATION;
    public static final GtpV2MessageType DELETE_BEARER_REQUEST;
    public static final GtpV2MessageType DELETE_BEARER_RESPONSE;
    public static final GtpV2MessageType DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST;
    public static final GtpV2MessageType DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE;
    public static final GtpV2MessageType DELETE_PDN_CONNECTION_SET_REQUEST;
    public static final GtpV2MessageType DELETE_PDN_CONNECTION_SET_RESPONSE;
    public static final GtpV2MessageType DELETE_SESSION_REQUEST;
    public static final GtpV2MessageType DELETE_SESSION_RESPONSE;
    public static final GtpV2MessageType DETACH_ACKNOWLEDGE;
    public static final GtpV2MessageType DETACH_NOTIFICATION;
    public static final GtpV2MessageType DOWNLINK_DATA_NOTIFICATION;
    public static final GtpV2MessageType DOWNLINK_DATA_NOTIFICATION_ACKNOWLEDGE;
    public static final GtpV2MessageType DOWNLINK_DATA_NOTIFICATION_FAILURE_INDICATION;
    public static final GtpV2MessageType ECHO_REQUEST;
    public static final GtpV2MessageType ECHO_RESPONSE;
    public static final GtpV2MessageType FORWARD_ACCESS_CONTEXT_ACKNOWLEDGE;
    public static final GtpV2MessageType FORWARD_ACCESS_CONTEXT_NOTIFICATION;
    public static final GtpV2MessageType FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE;
    public static final GtpV2MessageType FORWARD_RELOCATION_COMPLETE_NOTIFICATION;
    public static final GtpV2MessageType FORWARD_RELOCATION_REQUEST;
    public static final GtpV2MessageType FORWARD_RELOCATION_RESPONSE;
    public static final GtpV2MessageType IDENTIFICATION_REQUEST;
    public static final GtpV2MessageType IDENTIFICATION_RESPONSE;
    public static final GtpV2MessageType MBMS_SESSION_START_REQUEST;
    public static final GtpV2MessageType MBMS_SESSION_START_RESPONSE;
    public static final GtpV2MessageType MBMS_SESSION_STOP_REQUEST;
    public static final GtpV2MessageType MBMS_SESSION_STOP_RESPONSE;
    public static final GtpV2MessageType MBMS_SESSION_UPDATE_REQUEST;
    public static final GtpV2MessageType MBMS_SESSION_UPDATE_RESPONSE;
    public static final GtpV2MessageType MODIFY_BEARER_COMMAND;
    public static final GtpV2MessageType MODIFY_BEARER_FAILURE_INDICATION;
    public static final GtpV2MessageType MODIFY_BEARER_REQUEST;
    public static final GtpV2MessageType MODIFY_BEARER_RESPONSE;
    public static final GtpV2MessageType RAN_INFORMATION_RELAY;
    public static final GtpV2MessageType RELEASE_ACCESS_BEARERS_REQUEST;
    public static final GtpV2MessageType RELEASE_ACCESS_BEARERS_RESPONSE;
    public static final GtpV2MessageType RELOCATION_CANCEL_REQUEST;
    public static final GtpV2MessageType RELOCATION_CANCEL_RESPONSE;
    public static final GtpV2MessageType RESUME_ACKNOWLEDGE;
    public static final GtpV2MessageType RESUME_NOTIFICATION;
    public static final GtpV2MessageType STOP_PAGING_INDICATION;
    public static final GtpV2MessageType SUSPEND_ACKNOWLEDGE;
    public static final GtpV2MessageType SUSPEND_NOTIFICATION;
    public static final GtpV2MessageType TRACE_SESSION_ACTIVATION;
    public static final GtpV2MessageType TRACE_SESSION_DEACTIVATION;
    public static final GtpV2MessageType UPDATE_BEARER_REQUEST;
    public static final GtpV2MessageType UPDATE_BEARER_RESPONSE;
    public static final GtpV2MessageType UPDATE_PDN_CONNECTION_SET_REQUEST;
    public static final GtpV2MessageType UPDATE_PDN_CONNECTION_SET_RESPONSE;
    public static final GtpV2MessageType VERSION_NOT_SUPPORTED;
    private static final Map<Byte, GtpV2MessageType> registry;
    private static final long serialVersionUID = -1996685364080926844L;

    static {
        GtpV2MessageType gtpV2MessageType = new GtpV2MessageType((byte) 1, "Echo Request");
        ECHO_REQUEST = gtpV2MessageType;
        GtpV2MessageType gtpV2MessageType2 = new GtpV2MessageType((byte) 2, "Echo Response");
        ECHO_RESPONSE = gtpV2MessageType2;
        GtpV2MessageType gtpV2MessageType3 = new GtpV2MessageType((byte) 3, "Version Not Supported");
        VERSION_NOT_SUPPORTED = gtpV2MessageType3;
        GtpV2MessageType gtpV2MessageType4 = new GtpV2MessageType((byte) 32, "Create Session Request");
        CREATE_SESSION_REQUEST = gtpV2MessageType4;
        GtpV2MessageType gtpV2MessageType5 = new GtpV2MessageType((byte) 33, "Create Session Response");
        CREATE_SESSION_RESPONSE = gtpV2MessageType5;
        GtpV2MessageType gtpV2MessageType6 = new GtpV2MessageType((byte) 34, "Modify Bearer Request");
        MODIFY_BEARER_REQUEST = gtpV2MessageType6;
        GtpV2MessageType gtpV2MessageType7 = new GtpV2MessageType((byte) 35, "Modify Bearer Response");
        MODIFY_BEARER_RESPONSE = gtpV2MessageType7;
        GtpV2MessageType gtpV2MessageType8 = new GtpV2MessageType((byte) 36, "Delete Session Request");
        DELETE_SESSION_REQUEST = gtpV2MessageType8;
        GtpV2MessageType gtpV2MessageType9 = new GtpV2MessageType((byte) 37, "Delete Session Response");
        DELETE_SESSION_RESPONSE = gtpV2MessageType9;
        GtpV2MessageType gtpV2MessageType10 = new GtpV2MessageType((byte) 38, "Change Notification Request");
        CHANGE_NOTIFICATION_REQUEST = gtpV2MessageType10;
        GtpV2MessageType gtpV2MessageType11 = new GtpV2MessageType((byte) 39, "Change Notification Response");
        CHANGE_NOTIFICATION_RESPONSE = gtpV2MessageType11;
        GtpV2MessageType gtpV2MessageType12 = new GtpV2MessageType((byte) 64, "Modify Bearer Command");
        MODIFY_BEARER_COMMAND = gtpV2MessageType12;
        GtpV2MessageType gtpV2MessageType13 = new GtpV2MessageType((byte) 65, "Modify Bearer Failure Indication");
        MODIFY_BEARER_FAILURE_INDICATION = gtpV2MessageType13;
        GtpV2MessageType gtpV2MessageType14 = new GtpV2MessageType((byte) 66, "Delete Bearer Command");
        DELETE_BEARER_COMMAND = gtpV2MessageType14;
        GtpV2MessageType gtpV2MessageType15 = new GtpV2MessageType((byte) 67, "Delete Bearer Failure Indication");
        DELETE_BEARER_FAILURE_INDICATION = gtpV2MessageType15;
        GtpV2MessageType gtpV2MessageType16 = new GtpV2MessageType((byte) 68, "Bearer Resource Command");
        BEARER_RESOURCE_COMMAND = gtpV2MessageType16;
        GtpV2MessageType gtpV2MessageType17 = new GtpV2MessageType((byte) 69, "Bearer Resource Failure Indication");
        BEARER_RESOURCE_FAILURE_INDICATION = gtpV2MessageType17;
        GtpV2MessageType gtpV2MessageType18 = new GtpV2MessageType((byte) 70, "Downlink Data Notification Failure Indication");
        DOWNLINK_DATA_NOTIFICATION_FAILURE_INDICATION = gtpV2MessageType18;
        GtpV2MessageType gtpV2MessageType19 = new GtpV2MessageType((byte) 71, "Trace Session Activation");
        TRACE_SESSION_ACTIVATION = gtpV2MessageType19;
        GtpV2MessageType gtpV2MessageType20 = new GtpV2MessageType((byte) 72, "Trace Session Deactivation");
        TRACE_SESSION_DEACTIVATION = gtpV2MessageType20;
        GtpV2MessageType gtpV2MessageType21 = new GtpV2MessageType((byte) 73, "Stop Paging Indication");
        STOP_PAGING_INDICATION = gtpV2MessageType21;
        GtpV2MessageType gtpV2MessageType22 = new GtpV2MessageType((byte) 95, "Create Bearer Request");
        CREATE_BEARER_REQUEST = gtpV2MessageType22;
        GtpV2MessageType gtpV2MessageType23 = new GtpV2MessageType((byte) 96, "Create Bearer Response");
        CREATE_BEARER_RESPONSE = gtpV2MessageType23;
        GtpV2MessageType gtpV2MessageType24 = new GtpV2MessageType((byte) 97, "Update Bearer Request");
        UPDATE_BEARER_REQUEST = gtpV2MessageType24;
        GtpV2MessageType gtpV2MessageType25 = new GtpV2MessageType((byte) 98, "Update Bearer Response");
        UPDATE_BEARER_RESPONSE = gtpV2MessageType25;
        GtpV2MessageType gtpV2MessageType26 = new GtpV2MessageType((byte) 99, "Delete Bearer Request");
        DELETE_BEARER_REQUEST = gtpV2MessageType26;
        GtpV2MessageType gtpV2MessageType27 = new GtpV2MessageType((byte) 100, "Delete Bearer Response");
        DELETE_BEARER_RESPONSE = gtpV2MessageType27;
        GtpV2MessageType gtpV2MessageType28 = new GtpV2MessageType((byte) 101, "Delete PDN Connection Set Request");
        DELETE_PDN_CONNECTION_SET_REQUEST = gtpV2MessageType28;
        DELETE_PDN_CONNECTION_SET_RESPONSE = new GtpV2MessageType((byte) 102, "Delete PDN Connection Set Response");
        GtpV2MessageType gtpV2MessageType29 = new GtpV2MessageType((byte) -128, "Identification Request");
        IDENTIFICATION_REQUEST = gtpV2MessageType29;
        GtpV2MessageType gtpV2MessageType30 = new GtpV2MessageType((byte) -127, "Identification Response");
        IDENTIFICATION_RESPONSE = gtpV2MessageType30;
        GtpV2MessageType gtpV2MessageType31 = new GtpV2MessageType((byte) -126, "Context Request");
        CONTEXT_REQUEST = gtpV2MessageType31;
        GtpV2MessageType gtpV2MessageType32 = new GtpV2MessageType((byte) -125, "Context Response");
        CONTEXT_RESPONSE = gtpV2MessageType32;
        GtpV2MessageType gtpV2MessageType33 = new GtpV2MessageType((byte) -124, "Context Acknowledge");
        CONTEXT_ACKNOWLEDGE = gtpV2MessageType33;
        GtpV2MessageType gtpV2MessageType34 = new GtpV2MessageType((byte) -123, "Forward Relocation Request");
        FORWARD_RELOCATION_REQUEST = gtpV2MessageType34;
        GtpV2MessageType gtpV2MessageType35 = new GtpV2MessageType((byte) -122, "Forward Relocation Response");
        FORWARD_RELOCATION_RESPONSE = gtpV2MessageType35;
        GtpV2MessageType gtpV2MessageType36 = new GtpV2MessageType((byte) -121, "Forward Relocation Complete Notification");
        FORWARD_RELOCATION_COMPLETE_NOTIFICATION = gtpV2MessageType36;
        GtpV2MessageType gtpV2MessageType37 = new GtpV2MessageType((byte) -120, "Forward Relocation Complete Acknowledge");
        FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE = gtpV2MessageType37;
        GtpV2MessageType gtpV2MessageType38 = new GtpV2MessageType((byte) -119, "Forward Access Context Notification");
        FORWARD_ACCESS_CONTEXT_NOTIFICATION = gtpV2MessageType38;
        GtpV2MessageType gtpV2MessageType39 = new GtpV2MessageType((byte) -118, "Forward Access Context Acknowledge");
        FORWARD_ACCESS_CONTEXT_ACKNOWLEDGE = gtpV2MessageType39;
        GtpV2MessageType gtpV2MessageType40 = new GtpV2MessageType((byte) -117, "Relocation Cancel Request");
        RELOCATION_CANCEL_REQUEST = gtpV2MessageType40;
        GtpV2MessageType gtpV2MessageType41 = new GtpV2MessageType((byte) -116, "Relocation Cancel Response");
        RELOCATION_CANCEL_RESPONSE = gtpV2MessageType41;
        GtpV2MessageType gtpV2MessageType42 = new GtpV2MessageType((byte) -115, "Configuration Transfer Tunnel");
        CONFIGURATION_TRANSFER_TUNNEL = gtpV2MessageType42;
        GtpV2MessageType gtpV2MessageType43 = new GtpV2MessageType((byte) -107, "Detach Notification");
        DETACH_NOTIFICATION = gtpV2MessageType43;
        GtpV2MessageType gtpV2MessageType44 = new GtpV2MessageType((byte) -106, "Detach Acknowledge");
        DETACH_ACKNOWLEDGE = gtpV2MessageType44;
        GtpV2MessageType gtpV2MessageType45 = new GtpV2MessageType((byte) -105, "CS Paging Indication");
        CS_PAGING_INDICATION = gtpV2MessageType45;
        GtpV2MessageType gtpV2MessageType46 = new GtpV2MessageType((byte) -104, "RAN Information Relay");
        RAN_INFORMATION_RELAY = gtpV2MessageType46;
        GtpV2MessageType gtpV2MessageType47 = new GtpV2MessageType((byte) -96, "Create Forwarding Tunnel Request");
        CREATE_FORWARDING_TUNNEL_REQUEST = gtpV2MessageType47;
        GtpV2MessageType gtpV2MessageType48 = new GtpV2MessageType((byte) -95, "Create Forwarding Tunnel Response");
        CREATE_FORWARDING_TUNNEL_RESPONSE = gtpV2MessageType48;
        GtpV2MessageType gtpV2MessageType49 = new GtpV2MessageType((byte) -94, "Suspend Notification");
        SUSPEND_NOTIFICATION = gtpV2MessageType49;
        GtpV2MessageType gtpV2MessageType50 = new GtpV2MessageType((byte) -93, "Suspend Acknowledge");
        SUSPEND_ACKNOWLEDGE = gtpV2MessageType50;
        GtpV2MessageType gtpV2MessageType51 = new GtpV2MessageType((byte) -92, "Resume Notification");
        RESUME_NOTIFICATION = gtpV2MessageType51;
        GtpV2MessageType gtpV2MessageType52 = new GtpV2MessageType((byte) -91, "Resume Acknowledge");
        RESUME_ACKNOWLEDGE = gtpV2MessageType52;
        GtpV2MessageType gtpV2MessageType53 = new GtpV2MessageType((byte) -90, "Create Indirect Data Forwarding Tunnel Request");
        CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST = gtpV2MessageType53;
        GtpV2MessageType gtpV2MessageType54 = new GtpV2MessageType((byte) -89, "Create Indirect Data Forwarding Tunnel Response");
        CREATE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE = gtpV2MessageType54;
        GtpV2MessageType gtpV2MessageType55 = new GtpV2MessageType((byte) -88, "Delete Indirect Data Forwarding Tunnel Request");
        DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_REQUEST = gtpV2MessageType55;
        GtpV2MessageType gtpV2MessageType56 = new GtpV2MessageType((byte) -87, "Delete Indirect Data Forwarding Tunnel Response");
        DELETE_INDIRECT_DATA_FORWARDING_TUNNEL_RESPONSE = gtpV2MessageType56;
        GtpV2MessageType gtpV2MessageType57 = new GtpV2MessageType((byte) -86, "Release Access Bearers Request");
        RELEASE_ACCESS_BEARERS_REQUEST = gtpV2MessageType57;
        GtpV2MessageType gtpV2MessageType58 = new GtpV2MessageType((byte) -85, "Release Access Bearers Response");
        RELEASE_ACCESS_BEARERS_RESPONSE = gtpV2MessageType58;
        GtpV2MessageType gtpV2MessageType59 = new GtpV2MessageType((byte) -80, "Downlink Data Notification");
        DOWNLINK_DATA_NOTIFICATION = gtpV2MessageType59;
        GtpV2MessageType gtpV2MessageType60 = new GtpV2MessageType((byte) -79, "Downlink Data Notification Acknowledge");
        DOWNLINK_DATA_NOTIFICATION_ACKNOWLEDGE = gtpV2MessageType60;
        GtpV2MessageType gtpV2MessageType61 = new GtpV2MessageType((byte) -56, "Update PDN Connection Set Request");
        UPDATE_PDN_CONNECTION_SET_REQUEST = gtpV2MessageType61;
        GtpV2MessageType gtpV2MessageType62 = new GtpV2MessageType((byte) -55, "Update PDN Connection Set Response");
        UPDATE_PDN_CONNECTION_SET_RESPONSE = gtpV2MessageType62;
        GtpV2MessageType gtpV2MessageType63 = new GtpV2MessageType((byte) -25, "MBMS Session Start Request");
        MBMS_SESSION_START_REQUEST = gtpV2MessageType63;
        GtpV2MessageType gtpV2MessageType64 = new GtpV2MessageType((byte) -24, "MBMS Session Start Response");
        MBMS_SESSION_START_RESPONSE = gtpV2MessageType64;
        GtpV2MessageType gtpV2MessageType65 = new GtpV2MessageType((byte) -23, "MBMS Session Update Request");
        MBMS_SESSION_UPDATE_REQUEST = gtpV2MessageType65;
        GtpV2MessageType gtpV2MessageType66 = new GtpV2MessageType((byte) -1, "MBMS Session Update Response");
        MBMS_SESSION_UPDATE_RESPONSE = gtpV2MessageType66;
        GtpV2MessageType gtpV2MessageType67 = new GtpV2MessageType((byte) -21, "MBMS Session Stop Request");
        MBMS_SESSION_STOP_REQUEST = gtpV2MessageType67;
        GtpV2MessageType gtpV2MessageType68 = new GtpV2MessageType((byte) -20, "MBMS Session Stop Response");
        MBMS_SESSION_STOP_RESPONSE = gtpV2MessageType68;
        HashMap map = new HashMap();
        registry = map;
        dw1.A(gtpV2MessageType, map, gtpV2MessageType, gtpV2MessageType2, gtpV2MessageType2);
        dw1.A(gtpV2MessageType3, map, gtpV2MessageType3, gtpV2MessageType4, gtpV2MessageType4);
        dw1.A(gtpV2MessageType5, map, gtpV2MessageType5, gtpV2MessageType6, gtpV2MessageType6);
        dw1.A(gtpV2MessageType7, map, gtpV2MessageType7, gtpV2MessageType8, gtpV2MessageType8);
        dw1.A(gtpV2MessageType9, map, gtpV2MessageType9, gtpV2MessageType10, gtpV2MessageType10);
        dw1.A(gtpV2MessageType11, map, gtpV2MessageType11, gtpV2MessageType12, gtpV2MessageType12);
        dw1.A(gtpV2MessageType13, map, gtpV2MessageType13, gtpV2MessageType14, gtpV2MessageType14);
        dw1.A(gtpV2MessageType15, map, gtpV2MessageType15, gtpV2MessageType16, gtpV2MessageType16);
        dw1.A(gtpV2MessageType17, map, gtpV2MessageType17, gtpV2MessageType18, gtpV2MessageType18);
        dw1.A(gtpV2MessageType19, map, gtpV2MessageType19, gtpV2MessageType20, gtpV2MessageType20);
        dw1.A(gtpV2MessageType21, map, gtpV2MessageType21, gtpV2MessageType22, gtpV2MessageType22);
        dw1.A(gtpV2MessageType23, map, gtpV2MessageType23, gtpV2MessageType24, gtpV2MessageType24);
        dw1.A(gtpV2MessageType25, map, gtpV2MessageType25, gtpV2MessageType26, gtpV2MessageType26);
        dw1.A(gtpV2MessageType27, map, gtpV2MessageType27, gtpV2MessageType28, gtpV2MessageType28);
        dw1.A(gtpV2MessageType56, map, gtpV2MessageType56, gtpV2MessageType29, gtpV2MessageType29);
        dw1.A(gtpV2MessageType30, map, gtpV2MessageType30, gtpV2MessageType31, gtpV2MessageType31);
        dw1.A(gtpV2MessageType32, map, gtpV2MessageType32, gtpV2MessageType33, gtpV2MessageType33);
        dw1.A(gtpV2MessageType34, map, gtpV2MessageType34, gtpV2MessageType35, gtpV2MessageType35);
        dw1.A(gtpV2MessageType36, map, gtpV2MessageType36, gtpV2MessageType37, gtpV2MessageType37);
        dw1.A(gtpV2MessageType38, map, gtpV2MessageType38, gtpV2MessageType39, gtpV2MessageType39);
        dw1.A(gtpV2MessageType40, map, gtpV2MessageType40, gtpV2MessageType41, gtpV2MessageType41);
        dw1.A(gtpV2MessageType42, map, gtpV2MessageType42, gtpV2MessageType46, gtpV2MessageType46);
        dw1.A(gtpV2MessageType43, map, gtpV2MessageType43, gtpV2MessageType44, gtpV2MessageType44);
        dw1.A(gtpV2MessageType45, map, gtpV2MessageType45, gtpV2MessageType49, gtpV2MessageType49);
        dw1.A(gtpV2MessageType50, map, gtpV2MessageType50, gtpV2MessageType47, gtpV2MessageType47);
        dw1.A(gtpV2MessageType48, map, gtpV2MessageType48, gtpV2MessageType51, gtpV2MessageType51);
        dw1.A(gtpV2MessageType52, map, gtpV2MessageType52, gtpV2MessageType53, gtpV2MessageType53);
        dw1.A(gtpV2MessageType54, map, gtpV2MessageType54, gtpV2MessageType55, gtpV2MessageType55);
        dw1.A(gtpV2MessageType56, map, gtpV2MessageType56, gtpV2MessageType57, gtpV2MessageType57);
        dw1.A(gtpV2MessageType58, map, gtpV2MessageType58, gtpV2MessageType59, gtpV2MessageType59);
        dw1.A(gtpV2MessageType60, map, gtpV2MessageType60, gtpV2MessageType61, gtpV2MessageType61);
        dw1.A(gtpV2MessageType62, map, gtpV2MessageType62, gtpV2MessageType63, gtpV2MessageType63);
        dw1.A(gtpV2MessageType64, map, gtpV2MessageType64, gtpV2MessageType65, gtpV2MessageType65);
        dw1.A(gtpV2MessageType66, map, gtpV2MessageType66, gtpV2MessageType67, gtpV2MessageType67);
        map.put(gtpV2MessageType68.value(), gtpV2MessageType68);
    }

    public GtpV2MessageType(Byte b, String str) {
        super(b, str);
    }

    public static GtpV2MessageType getInstance(Byte b) {
        Map<Byte, GtpV2MessageType> map = registry;
        return map.containsKey(b) ? map.get(b) : new GtpV2MessageType(b, "unknown");
    }

    public static GtpV2MessageType register(GtpV2MessageType gtpV2MessageType) {
        return registry.put(gtpV2MessageType.value(), gtpV2MessageType);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public String valueAsString() {
        return String.valueOf(value().byteValue() & 255);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public int compareTo(GtpV2MessageType gtpV2MessageType) {
        return value().compareTo(gtpV2MessageType.value());
    }
}
