package org.pcap4j.packet.namednumber;

import defpackage.dw1;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes4.dex */
public final class GtpV1MessageType extends NamedNumber<Byte, GtpV1MessageType> {
    public static final GtpV1MessageType CREATE_MBMS_CONTEXT_REQUEST;
    public static final GtpV1MessageType CREATE_MBMS_CONTEXT_RESPONSE;
    public static final GtpV1MessageType CREATE_PDP_CONTEXT_REQUEST;
    public static final GtpV1MessageType CREATE_PDP_CONTEXT_RESPONSE;
    public static final GtpV1MessageType DATA_RECORD_TRANSFER_REQUEST;
    public static final GtpV1MessageType DATA_RECORD_TRANSFER_RESPONSE;
    public static final GtpV1MessageType DELETE_MBMS_CONTEXT_REQUEST;
    public static final GtpV1MessageType DELETE_MBMS_CONTEXT_RESPONSE;
    public static final GtpV1MessageType DELETE_PDP_CONTEXT_REQUEST;
    public static final GtpV1MessageType DELETE_PDP_CONTEXT_RESPONSE;
    public static final GtpV1MessageType ECHO_REQUEST;
    public static final GtpV1MessageType ECHO_RESPONSE;
    public static final GtpV1MessageType END_MARKER;
    public static final GtpV1MessageType ERROR_INDICATION;
    public static final GtpV1MessageType FAILURE_REPORT_REQUEST;
    public static final GtpV1MessageType FAILURE_REPORT_RESPONSE;
    public static final GtpV1MessageType FORWARD_RELOCATION_COMPLETE;
    public static final GtpV1MessageType FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE;
    public static final GtpV1MessageType FORWARD_RELOCATION_REQUEST;
    public static final GtpV1MessageType FORWARD_RELOCATION_RESPONSE;
    public static final GtpV1MessageType FORWARD_SNRS_CONTEXT;
    public static final GtpV1MessageType FORWARD_SNRS_CONTEXT_ACKNOWLEDGE;
    public static final GtpV1MessageType G_PDU;
    public static final GtpV1MessageType IDENTIFICATION_REQUEST;
    public static final GtpV1MessageType IDENTIFICATION_RESPONSE;
    public static final GtpV1MessageType INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST;
    public static final GtpV1MessageType INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE;
    public static final GtpV1MessageType MBMS_DE_REGISTRATION_REQUEST;
    public static final GtpV1MessageType MBMS_DE_REGISTRATION_RESPONSE;
    public static final GtpV1MessageType MBMS_NOTIFICATION_REJECT_REQUEST;
    public static final GtpV1MessageType MBMS_NOTIFICATION_REJECT_RESPONSE;
    public static final GtpV1MessageType MBMS_NOTIFICATION_REQUEST;
    public static final GtpV1MessageType MBMS_NOTIFICATION_RESPONSE;
    public static final GtpV1MessageType MBMS_REGISTRATION_REQUEST;
    public static final GtpV1MessageType MBMS_REGISTRATION_RESPONSE;
    public static final GtpV1MessageType MBMS_SESSION_START_REQUEST;
    public static final GtpV1MessageType MBMS_SESSION_START_RESPONSE;
    public static final GtpV1MessageType MBMS_SESSION_STOP_REQUEST;
    public static final GtpV1MessageType MBMS_SESSION_STOP_RESPONSE;
    public static final GtpV1MessageType MBMS_SESSION_UPDATE_REQUEST;
    public static final GtpV1MessageType MBMS_SESSION_UPDATE_RESPONSE;
    public static final GtpV1MessageType MS_INFO_CHANGE_NOTIFICATION_REQUEST;
    public static final GtpV1MessageType MS_INFO_CHANGE_NOTIFICATION_RESPONSE;
    public static final GtpV1MessageType NODE_ALIVE_REQUEST;
    public static final GtpV1MessageType NODE_ALIVE_RESPONSE;
    public static final GtpV1MessageType NOTE_MS_GPRS_PRESENT_REQUEST;
    public static final GtpV1MessageType NOTE_MS_GPRS_PRESENT_RESPONSE;
    public static final GtpV1MessageType PDU_NOTIFICATION_REJECT_REQUEST;
    public static final GtpV1MessageType PDU_NOTIFICATION_REJECT_RESPONSE;
    public static final GtpV1MessageType PDU_NOTIFICATION_REQUEST;
    public static final GtpV1MessageType PDU_NOTIFICATION_RESPONSE;
    public static final GtpV1MessageType RAN_INFORMATION_RELAY;
    public static final GtpV1MessageType REDIRECTION_REQUEST;
    public static final GtpV1MessageType REDIRECTION_RESPONSE;
    public static final GtpV1MessageType RELOCATION_CANCEL_REQUEST;
    public static final GtpV1MessageType RELOCATION_CANCEL_RESPONSE;
    public static final GtpV1MessageType SEND_ROUTING_INFORMATION_FOR_GPRS_REQUEST;
    public static final GtpV1MessageType SEND_ROUTING_INFORMATION_FOR_GPRS_RESPONSE;
    public static final GtpV1MessageType SGSN_CONTEXT_ACKNOWLEDGE;
    public static final GtpV1MessageType SGSN_CONTEXT_REQUEST;
    public static final GtpV1MessageType SGSN_CONTEXT_RESPONSE;
    public static final GtpV1MessageType SUPPORTED_EXTENSION_HEADERS_NOTIFICATION;
    public static final GtpV1MessageType UPDATE_MBMS_CONTEXT_REQUEST;
    public static final GtpV1MessageType UPDATE_MBMS_CONTEXT_RESPONSE;
    public static final GtpV1MessageType UPDATE_PDP_CONTEXT_REQUEST;
    public static final GtpV1MessageType UPDATE_PDP_CONTEXT_RESPONSE;
    public static final GtpV1MessageType VERSION_NOT_SUPPORTED;
    private static final Map<Byte, GtpV1MessageType> registry;
    private static final long serialVersionUID = 7592798859079852877L;

    static {
        GtpV1MessageType gtpV1MessageType = new GtpV1MessageType((byte) 1, "Echo Request");
        ECHO_REQUEST = gtpV1MessageType;
        GtpV1MessageType gtpV1MessageType2 = new GtpV1MessageType((byte) 2, "Echo Response");
        ECHO_RESPONSE = gtpV1MessageType2;
        GtpV1MessageType gtpV1MessageType3 = new GtpV1MessageType((byte) 3, "Version Not Supported");
        VERSION_NOT_SUPPORTED = gtpV1MessageType3;
        GtpV1MessageType gtpV1MessageType4 = new GtpV1MessageType((byte) 4, "Node Alive Request");
        NODE_ALIVE_REQUEST = gtpV1MessageType4;
        GtpV1MessageType gtpV1MessageType5 = new GtpV1MessageType((byte) 5, "Node Alive Response");
        NODE_ALIVE_RESPONSE = gtpV1MessageType5;
        GtpV1MessageType gtpV1MessageType6 = new GtpV1MessageType((byte) 6, "Redirection Request");
        REDIRECTION_REQUEST = gtpV1MessageType6;
        GtpV1MessageType gtpV1MessageType7 = new GtpV1MessageType((byte) 7, "Redirection Response");
        REDIRECTION_RESPONSE = gtpV1MessageType7;
        GtpV1MessageType gtpV1MessageType8 = new GtpV1MessageType((byte) 16, "Create PDP Context Request");
        CREATE_PDP_CONTEXT_REQUEST = gtpV1MessageType8;
        GtpV1MessageType gtpV1MessageType9 = new GtpV1MessageType((byte) 17, "Create PDP Context Response");
        CREATE_PDP_CONTEXT_RESPONSE = gtpV1MessageType9;
        GtpV1MessageType gtpV1MessageType10 = new GtpV1MessageType((byte) 18, "Update PDP Context Request");
        UPDATE_PDP_CONTEXT_REQUEST = gtpV1MessageType10;
        GtpV1MessageType gtpV1MessageType11 = new GtpV1MessageType((byte) 19, "Update PDP Context Response");
        UPDATE_PDP_CONTEXT_RESPONSE = gtpV1MessageType11;
        GtpV1MessageType gtpV1MessageType12 = new GtpV1MessageType((byte) 20, "Delete PDP Context Request");
        DELETE_PDP_CONTEXT_REQUEST = gtpV1MessageType12;
        GtpV1MessageType gtpV1MessageType13 = new GtpV1MessageType((byte) 21, "Delete PDP Context Response");
        DELETE_PDP_CONTEXT_RESPONSE = gtpV1MessageType13;
        GtpV1MessageType gtpV1MessageType14 = new GtpV1MessageType((byte) 22, "Initiate PDP Context Activation Request");
        INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST = gtpV1MessageType14;
        GtpV1MessageType gtpV1MessageType15 = new GtpV1MessageType((byte) 22, "Initiate PDP Context Activation Response");
        INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE = gtpV1MessageType15;
        GtpV1MessageType gtpV1MessageType16 = new GtpV1MessageType((byte) 26, "Error Indication");
        ERROR_INDICATION = gtpV1MessageType16;
        GtpV1MessageType gtpV1MessageType17 = new GtpV1MessageType((byte) 27, "PDU Notification Request");
        PDU_NOTIFICATION_REQUEST = gtpV1MessageType17;
        GtpV1MessageType gtpV1MessageType18 = new GtpV1MessageType((byte) 28, "PDU Notification Response");
        PDU_NOTIFICATION_RESPONSE = gtpV1MessageType18;
        GtpV1MessageType gtpV1MessageType19 = new GtpV1MessageType((byte) 29, "PDU Notification Reject Request");
        PDU_NOTIFICATION_REJECT_REQUEST = gtpV1MessageType19;
        GtpV1MessageType gtpV1MessageType20 = new GtpV1MessageType((byte) 30, "PDU Notification Reject Response");
        PDU_NOTIFICATION_REJECT_RESPONSE = gtpV1MessageType20;
        GtpV1MessageType gtpV1MessageType21 = new GtpV1MessageType((byte) 31, "Supported Extension Headers Notification");
        SUPPORTED_EXTENSION_HEADERS_NOTIFICATION = gtpV1MessageType21;
        GtpV1MessageType gtpV1MessageType22 = new GtpV1MessageType((byte) 32, "Send Routing Information for GPRS Request");
        SEND_ROUTING_INFORMATION_FOR_GPRS_REQUEST = gtpV1MessageType22;
        GtpV1MessageType gtpV1MessageType23 = new GtpV1MessageType((byte) 33, "Send Routing Information for GPRS Response");
        SEND_ROUTING_INFORMATION_FOR_GPRS_RESPONSE = gtpV1MessageType23;
        GtpV1MessageType gtpV1MessageType24 = new GtpV1MessageType((byte) 34, "Failure Report Request");
        FAILURE_REPORT_REQUEST = gtpV1MessageType24;
        GtpV1MessageType gtpV1MessageType25 = new GtpV1MessageType((byte) 35, "Failure Report Response");
        FAILURE_REPORT_RESPONSE = gtpV1MessageType25;
        GtpV1MessageType gtpV1MessageType26 = new GtpV1MessageType((byte) 36, "Note MS GPRS Present Request");
        NOTE_MS_GPRS_PRESENT_REQUEST = gtpV1MessageType26;
        GtpV1MessageType gtpV1MessageType27 = new GtpV1MessageType((byte) 37, "Note MS GPRS Present Response");
        NOTE_MS_GPRS_PRESENT_RESPONSE = gtpV1MessageType27;
        GtpV1MessageType gtpV1MessageType28 = new GtpV1MessageType((byte) 48, "Identification Request");
        IDENTIFICATION_REQUEST = gtpV1MessageType28;
        GtpV1MessageType gtpV1MessageType29 = new GtpV1MessageType((byte) 49, "Identification Response");
        IDENTIFICATION_RESPONSE = gtpV1MessageType29;
        GtpV1MessageType gtpV1MessageType30 = new GtpV1MessageType((byte) 50, "SGSN Context Request");
        SGSN_CONTEXT_REQUEST = gtpV1MessageType30;
        GtpV1MessageType gtpV1MessageType31 = new GtpV1MessageType((byte) 51, "SGSN Context Response");
        SGSN_CONTEXT_RESPONSE = gtpV1MessageType31;
        GtpV1MessageType gtpV1MessageType32 = new GtpV1MessageType((byte) 52, "SGSN Context Acknowledge");
        SGSN_CONTEXT_ACKNOWLEDGE = gtpV1MessageType32;
        GtpV1MessageType gtpV1MessageType33 = new GtpV1MessageType((byte) 53, "Forward Relocation Request");
        FORWARD_RELOCATION_REQUEST = gtpV1MessageType33;
        GtpV1MessageType gtpV1MessageType34 = new GtpV1MessageType((byte) 54, "Forward Relocation Response");
        FORWARD_RELOCATION_RESPONSE = gtpV1MessageType34;
        GtpV1MessageType gtpV1MessageType35 = new GtpV1MessageType((byte) 55, "Forward Relocation Complete");
        FORWARD_RELOCATION_COMPLETE = gtpV1MessageType35;
        GtpV1MessageType gtpV1MessageType36 = new GtpV1MessageType((byte) 56, "Relocation Cancel Request");
        RELOCATION_CANCEL_REQUEST = gtpV1MessageType36;
        GtpV1MessageType gtpV1MessageType37 = new GtpV1MessageType((byte) 57, "Relocation Cancel Response");
        RELOCATION_CANCEL_RESPONSE = gtpV1MessageType37;
        GtpV1MessageType gtpV1MessageType38 = new GtpV1MessageType((byte) 58, "Forward SNRS Context");
        FORWARD_SNRS_CONTEXT = gtpV1MessageType38;
        GtpV1MessageType gtpV1MessageType39 = new GtpV1MessageType((byte) 59, "Forward Relocation Complete Acknowledge");
        FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE = gtpV1MessageType39;
        GtpV1MessageType gtpV1MessageType40 = new GtpV1MessageType((byte) 60, "Forward SNRS Context Acknowledge");
        FORWARD_SNRS_CONTEXT_ACKNOWLEDGE = gtpV1MessageType40;
        GtpV1MessageType gtpV1MessageType41 = new GtpV1MessageType((byte) 70, "RAN Information Relay");
        RAN_INFORMATION_RELAY = gtpV1MessageType41;
        GtpV1MessageType gtpV1MessageType42 = new GtpV1MessageType((byte) 96, "MBMS Notification Request");
        MBMS_NOTIFICATION_REQUEST = gtpV1MessageType42;
        GtpV1MessageType gtpV1MessageType43 = new GtpV1MessageType((byte) 97, "MBMS Notification Response");
        MBMS_NOTIFICATION_RESPONSE = gtpV1MessageType43;
        GtpV1MessageType gtpV1MessageType44 = new GtpV1MessageType((byte) 98, "MBMS Notification Request");
        MBMS_NOTIFICATION_REJECT_REQUEST = gtpV1MessageType44;
        GtpV1MessageType gtpV1MessageType45 = new GtpV1MessageType((byte) 99, "MBMS Notification Response");
        MBMS_NOTIFICATION_REJECT_RESPONSE = gtpV1MessageType45;
        GtpV1MessageType gtpV1MessageType46 = new GtpV1MessageType((byte) 100, "Create MBMS Context Request");
        CREATE_MBMS_CONTEXT_REQUEST = gtpV1MessageType46;
        GtpV1MessageType gtpV1MessageType47 = new GtpV1MessageType((byte) 101, "Create MBMS Context Response");
        CREATE_MBMS_CONTEXT_RESPONSE = gtpV1MessageType47;
        GtpV1MessageType gtpV1MessageType48 = new GtpV1MessageType((byte) 102, "Update MBMS Context Request");
        UPDATE_MBMS_CONTEXT_REQUEST = gtpV1MessageType48;
        GtpV1MessageType gtpV1MessageType49 = new GtpV1MessageType((byte) 103, "Update MBMS Context Response");
        UPDATE_MBMS_CONTEXT_RESPONSE = gtpV1MessageType49;
        GtpV1MessageType gtpV1MessageType50 = new GtpV1MessageType((byte) 104, "Delete MBMS Context Request");
        DELETE_MBMS_CONTEXT_REQUEST = gtpV1MessageType50;
        GtpV1MessageType gtpV1MessageType51 = new GtpV1MessageType((byte) 105, "Delete MBMS Context Response");
        DELETE_MBMS_CONTEXT_RESPONSE = gtpV1MessageType51;
        GtpV1MessageType gtpV1MessageType52 = new GtpV1MessageType((byte) 112, "MBMS Registration Request");
        MBMS_REGISTRATION_REQUEST = gtpV1MessageType52;
        GtpV1MessageType gtpV1MessageType53 = new GtpV1MessageType((byte) 113, "MBMS Registration Response");
        MBMS_REGISTRATION_RESPONSE = gtpV1MessageType53;
        GtpV1MessageType gtpV1MessageType54 = new GtpV1MessageType((byte) 114, "MBMS De Registration Request");
        MBMS_DE_REGISTRATION_REQUEST = gtpV1MessageType54;
        GtpV1MessageType gtpV1MessageType55 = new GtpV1MessageType((byte) 115, "MBMS De Registration Response");
        MBMS_DE_REGISTRATION_RESPONSE = gtpV1MessageType55;
        GtpV1MessageType gtpV1MessageType56 = new GtpV1MessageType((byte) 116, "MBMS Session Start Request");
        MBMS_SESSION_START_REQUEST = gtpV1MessageType56;
        GtpV1MessageType gtpV1MessageType57 = new GtpV1MessageType((byte) 117, "MBMS Session Start Response");
        MBMS_SESSION_START_RESPONSE = gtpV1MessageType57;
        GtpV1MessageType gtpV1MessageType58 = new GtpV1MessageType((byte) 118, "MBMS Session Stop Request");
        MBMS_SESSION_STOP_REQUEST = gtpV1MessageType58;
        GtpV1MessageType gtpV1MessageType59 = new GtpV1MessageType((byte) 119, "MBMS Session Stop Response");
        MBMS_SESSION_STOP_RESPONSE = gtpV1MessageType59;
        GtpV1MessageType gtpV1MessageType60 = new GtpV1MessageType((byte) 120, "MBMS Session Update Request");
        MBMS_SESSION_UPDATE_REQUEST = gtpV1MessageType60;
        GtpV1MessageType gtpV1MessageType61 = new GtpV1MessageType((byte) 121, "MBMS Session Update Response");
        MBMS_SESSION_UPDATE_RESPONSE = gtpV1MessageType61;
        GtpV1MessageType gtpV1MessageType62 = new GtpV1MessageType((byte) -128, "MS Info Change Notification Request");
        MS_INFO_CHANGE_NOTIFICATION_REQUEST = gtpV1MessageType62;
        GtpV1MessageType gtpV1MessageType63 = new GtpV1MessageType((byte) -127, "MS Info Change Notification Response");
        MS_INFO_CHANGE_NOTIFICATION_RESPONSE = gtpV1MessageType63;
        GtpV1MessageType gtpV1MessageType64 = new GtpV1MessageType((byte) -16, "Data Record Transfer Request");
        DATA_RECORD_TRANSFER_REQUEST = gtpV1MessageType64;
        GtpV1MessageType gtpV1MessageType65 = new GtpV1MessageType((byte) -15, "Data Record Transfer Response");
        DATA_RECORD_TRANSFER_RESPONSE = gtpV1MessageType65;
        GtpV1MessageType gtpV1MessageType66 = new GtpV1MessageType((byte) -2, "End Marker");
        END_MARKER = gtpV1MessageType66;
        GtpV1MessageType gtpV1MessageType67 = new GtpV1MessageType((byte) -1, "G-PDU");
        G_PDU = gtpV1MessageType67;
        HashMap map = new HashMap();
        registry = map;
        dw1.z(gtpV1MessageType, map, gtpV1MessageType, gtpV1MessageType2, gtpV1MessageType2);
        dw1.z(gtpV1MessageType3, map, gtpV1MessageType3, gtpV1MessageType4, gtpV1MessageType4);
        dw1.z(gtpV1MessageType5, map, gtpV1MessageType5, gtpV1MessageType6, gtpV1MessageType6);
        dw1.z(gtpV1MessageType7, map, gtpV1MessageType7, gtpV1MessageType8, gtpV1MessageType8);
        dw1.z(gtpV1MessageType9, map, gtpV1MessageType9, gtpV1MessageType10, gtpV1MessageType10);
        dw1.z(gtpV1MessageType11, map, gtpV1MessageType11, gtpV1MessageType12, gtpV1MessageType12);
        dw1.z(gtpV1MessageType13, map, gtpV1MessageType13, gtpV1MessageType14, gtpV1MessageType14);
        dw1.z(gtpV1MessageType15, map, gtpV1MessageType15, gtpV1MessageType16, gtpV1MessageType16);
        dw1.z(gtpV1MessageType17, map, gtpV1MessageType17, gtpV1MessageType18, gtpV1MessageType18);
        dw1.z(gtpV1MessageType19, map, gtpV1MessageType19, gtpV1MessageType20, gtpV1MessageType20);
        dw1.z(gtpV1MessageType21, map, gtpV1MessageType21, gtpV1MessageType22, gtpV1MessageType22);
        dw1.z(gtpV1MessageType23, map, gtpV1MessageType23, gtpV1MessageType24, gtpV1MessageType24);
        dw1.z(gtpV1MessageType25, map, gtpV1MessageType25, gtpV1MessageType26, gtpV1MessageType26);
        dw1.z(gtpV1MessageType27, map, gtpV1MessageType27, gtpV1MessageType28, gtpV1MessageType28);
        dw1.z(gtpV1MessageType29, map, gtpV1MessageType29, gtpV1MessageType30, gtpV1MessageType30);
        dw1.z(gtpV1MessageType31, map, gtpV1MessageType31, gtpV1MessageType32, gtpV1MessageType32);
        dw1.z(gtpV1MessageType33, map, gtpV1MessageType33, gtpV1MessageType34, gtpV1MessageType34);
        dw1.z(gtpV1MessageType35, map, gtpV1MessageType35, gtpV1MessageType39, gtpV1MessageType39);
        dw1.z(gtpV1MessageType36, map, gtpV1MessageType36, gtpV1MessageType37, gtpV1MessageType37);
        dw1.z(gtpV1MessageType38, map, gtpV1MessageType38, gtpV1MessageType40, gtpV1MessageType40);
        dw1.z(gtpV1MessageType41, map, gtpV1MessageType41, gtpV1MessageType42, gtpV1MessageType42);
        dw1.z(gtpV1MessageType43, map, gtpV1MessageType43, gtpV1MessageType44, gtpV1MessageType44);
        dw1.z(gtpV1MessageType45, map, gtpV1MessageType45, gtpV1MessageType46, gtpV1MessageType46);
        dw1.z(gtpV1MessageType47, map, gtpV1MessageType47, gtpV1MessageType48, gtpV1MessageType48);
        dw1.z(gtpV1MessageType49, map, gtpV1MessageType49, gtpV1MessageType50, gtpV1MessageType50);
        dw1.z(gtpV1MessageType51, map, gtpV1MessageType51, gtpV1MessageType52, gtpV1MessageType52);
        dw1.z(gtpV1MessageType53, map, gtpV1MessageType53, gtpV1MessageType54, gtpV1MessageType54);
        dw1.z(gtpV1MessageType55, map, gtpV1MessageType55, gtpV1MessageType56, gtpV1MessageType56);
        dw1.z(gtpV1MessageType57, map, gtpV1MessageType57, gtpV1MessageType58, gtpV1MessageType58);
        dw1.z(gtpV1MessageType59, map, gtpV1MessageType59, gtpV1MessageType60, gtpV1MessageType60);
        dw1.z(gtpV1MessageType61, map, gtpV1MessageType61, gtpV1MessageType62, gtpV1MessageType62);
        dw1.z(gtpV1MessageType63, map, gtpV1MessageType63, gtpV1MessageType64, gtpV1MessageType64);
        dw1.z(gtpV1MessageType65, map, gtpV1MessageType65, gtpV1MessageType66, gtpV1MessageType66);
        map.put(gtpV1MessageType67.value(), gtpV1MessageType67);
    }

    public GtpV1MessageType(Byte b, String str) {
        super(b, str);
    }

    public static GtpV1MessageType getInstance(Byte b) {
        Map<Byte, GtpV1MessageType> map = registry;
        return map.containsKey(b) ? map.get(b) : new GtpV1MessageType(b, "unknown");
    }

    public static GtpV1MessageType register(GtpV1MessageType gtpV1MessageType) {
        return registry.put(gtpV1MessageType.value(), gtpV1MessageType);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public String valueAsString() {
        return String.valueOf(value().byteValue() & 255);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public int compareTo(GtpV1MessageType gtpV1MessageType) {
        return value().compareTo(gtpV1MessageType.value());
    }
}
