package org.pcap4j.packet.namednumber;

import defpackage.dw1;
import java.util.HashMap;
import java.util.Map;
import org.pcap4j.packet.Dot11LinkAdaptationControl;

/* JADX INFO: loaded from: classes4.dex */
public final class IpNumber extends NamedNumber<Byte, IpNumber> {
    public static final IpNumber ACTIVE_NETWORKS;
    public static final IpNumber AH;
    public static final IpNumber ARGUS;
    public static final IpNumber ARIS;
    public static final IpNumber AX_25;
    public static final IpNumber BBN_RCC_MON;
    public static final IpNumber BNA;
    public static final IpNumber BR_SAT_MON;
    public static final IpNumber CBT;
    public static final IpNumber CFTP;
    public static final IpNumber CHAOS;
    public static final IpNumber COMPAQ_PEER;
    public static final IpNumber CPHB;
    public static final IpNumber CPNX;
    public static final IpNumber CRTP;
    public static final IpNumber CRUDP;
    public static final IpNumber DCCP;
    public static final IpNumber DCN_MEAS;
    public static final IpNumber DDP;
    public static final IpNumber DDX;
    public static final IpNumber DGP;
    public static final IpNumber DSR;
    public static final IpNumber EGP;
    public static final IpNumber EIGRP;
    public static final IpNumber EMCON;
    public static final IpNumber ENCAP;
    public static final IpNumber ESP;
    public static final IpNumber ETHERIP;
    public static final IpNumber FC;
    public static final IpNumber FIRE;
    public static final IpNumber GGP;
    public static final IpNumber GMTP;
    public static final IpNumber GRE;
    public static final IpNumber HIP;
    public static final IpNumber HMP;
    public static final IpNumber IATP;
    public static final IpNumber ICMPV4;
    public static final IpNumber ICMPV6;
    public static final IpNumber IDPR;
    public static final IpNumber IDPR_CMTP;
    public static final IpNumber IDRP;
    public static final IpNumber IFMP;
    public static final IpNumber IGMP;
    public static final IpNumber IGP;
    public static final IpNumber IL;
    public static final IpNumber IPCOMP;
    public static final IpNumber IPCV;
    public static final IpNumber IPIP;
    public static final IpNumber IPLT;
    public static final IpNumber IPPC;
    public static final IpNumber IPTM;
    public static final IpNumber IPV4;
    public static final IpNumber IPV6;
    public static final IpNumber IPV6_DST_OPTS;
    public static final IpNumber IPV6_FRAG;
    public static final IpNumber IPV6_HOPOPT;
    public static final IpNumber IPV6_NONXT;
    public static final IpNumber IPV6_ROUTE;
    public static final IpNumber IPX_IN_IP;
    public static final IpNumber IRTP;
    public static final IpNumber ISIS_OVER_IPV4;
    public static final IpNumber ISO_IP;
    public static final IpNumber ISO_TP4;
    public static final IpNumber I_NLSP;
    public static final IpNumber KRYPTOLAN;
    public static final IpNumber L2TP;
    public static final IpNumber LARP;
    public static final IpNumber LEAF_1;
    public static final IpNumber LEAF_2;
    public static final IpNumber MANET;
    public static final IpNumber MERIT_INP;
    public static final IpNumber MFE_NSP;
    public static final IpNumber MICP;
    public static final IpNumber MOBILE;
    public static final IpNumber MOBILITY_HEADER;
    public static final IpNumber MPLS_IN_IP;
    public static final IpNumber MTP;
    public static final IpNumber MUX;
    public static final IpNumber NARP;
    public static final IpNumber NETBLT;
    public static final IpNumber NSFNET_IGP;
    public static final IpNumber NVP_II;
    public static final IpNumber OSPFIGP;
    public static final IpNumber PGM;
    public static final IpNumber PIM;
    public static final IpNumber PIPE;
    public static final IpNumber PNNI;
    public static final IpNumber PRM;
    public static final IpNumber PTP;
    public static final IpNumber PUP;
    public static final IpNumber PVP;
    public static final IpNumber QNX;
    public static final IpNumber RDP;
    public static final IpNumber ROHC;
    public static final IpNumber RSVP;
    public static final IpNumber RSVP_E2E_IGNORE;
    public static final IpNumber RVD;
    public static final IpNumber SAT_EXPAK;
    public static final IpNumber SAT_MON;
    public static final IpNumber SCC_SP;
    public static final IpNumber SCPS;
    public static final IpNumber SCTP;
    public static final IpNumber SDRP;
    public static final IpNumber SECURE_VMTP;
    public static final IpNumber SHIM6;
    public static final IpNumber SKIP;
    public static final IpNumber SM;
    public static final IpNumber SMP;
    public static final IpNumber SNP;
    public static final IpNumber SPRITE_RPC;
    public static final IpNumber SPS;
    public static final IpNumber SRP;
    public static final IpNumber SSCOPMCE;
    public static final IpNumber ST;
    public static final IpNumber STP;
    public static final IpNumber SUN_ND;
    public static final IpNumber SWIPE;
    public static final IpNumber TCF;
    public static final IpNumber TCP;
    public static final IpNumber TLSP;
    public static final IpNumber TPC;
    public static final IpNumber TP_PP;
    public static final IpNumber TRUNK_1;
    public static final IpNumber TRUNK_2;
    public static final IpNumber TTP;
    public static final IpNumber UDP;
    public static final IpNumber UDPLITE;
    public static final IpNumber UTI;
    public static final IpNumber VINES;
    public static final IpNumber VISA;
    public static final IpNumber VMTP;
    public static final IpNumber VRRP;
    public static final IpNumber WB_EXPAK;
    public static final IpNumber WB_MON;
    public static final IpNumber WESP;
    public static final IpNumber WSN;
    public static final IpNumber XNET;
    public static final IpNumber XNS_IDP;
    public static final IpNumber XTP;
    private static final Map<Byte, IpNumber> registry;
    private static final long serialVersionUID = -3109332132272568136L;

    static {
        IpNumber ipNumber = new IpNumber((byte) 0, "IPv6 Hop-by-Hop Option");
        IPV6_HOPOPT = ipNumber;
        IpNumber ipNumber2 = new IpNumber((byte) 1, "ICMPv4");
        ICMPV4 = ipNumber2;
        IpNumber ipNumber3 = new IpNumber((byte) 2, "IGMP");
        IGMP = ipNumber3;
        IpNumber ipNumber4 = new IpNumber((byte) 3, "GGP");
        GGP = ipNumber4;
        IpNumber ipNumber5 = new IpNumber((byte) 4, "IPv4 encapsulation");
        IPV4 = ipNumber5;
        IpNumber ipNumber6 = new IpNumber((byte) 5, "Stream");
        ST = ipNumber6;
        IpNumber ipNumber7 = new IpNumber((byte) 6, "TCP");
        TCP = ipNumber7;
        IpNumber ipNumber8 = new IpNumber((byte) 7, "CBT");
        CBT = ipNumber8;
        IpNumber ipNumber9 = new IpNumber((byte) 8, "EGP");
        EGP = ipNumber9;
        IpNumber ipNumber10 = new IpNumber((byte) 9, "IGP");
        IGP = ipNumber10;
        IpNumber ipNumber11 = new IpNumber((byte) 10, "BBN RCC Monitoring");
        BBN_RCC_MON = ipNumber11;
        IpNumber ipNumber12 = new IpNumber((byte) 11, "NVP-II");
        NVP_II = ipNumber12;
        IpNumber ipNumber13 = new IpNumber((byte) 12, "PUP");
        PUP = ipNumber13;
        IpNumber ipNumber14 = new IpNumber((byte) 13, "ARGUS");
        ARGUS = ipNumber14;
        IpNumber ipNumber15 = new IpNumber(Byte.valueOf(Dot11LinkAdaptationControl.ASELI), "EMCON");
        EMCON = ipNumber15;
        IpNumber ipNumber16 = new IpNumber((byte) 15, "XNET");
        XNET = ipNumber16;
        IpNumber ipNumber17 = new IpNumber((byte) 16, "Chaos");
        CHAOS = ipNumber17;
        IpNumber ipNumber18 = new IpNumber((byte) 17, "UDP");
        UDP = ipNumber18;
        IpNumber ipNumber19 = new IpNumber((byte) 18, "Multiplexing");
        MUX = ipNumber19;
        IpNumber ipNumber20 = new IpNumber((byte) 19, "DCN-MEAS");
        DCN_MEAS = ipNumber20;
        IpNumber ipNumber21 = new IpNumber((byte) 20, "HMP");
        HMP = ipNumber21;
        IpNumber ipNumber22 = new IpNumber((byte) 21, "PRM");
        PRM = ipNumber22;
        IpNumber ipNumber23 = new IpNumber((byte) 22, "XEROX NS IDP");
        XNS_IDP = ipNumber23;
        IpNumber ipNumber24 = new IpNumber((byte) 23, "Trunk-1");
        TRUNK_1 = ipNumber24;
        IpNumber ipNumber25 = new IpNumber((byte) 24, "Trunk-2");
        TRUNK_2 = ipNumber25;
        IpNumber ipNumber26 = new IpNumber((byte) 25, "Leaf-1");
        LEAF_1 = ipNumber26;
        IpNumber ipNumber27 = new IpNumber((byte) 26, "Leaf-2");
        LEAF_2 = ipNumber27;
        IpNumber ipNumber28 = new IpNumber((byte) 27, "RDP");
        RDP = ipNumber28;
        IpNumber ipNumber29 = new IpNumber((byte) 28, "IRTP");
        IRTP = ipNumber29;
        IpNumber ipNumber30 = new IpNumber((byte) 29, "ISO-TP4");
        ISO_TP4 = ipNumber30;
        IpNumber ipNumber31 = new IpNumber((byte) 30, "NETBLT");
        NETBLT = ipNumber31;
        IpNumber ipNumber32 = new IpNumber((byte) 31, "MFE-NSP");
        MFE_NSP = ipNumber32;
        IpNumber ipNumber33 = new IpNumber((byte) 32, "MERIT-INP");
        MERIT_INP = ipNumber33;
        IpNumber ipNumber34 = new IpNumber((byte) 33, "DCCP");
        DCCP = ipNumber34;
        IpNumber ipNumber35 = new IpNumber((byte) 34, "3PC");
        TPC = ipNumber35;
        IpNumber ipNumber36 = new IpNumber((byte) 35, "IDPR");
        IDPR = ipNumber36;
        IpNumber ipNumber37 = new IpNumber((byte) 36, "XTP");
        XTP = ipNumber37;
        IpNumber ipNumber38 = new IpNumber((byte) 37, "DDP");
        DDP = ipNumber38;
        IpNumber ipNumber39 = new IpNumber((byte) 38, "IDPR-CMTP");
        IDPR_CMTP = ipNumber39;
        IpNumber ipNumber40 = new IpNumber((byte) 39, "TP++");
        TP_PP = ipNumber40;
        IpNumber ipNumber41 = new IpNumber((byte) 40, "IL");
        IL = ipNumber41;
        IpNumber ipNumber42 = new IpNumber((byte) 41, "IPv6 encapsulation");
        IPV6 = ipNumber42;
        IpNumber ipNumber43 = new IpNumber((byte) 42, "SDRP");
        SDRP = ipNumber43;
        IpNumber ipNumber44 = new IpNumber((byte) 43, "Routing Header for IPv6");
        IPV6_ROUTE = ipNumber44;
        IpNumber ipNumber45 = new IpNumber((byte) 44, "Fragment Header for IPv6");
        IPV6_FRAG = ipNumber45;
        IpNumber ipNumber46 = new IpNumber((byte) 45, "IDRP");
        IDRP = ipNumber46;
        IpNumber ipNumber47 = new IpNumber((byte) 46, "RSVP");
        RSVP = ipNumber47;
        IpNumber ipNumber48 = new IpNumber((byte) 47, "GRE");
        GRE = ipNumber48;
        IpNumber ipNumber49 = new IpNumber((byte) 48, "DSR");
        DSR = ipNumber49;
        IpNumber ipNumber50 = new IpNumber((byte) 49, "BNA");
        BNA = ipNumber50;
        IpNumber ipNumber51 = new IpNumber((byte) 50, "ESP");
        ESP = ipNumber51;
        IpNumber ipNumber52 = new IpNumber((byte) 51, "Authentication Header");
        AH = ipNumber52;
        IpNumber ipNumber53 = new IpNumber((byte) 52, "I-NLSP");
        I_NLSP = ipNumber53;
        IpNumber ipNumber54 = new IpNumber((byte) 53, "SWIPE");
        SWIPE = ipNumber54;
        IpNumber ipNumber55 = new IpNumber((byte) 54, "NARP");
        NARP = ipNumber55;
        IpNumber ipNumber56 = new IpNumber((byte) 55, "IP Mobility");
        MOBILE = ipNumber56;
        IpNumber ipNumber57 = new IpNumber((byte) 56, "TLSP");
        TLSP = ipNumber57;
        IpNumber ipNumber58 = new IpNumber((byte) 57, "SKIP");
        SKIP = ipNumber58;
        IpNumber ipNumber59 = new IpNumber((byte) 58, "ICMPv6");
        ICMPV6 = ipNumber59;
        IpNumber ipNumber60 = new IpNumber((byte) 59, "No Next Header for IPv6");
        IPV6_NONXT = ipNumber60;
        IpNumber ipNumber61 = new IpNumber((byte) 60, "Destination Options for IPv6");
        IPV6_DST_OPTS = ipNumber61;
        IpNumber ipNumber62 = new IpNumber((byte) 62, "CFTP");
        CFTP = ipNumber62;
        IpNumber ipNumber63 = new IpNumber((byte) 64, "SATNET and Backroom EXPAK");
        SAT_EXPAK = ipNumber63;
        IpNumber ipNumber64 = new IpNumber((byte) 65, "Kryptolan");
        KRYPTOLAN = ipNumber64;
        IpNumber ipNumber65 = new IpNumber((byte) 66, "RVD");
        RVD = ipNumber65;
        IpNumber ipNumber66 = new IpNumber((byte) 67, "IPPC");
        IPPC = ipNumber66;
        IpNumber ipNumber67 = new IpNumber((byte) 69, "SATNET Monitoring");
        SAT_MON = ipNumber67;
        IpNumber ipNumber68 = new IpNumber((byte) 70, "VISA");
        VISA = ipNumber68;
        IpNumber ipNumber69 = new IpNumber((byte) 71, "IPCV");
        IPCV = ipNumber69;
        IpNumber ipNumber70 = new IpNumber((byte) 72, "CPNX");
        CPNX = ipNumber70;
        IpNumber ipNumber71 = new IpNumber((byte) 73, "CPHB");
        CPHB = ipNumber71;
        IpNumber ipNumber72 = new IpNumber((byte) 74, "WSN");
        WSN = ipNumber72;
        IpNumber ipNumber73 = new IpNumber((byte) 75, "PVP");
        PVP = ipNumber73;
        IpNumber ipNumber74 = new IpNumber((byte) 76, "Backroom SATNET Monitoring");
        BR_SAT_MON = ipNumber74;
        IpNumber ipNumber75 = new IpNumber((byte) 77, "SUN-ND");
        SUN_ND = ipNumber75;
        IpNumber ipNumber76 = new IpNumber((byte) 78, "WIDEBAND Monitoring");
        WB_MON = ipNumber76;
        IpNumber ipNumber77 = new IpNumber((byte) 79, "WIDEBAND EXPAK");
        WB_EXPAK = ipNumber77;
        IpNumber ipNumber78 = new IpNumber((byte) 80, "ISO-IP");
        ISO_IP = ipNumber78;
        IpNumber ipNumber79 = new IpNumber((byte) 81, "VMTP");
        VMTP = ipNumber79;
        IpNumber ipNumber80 = new IpNumber((byte) 82, "SECURE-VMTP");
        SECURE_VMTP = ipNumber80;
        IpNumber ipNumber81 = new IpNumber((byte) 83, "VINES");
        VINES = ipNumber81;
        IpNumber ipNumber82 = new IpNumber((byte) 84, "TTP");
        TTP = ipNumber82;
        IpNumber ipNumber83 = new IpNumber((byte) 84, "IPTM");
        IPTM = ipNumber83;
        IpNumber ipNumber84 = new IpNumber((byte) 85, "NSFNET-IGP");
        NSFNET_IGP = ipNumber84;
        IpNumber ipNumber85 = new IpNumber((byte) 86, "DGP");
        DGP = ipNumber85;
        IpNumber ipNumber86 = new IpNumber((byte) 87, "TCF");
        TCF = ipNumber86;
        IpNumber ipNumber87 = new IpNumber((byte) 88, "EIGRP");
        EIGRP = ipNumber87;
        IpNumber ipNumber88 = new IpNumber((byte) 89, "OSPFIGP");
        OSPFIGP = ipNumber88;
        IpNumber ipNumber89 = new IpNumber((byte) 90, "Sprite RPC");
        SPRITE_RPC = ipNumber89;
        IpNumber ipNumber90 = new IpNumber((byte) 91, "LARP");
        LARP = ipNumber90;
        IpNumber ipNumber91 = new IpNumber((byte) 92, "MTP");
        MTP = ipNumber91;
        IpNumber ipNumber92 = new IpNumber((byte) 93, "AX.25");
        AX_25 = ipNumber92;
        IpNumber ipNumber93 = new IpNumber((byte) 94, "IPIP");
        IPIP = ipNumber93;
        IpNumber ipNumber94 = new IpNumber((byte) 95, "MICP");
        MICP = ipNumber94;
        IpNumber ipNumber95 = new IpNumber((byte) 96, "SCC-SP");
        SCC_SP = ipNumber95;
        IpNumber ipNumber96 = new IpNumber((byte) 97, "Ethernet-within-IP Encapsulation");
        ETHERIP = ipNumber96;
        IpNumber ipNumber97 = new IpNumber((byte) 98, "Encapsulation Header");
        ENCAP = ipNumber97;
        IpNumber ipNumber98 = new IpNumber((byte) 100, "GMTP");
        GMTP = ipNumber98;
        IpNumber ipNumber99 = new IpNumber((byte) 101, "IFMP");
        IFMP = ipNumber99;
        IpNumber ipNumber100 = new IpNumber((byte) 102, "PNNI over IP");
        PNNI = ipNumber100;
        IpNumber ipNumber101 = new IpNumber((byte) 103, "PIM");
        PIM = ipNumber101;
        IpNumber ipNumber102 = new IpNumber((byte) 104, "ARIS");
        ARIS = ipNumber102;
        IpNumber ipNumber103 = new IpNumber((byte) 105, "SCPS");
        SCPS = ipNumber103;
        IpNumber ipNumber104 = new IpNumber((byte) 106, "QNX");
        QNX = ipNumber104;
        IpNumber ipNumber105 = new IpNumber((byte) 107, "Active Networks");
        ACTIVE_NETWORKS = ipNumber105;
        IpNumber ipNumber106 = new IpNumber((byte) 108, "IPCOMP");
        IPCOMP = ipNumber106;
        IpNumber ipNumber107 = new IpNumber((byte) 109, "SNP");
        SNP = ipNumber107;
        IpNumber ipNumber108 = new IpNumber((byte) 110, "Compaq Peer");
        COMPAQ_PEER = ipNumber108;
        IpNumber ipNumber109 = new IpNumber((byte) 111, "IPX in IP");
        IPX_IN_IP = ipNumber109;
        IpNumber ipNumber110 = new IpNumber((byte) 112, "VRRP");
        VRRP = ipNumber110;
        IpNumber ipNumber111 = new IpNumber((byte) 113, "PGM");
        PGM = ipNumber111;
        IpNumber ipNumber112 = new IpNumber((byte) 115, "L2TP");
        L2TP = ipNumber112;
        IpNumber ipNumber113 = new IpNumber((byte) 116, "DDX");
        DDX = ipNumber113;
        IpNumber ipNumber114 = new IpNumber((byte) 117, "IATP");
        IATP = ipNumber114;
        IpNumber ipNumber115 = new IpNumber((byte) 118, "STP");
        STP = ipNumber115;
        IpNumber ipNumber116 = new IpNumber((byte) 119, "SRP");
        SRP = ipNumber116;
        IpNumber ipNumber117 = new IpNumber((byte) 120, "UTI");
        UTI = ipNumber117;
        IpNumber ipNumber118 = new IpNumber((byte) 121, "SMP");
        SMP = ipNumber118;
        IpNumber ipNumber119 = new IpNumber((byte) 122, "SM");
        SM = ipNumber119;
        IpNumber ipNumber120 = new IpNumber((byte) 123, "PTP");
        PTP = ipNumber120;
        IpNumber ipNumber121 = new IpNumber((byte) 124, "ISIS over IPv4");
        ISIS_OVER_IPV4 = ipNumber121;
        IpNumber ipNumber122 = new IpNumber((byte) 125, "FIRE");
        FIRE = ipNumber122;
        IpNumber ipNumber123 = new IpNumber((byte) 126, "CRTP");
        CRTP = ipNumber123;
        IpNumber ipNumber124 = new IpNumber((byte) 127, "CRUDP");
        CRUDP = ipNumber124;
        IpNumber ipNumber125 = new IpNumber((byte) -128, "SSCOPMCE");
        SSCOPMCE = ipNumber125;
        IpNumber ipNumber126 = new IpNumber((byte) -127, "IPLT");
        IPLT = ipNumber126;
        IpNumber ipNumber127 = new IpNumber((byte) -126, "SPS");
        SPS = ipNumber127;
        IpNumber ipNumber128 = new IpNumber((byte) -125, "PIPE");
        PIPE = ipNumber128;
        IpNumber ipNumber129 = new IpNumber((byte) -124, "SCTP");
        SCTP = ipNumber129;
        IpNumber ipNumber130 = new IpNumber((byte) -123, "Fibre Channel");
        FC = ipNumber130;
        IpNumber ipNumber131 = new IpNumber((byte) -122, "RSVP-E2E-IGNORE");
        RSVP_E2E_IGNORE = ipNumber131;
        IpNumber ipNumber132 = new IpNumber((byte) -121, "Mobility Header");
        MOBILITY_HEADER = ipNumber132;
        IpNumber ipNumber133 = new IpNumber((byte) -120, "UDPLite");
        UDPLITE = ipNumber133;
        IpNumber ipNumber134 = new IpNumber((byte) -119, "MPLS-in-IP");
        MPLS_IN_IP = ipNumber134;
        IpNumber ipNumber135 = new IpNumber((byte) -118, "MANET");
        MANET = ipNumber135;
        IpNumber ipNumber136 = new IpNumber((byte) -117, "HIP");
        HIP = ipNumber136;
        IpNumber ipNumber137 = new IpNumber((byte) -116, "Shim6");
        SHIM6 = ipNumber137;
        IpNumber ipNumber138 = new IpNumber((byte) -115, "WESP");
        WESP = ipNumber138;
        IpNumber ipNumber139 = new IpNumber((byte) -114, "ROHC");
        ROHC = ipNumber139;
        HashMap map = new HashMap();
        registry = map;
        dw1.B(ipNumber, map, ipNumber, ipNumber2, ipNumber2);
        dw1.B(ipNumber3, map, ipNumber3, ipNumber4, ipNumber4);
        dw1.B(ipNumber5, map, ipNumber5, ipNumber6, ipNumber6);
        dw1.B(ipNumber7, map, ipNumber7, ipNumber8, ipNumber8);
        dw1.B(ipNumber9, map, ipNumber9, ipNumber10, ipNumber10);
        dw1.B(ipNumber11, map, ipNumber11, ipNumber12, ipNumber12);
        dw1.B(ipNumber13, map, ipNumber13, ipNumber14, ipNumber14);
        dw1.B(ipNumber15, map, ipNumber15, ipNumber16, ipNumber16);
        dw1.B(ipNumber17, map, ipNumber17, ipNumber18, ipNumber18);
        dw1.B(ipNumber19, map, ipNumber19, ipNumber20, ipNumber20);
        dw1.B(ipNumber21, map, ipNumber21, ipNumber22, ipNumber22);
        dw1.B(ipNumber23, map, ipNumber23, ipNumber24, ipNumber24);
        dw1.B(ipNumber25, map, ipNumber25, ipNumber26, ipNumber26);
        dw1.B(ipNumber27, map, ipNumber27, ipNumber28, ipNumber28);
        dw1.B(ipNumber29, map, ipNumber29, ipNumber30, ipNumber30);
        dw1.B(ipNumber31, map, ipNumber31, ipNumber32, ipNumber32);
        dw1.B(ipNumber33, map, ipNumber33, ipNumber34, ipNumber34);
        dw1.B(ipNumber35, map, ipNumber35, ipNumber36, ipNumber36);
        dw1.B(ipNumber37, map, ipNumber37, ipNumber38, ipNumber38);
        dw1.B(ipNumber39, map, ipNumber39, ipNumber40, ipNumber40);
        dw1.B(ipNumber41, map, ipNumber41, ipNumber42, ipNumber42);
        dw1.B(ipNumber43, map, ipNumber43, ipNumber44, ipNumber44);
        dw1.B(ipNumber45, map, ipNumber45, ipNumber46, ipNumber46);
        dw1.B(ipNumber47, map, ipNumber47, ipNumber48, ipNumber48);
        dw1.B(ipNumber49, map, ipNumber49, ipNumber50, ipNumber50);
        dw1.B(ipNumber51, map, ipNumber51, ipNumber52, ipNumber52);
        dw1.B(ipNumber53, map, ipNumber53, ipNumber54, ipNumber54);
        dw1.B(ipNumber55, map, ipNumber55, ipNumber56, ipNumber56);
        dw1.B(ipNumber57, map, ipNumber57, ipNumber58, ipNumber58);
        dw1.B(ipNumber59, map, ipNumber59, ipNumber60, ipNumber60);
        dw1.B(ipNumber61, map, ipNumber61, ipNumber62, ipNumber62);
        dw1.B(ipNumber63, map, ipNumber63, ipNumber64, ipNumber64);
        dw1.B(ipNumber65, map, ipNumber65, ipNumber66, ipNumber66);
        dw1.B(ipNumber67, map, ipNumber67, ipNumber68, ipNumber68);
        dw1.B(ipNumber69, map, ipNumber69, ipNumber70, ipNumber70);
        dw1.B(ipNumber71, map, ipNumber71, ipNumber72, ipNumber72);
        dw1.B(ipNumber73, map, ipNumber73, ipNumber74, ipNumber74);
        dw1.B(ipNumber75, map, ipNumber75, ipNumber76, ipNumber76);
        dw1.B(ipNumber77, map, ipNumber77, ipNumber78, ipNumber78);
        dw1.B(ipNumber79, map, ipNumber79, ipNumber80, ipNumber80);
        dw1.B(ipNumber81, map, ipNumber81, ipNumber82, ipNumber82);
        dw1.B(ipNumber83, map, ipNumber83, ipNumber84, ipNumber84);
        dw1.B(ipNumber85, map, ipNumber85, ipNumber86, ipNumber86);
        dw1.B(ipNumber87, map, ipNumber87, ipNumber88, ipNumber88);
        dw1.B(ipNumber89, map, ipNumber89, ipNumber90, ipNumber90);
        dw1.B(ipNumber91, map, ipNumber91, ipNumber92, ipNumber92);
        dw1.B(ipNumber93, map, ipNumber93, ipNumber94, ipNumber94);
        dw1.B(ipNumber95, map, ipNumber95, ipNumber96, ipNumber96);
        dw1.B(ipNumber97, map, ipNumber97, ipNumber98, ipNumber98);
        dw1.B(ipNumber99, map, ipNumber99, ipNumber100, ipNumber100);
        dw1.B(ipNumber101, map, ipNumber101, ipNumber102, ipNumber102);
        dw1.B(ipNumber103, map, ipNumber103, ipNumber104, ipNumber104);
        dw1.B(ipNumber105, map, ipNumber105, ipNumber106, ipNumber106);
        dw1.B(ipNumber107, map, ipNumber107, ipNumber108, ipNumber108);
        dw1.B(ipNumber109, map, ipNumber109, ipNumber110, ipNumber110);
        dw1.B(ipNumber111, map, ipNumber111, ipNumber112, ipNumber112);
        dw1.B(ipNumber113, map, ipNumber113, ipNumber114, ipNumber114);
        dw1.B(ipNumber115, map, ipNumber115, ipNumber116, ipNumber116);
        dw1.B(ipNumber117, map, ipNumber117, ipNumber118, ipNumber118);
        dw1.B(ipNumber119, map, ipNumber119, ipNumber120, ipNumber120);
        dw1.B(ipNumber121, map, ipNumber121, ipNumber122, ipNumber122);
        dw1.B(ipNumber123, map, ipNumber123, ipNumber124, ipNumber124);
        dw1.B(ipNumber125, map, ipNumber125, ipNumber126, ipNumber126);
        dw1.B(ipNumber127, map, ipNumber127, ipNumber128, ipNumber128);
        dw1.B(ipNumber129, map, ipNumber129, ipNumber130, ipNumber130);
        dw1.B(ipNumber131, map, ipNumber131, ipNumber132, ipNumber132);
        dw1.B(ipNumber133, map, ipNumber133, ipNumber134, ipNumber134);
        dw1.B(ipNumber135, map, ipNumber135, ipNumber136, ipNumber136);
        dw1.B(ipNumber137, map, ipNumber137, ipNumber138, ipNumber138);
        map.put(ipNumber139.value(), ipNumber139);
    }

    public IpNumber(Byte b, String str) {
        super(b, str);
    }

    public static IpNumber getInstance(Byte b) {
        Map<Byte, IpNumber> map = registry;
        return map.containsKey(b) ? map.get(b) : new IpNumber(b, "unknown");
    }

    public static IpNumber register(IpNumber ipNumber) {
        return registry.put(ipNumber.value(), ipNumber);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public String valueAsString() {
        return String.valueOf(value().byteValue() & 255);
    }

    @Override // org.pcap4j.packet.namednumber.NamedNumber
    public int compareTo(IpNumber ipNumber) {
        return value().compareTo(ipNumber.value());
    }
}
