package defpackage;

import android.graphics.Bitmap;
import android.graphics.ColorFilter;
import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.Typeface;

/* JADX INFO: loaded from: classes.dex */
public interface ag4 {
    public static final Float A;
    public static final Float B;
    public static final Float C;
    public static final Float D;
    public static final Float E;
    public static final Float F;
    public static final Float G;
    public static final Float H;
    public static final ColorFilter I;
    public static final Integer[] J;
    public static final Typeface K;
    public static final Bitmap L;
    public static final String M;
    public static final Path N;
    public static final PointF a = new PointF();
    public static final PointF b = new PointF();
    public static final Float c;
    public static final Float d;
    public static final Float e;
    public static final PointF f;
    public static final PointF g;
    public static final Float h;
    public static final PointF i;
    public static final be7 j;
    public static final Float k;
    public static final Float l;
    public static final Float m;
    public static final Float n;
    public static final Float o;
    public static final Float p;
    public static final Float q;
    public static final Float r;
    public static final Float s;
    public static final Float t;
    public static final Float u;
    public static final Float v;
    public static final Float w;
    public static final Float x;
    public static final Float y;
    public static final Float z;

    static {
        Float fValueOf = Float.valueOf(15.0f);
        c = fValueOf;
        Float fValueOf2 = Float.valueOf(16.0f);
        d = fValueOf2;
        Float fValueOf3 = Float.valueOf(17.0f);
        e = fValueOf3;
        f = new PointF();
        g = new PointF();
        Float fValueOf4 = Float.valueOf(0.0f);
        h = fValueOf4;
        i = new PointF();
        j = new be7();
        k = Float.valueOf(1.0f);
        l = Float.valueOf(1.1f);
        m = Float.valueOf(1.2f);
        n = Float.valueOf(1.3f);
        o = fValueOf4;
        p = fValueOf4;
        q = Float.valueOf(2.0f);
        r = Float.valueOf(3.0f);
        s = Float.valueOf(4.0f);
        t = Float.valueOf(5.0f);
        u = Float.valueOf(6.0f);
        v = Float.valueOf(7.0f);
        w = Float.valueOf(8.0f);
        x = Float.valueOf(9.0f);
        y = Float.valueOf(10.0f);
        z = Float.valueOf(11.0f);
        A = Float.valueOf(12.0f);
        B = Float.valueOf(12.1f);
        C = Float.valueOf(13.0f);
        D = Float.valueOf(14.0f);
        E = fValueOf;
        F = fValueOf2;
        G = fValueOf3;
        H = Float.valueOf(18.0f);
        I = new ColorFilter();
        J = new Integer[0];
        K = Typeface.DEFAULT;
        L = Bitmap.createBitmap(1, 1, Bitmap.Config.ALPHA_8);
        M = "dynamic_text";
        N = new Path();
    }
}
