package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class bv8 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final fj2 D;
    public static final lr2 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final fj2 I;
    public static final lr2 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final fj2 N;
    public static final lr2 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final fj2 S;
    public static final lr2 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final fj2 X;
    public static final lr2 Y;
    public static final long Z;
    public static final lr2 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final fj2 c0;
    public static final long d;
    public static final lr2 d0;
    public static final fj2 e;
    public static final long e0;
    public static final lr2 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final fj2 h0;
    public static final long i;
    public static final lr2 i0;
    public static final fj2 j;
    public static final long j0;
    public static final lr2 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final fj2 m0;
    public static final long n;
    public static final lr2 n0;
    public static final fj2 o;
    public static final long o0;
    public static final lr2 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final fj2 r0;
    public static final long s;
    public static final lr2 s0;
    public static final fj2 t;
    public static final long t0;
    public static final lr2 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final fj2 w0;
    public static final long x;
    public static final fj2 y;
    public static final lr2 z;

    static {
        fj2 fj2Var = rv8.a;
        lr2 lr2Var = ph2.b;
        a = lr2Var;
        b = w07.d(24.0d);
        c = w07.e(16);
        d = w07.d(0.5d);
        fj2 fj2Var2 = rv8.b;
        e = fj2Var2;
        f = lr2Var;
        g = w07.d(20.0d);
        h = w07.e(14);
        i = w07.d(0.2d);
        j = fj2Var2;
        k = lr2Var;
        l = w07.d(16.0d);
        m = w07.e(12);
        n = w07.d(0.2d);
        o = fj2Var2;
        p = lr2Var;
        q = w07.d(64.0d);
        r = w07.e(57);
        long jD = w07.d(0.2d);
        kj8[] kj8VarArr = jj8.b;
        long j2 = jD & 1095216660480L;
        if (j2 == 0) {
            tn3.a("Cannot perform operation for Unspecified type.");
        }
        s = w07.h(-jj8.c(jD), j2);
        t = fj2Var2;
        u = lr2Var;
        v = w07.d(52.0d);
        w = w07.e(45);
        x = w07.d(0.0d);
        y = fj2Var2;
        z = lr2Var;
        A = w07.d(44.0d);
        B = w07.e(36);
        C = w07.d(0.0d);
        D = fj2Var2;
        E = lr2Var;
        F = w07.d(40.0d);
        G = w07.e(32);
        H = w07.d(0.0d);
        I = fj2Var2;
        J = lr2Var;
        K = w07.d(36.0d);
        L = w07.e(28);
        M = w07.d(0.0d);
        N = fj2Var2;
        O = lr2Var;
        P = w07.d(32.0d);
        Q = w07.e(24);
        R = w07.d(0.0d);
        S = fj2Var2;
        T = lr2Var;
        U = w07.d(20.0d);
        V = w07.e(14);
        W = w07.d(0.1d);
        fj2 fj2Var3 = rv8.a;
        X = fj2Var3;
        Y = lr2Var;
        Z = w07.d(16.0d);
        a0 = w07.e(12);
        b0 = w07.d(0.5d);
        c0 = fj2Var3;
        d0 = lr2Var;
        e0 = w07.d(16.0d);
        f0 = w07.e(11);
        g0 = w07.d(0.5d);
        h0 = fj2Var3;
        i0 = lr2Var;
        j0 = w07.d(28.0d);
        k0 = w07.e(22);
        l0 = w07.d(0.0d);
        m0 = fj2Var2;
        n0 = lr2Var;
        o0 = w07.d(24.0d);
        p0 = w07.e(16);
        q0 = w07.d(0.2d);
        r0 = fj2Var3;
        s0 = lr2Var;
        t0 = w07.d(20.0d);
        u0 = w07.e(14);
        v0 = w07.d(0.1d);
        w0 = fj2Var3;
    }
}
