package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class cv8 {
    public static final long A;
    public static final long A0;
    public static final lr2 A1;
    public static final long B;
    public static final fj2 B0;
    public static final long B1;
    public static final long C;
    public static final lr2 C0;
    public static final long C1;
    public static final fj2 D;
    public static final long D0;
    public static final long D1;
    public static final lr2 E;
    public static final long E0;
    public static final fj2 E1;
    public static final long F;
    public static final long F0;
    public static final lr2 F1;
    public static final long G;
    public static final fj2 G0;
    public static final long G1;
    public static final long H;
    public static final lr2 H0;
    public static final long H1;
    public static final fj2 I;
    public static final long I0;
    public static final long I1;
    public static final lr2 J;
    public static final long J0;
    public static final fj2 J1;
    public static final long K;
    public static final long K0;
    public static final lr2 K1;
    public static final long L;
    public static final fj2 L0;
    public static final long L1;
    public static final long M;
    public static final lr2 M0;
    public static final long M1;
    public static final fj2 N;
    public static final long N0;
    public static final long N1;
    public static final lr2 O;
    public static final long O0;
    public static final fj2 O1;
    public static final long P;
    public static final long P0;
    public static final lr2 P1;
    public static final long Q;
    public static final fj2 Q0;
    public static final long Q1;
    public static final long R;
    public static final lr2 R0;
    public static final long R1;
    public static final fj2 S;
    public static final long S0;
    public static final long S1;
    public static final lr2 T;
    public static final long T0;
    public static final fj2 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final fj2 V0;
    public static final long W;
    public static final lr2 W0;
    public static final fj2 X;
    public static final long X0;
    public static final lr2 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final lr2 a;
    public static final long a0;
    public static final fj2 a1;
    public static final long b;
    public static final long b0;
    public static final lr2 b1;
    public static final long c;
    public static final fj2 c0;
    public static final long c1;
    public static final long d;
    public static final lr2 d0;
    public static final long d1;
    public static final fj2 e;
    public static final long e0;
    public static final long e1;
    public static final lr2 f;
    public static final long f0;
    public static final fj2 f1;
    public static final long g;
    public static final long g0;
    public static final lr2 g1;
    public static final long h;
    public static final fj2 h0;
    public static final long h1;
    public static final long i;
    public static final lr2 i0;
    public static final long i1;
    public static final fj2 j;
    public static final long j0;
    public static final long j1;
    public static final lr2 k;
    public static final long k0;
    public static final fj2 k1;
    public static final long l;
    public static final long l0;
    public static final lr2 l1;
    public static final long m;
    public static final fj2 m0;
    public static final long m1;
    public static final long n;
    public static final lr2 n0;
    public static final long n1;
    public static final fj2 o;
    public static final long o0;
    public static final long o1;
    public static final lr2 p;
    public static final long p0;
    public static final fj2 p1;
    public static final long q;
    public static final long q0;
    public static final lr2 q1;
    public static final long r;
    public static final fj2 r0;
    public static final long r1;
    public static final long s;
    public static final lr2 s0;
    public static final long s1;
    public static final fj2 t;
    public static final long t0;
    public static final long t1;
    public static final lr2 u;
    public static final long u0;
    public static final fj2 u1;
    public static final long v;
    public static final long v0;
    public static final lr2 v1;
    public static final long w;
    public static final fj2 w0;
    public static final long w1;
    public static final long x;
    public static final lr2 x0;
    public static final long x1;
    public static final fj2 y;
    public static final long y0;
    public static final long y1;
    public static final lr2 z;
    public static final long z0;
    public static final fj2 z1;

    static {
        fj2 fj2Var = sv8.a;
        lr2 lr2Var = ph2.b;
        a = lr2Var;
        b = w07.d(24.0d);
        c = w07.e(16);
        d = w07.d(0.5d);
        fj2 fj2Var2 = sv8.c;
        e = fj2Var2;
        f = lr2Var;
        g = w07.d(20.0d);
        h = w07.e(14);
        i = w07.d(0.2d);
        j = fj2Var2;
        k = lr2Var;
        l = w07.d(16.0d);
        m = w07.e(12);
        n = w07.d(0.4d);
        o = fj2Var2;
        p = lr2Var;
        q = w07.d(64.0d);
        r = w07.e(57);
        long jD = w07.d(0.2d);
        kj8[] kj8VarArr = jj8.b;
        long j2 = jD & 1095216660480L;
        if (j2 == 0) {
            tn3.a("Cannot perform operation for Unspecified type.");
        }
        s = w07.h(-jj8.c(jD), j2);
        t = fj2Var2;
        u = lr2Var;
        v = w07.d(52.0d);
        w = w07.e(45);
        x = w07.d(0.0d);
        y = fj2Var2;
        z = lr2Var;
        A = w07.d(44.0d);
        B = w07.e(36);
        C = w07.d(0.0d);
        D = fj2Var2;
        E = lr2Var;
        F = w07.d(40.0d);
        G = w07.e(32);
        H = w07.d(0.0d);
        I = fj2Var2;
        J = lr2Var;
        K = w07.d(36.0d);
        L = w07.e(28);
        M = w07.d(0.0d);
        N = fj2Var2;
        O = lr2Var;
        P = w07.d(32.0d);
        Q = w07.e(24);
        R = w07.d(0.0d);
        S = fj2Var2;
        T = lr2Var;
        U = w07.d(20.0d);
        V = w07.e(14);
        W = w07.d(0.1d);
        fj2 fj2Var3 = sv8.b;
        X = fj2Var3;
        Y = lr2Var;
        Z = w07.d(16.0d);
        a0 = w07.e(12);
        b0 = w07.d(0.5d);
        c0 = fj2Var3;
        d0 = lr2Var;
        e0 = w07.d(16.0d);
        f0 = w07.e(11);
        g0 = w07.d(0.5d);
        h0 = fj2Var3;
        i0 = lr2Var;
        j0 = w07.d(28.0d);
        k0 = w07.e(22);
        l0 = w07.d(0.0d);
        m0 = fj2Var2;
        n0 = lr2Var;
        o0 = w07.d(24.0d);
        p0 = w07.e(16);
        q0 = w07.d(0.2d);
        r0 = fj2Var3;
        s0 = lr2Var;
        t0 = w07.d(20.0d);
        u0 = w07.e(14);
        v0 = w07.d(0.1d);
        w0 = fj2Var3;
        x0 = lr2Var;
        y0 = w07.d(24.0d);
        z0 = w07.e(16);
        A0 = w07.d(0.15d);
        B0 = fj2Var3;
        C0 = lr2Var;
        D0 = w07.d(20.0d);
        E0 = w07.e(14);
        F0 = w07.d(0.25d);
        G0 = fj2Var3;
        H0 = lr2Var;
        I0 = w07.d(16.0d);
        J0 = w07.e(12);
        K0 = w07.d(0.4d);
        L0 = fj2Var3;
        M0 = lr2Var;
        N0 = w07.d(64.0d);
        O0 = w07.e(57);
        P0 = w07.e(0);
        Q0 = fj2Var3;
        R0 = lr2Var;
        S0 = w07.d(52.0d);
        T0 = w07.e(45);
        U0 = w07.e(0);
        V0 = fj2Var3;
        W0 = lr2Var;
        X0 = w07.d(44.0d);
        Y0 = w07.e(36);
        Z0 = w07.e(0);
        a1 = fj2Var3;
        b1 = lr2Var;
        c1 = w07.d(40.0d);
        d1 = w07.e(32);
        e1 = w07.e(0);
        f1 = fj2Var3;
        g1 = lr2Var;
        h1 = w07.d(36.0d);
        i1 = w07.e(28);
        j1 = w07.e(0);
        k1 = fj2Var3;
        l1 = lr2Var;
        m1 = w07.d(32.0d);
        n1 = w07.e(24);
        o1 = w07.e(0);
        p1 = fj2Var3;
        q1 = lr2Var;
        r1 = w07.d(20.0d);
        s1 = w07.e(14);
        t1 = w07.d(0.1d);
        fj2 fj2Var4 = sv8.a;
        u1 = fj2Var4;
        v1 = lr2Var;
        w1 = w07.d(16.0d);
        x1 = w07.e(12);
        y1 = w07.d(0.5d);
        z1 = fj2Var4;
        A1 = lr2Var;
        B1 = w07.d(16.0d);
        C1 = w07.e(11);
        D1 = w07.d(0.5d);
        E1 = fj2Var4;
        F1 = lr2Var;
        G1 = w07.d(28.0d);
        H1 = w07.e(22);
        I1 = w07.e(0);
        J1 = fj2Var3;
        K1 = lr2Var;
        L1 = w07.d(24.0d);
        M1 = w07.e(16);
        N1 = w07.d(0.15d);
        O1 = fj2Var4;
        P1 = lr2Var;
        Q1 = w07.d(20.0d);
        R1 = w07.e(14);
        S1 = w07.d(0.1d);
        T1 = fj2Var4;
    }
}
