package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class fv0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = j16.o;
        a = j2;
        b = j16.c;
        c = j16.d;
        d = j16.m;
        long j3 = j16.x;
        e = j3;
        f = j16.h;
        long j4 = j16.f;
        g = j4;
        h = j16.b;
        i = j16.a;
        j = j16.u;
        long j5 = j16.t;
        k = j5;
        l = j5;
        m = j16.v;
        n = j16.A;
        long j6 = j16.z;
        o = j6;
        p = j6;
        q = j16.B;
        r = j4;
        s = j16.p;
        t = j16.G;
        long j7 = j16.F;
        u = j7;
        v = j7;
        w = j16.H;
        x = j16.q;
        y = j16.r;
        z = j16.w;
        long j8 = j16.y;
        A = j8;
        B = j8;
        C = j3;
        D = j16.e;
        E = j16.C;
        long j9 = j16.E;
        F = j9;
        G = j9;
        H = j16.D;
        I = j2;
        J = j2;
        K = j16.l;
        L = j16.k;
        M = j16.j;
        N = j16.n;
        O = j16.g;
        P = j16.i;
        Q = j16.s;
        R = j16.I;
        long j10 = j16.K;
        S = j10;
        T = j10;
        U = j16.J;
    }
}
