package defpackage;

import java.util.LinkedHashMap;

/* JADX INFO: loaded from: classes3.dex */
public final class gr0 {
    public static final fv b;
    public static final yg2 c;
    public static final LinkedHashMap d;
    public static final gr0 e;
    public static final gr0 f;
    public static final gr0 g;
    public static final gr0 h;
    public static final gr0 i;
    public static final gr0 j;
    public static final gr0 k;
    public static final gr0 l;
    public static final gr0 m;
    public static final gr0 n;
    public static final gr0 o;
    public static final gr0 p;
    public static final gr0 q;
    public static final gr0 r;
    public static final gr0 s;
    public static final gr0 t;
    public final String a;

    static {
        fv fvVar = new fv(7);
        b = fvVar;
        c = new yg2(12);
        d = new LinkedHashMap();
        fv.j(fvVar, "SSL_RSA_WITH_NULL_MD5");
        fv.j(fvVar, "SSL_RSA_WITH_NULL_SHA");
        fv.j(fvVar, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        fv.j(fvVar, "SSL_RSA_WITH_RC4_128_MD5");
        fv.j(fvVar, "SSL_RSA_WITH_RC4_128_SHA");
        fv.j(fvVar, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        fv.j(fvVar, "SSL_RSA_WITH_DES_CBC_SHA");
        e = fv.j(fvVar, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        fv.j(fvVar, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        fv.j(fvVar, "SSL_DH_anon_WITH_RC4_128_MD5");
        fv.j(fvVar, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        fv.j(fvVar, "SSL_DH_anon_WITH_DES_CBC_SHA");
        fv.j(fvVar, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_KRB5_WITH_DES_CBC_SHA");
        fv.j(fvVar, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_KRB5_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_KRB5_WITH_DES_CBC_MD5");
        fv.j(fvVar, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        fv.j(fvVar, "TLS_KRB5_WITH_RC4_128_MD5");
        fv.j(fvVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        fv.j(fvVar, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        fv.j(fvVar, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        fv.j(fvVar, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        f = fv.j(fvVar, "TLS_RSA_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        g = fv.j(fvVar, "TLS_RSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_RSA_WITH_NULL_SHA256");
        fv.j(fvVar, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        fv.j(fvVar, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        fv.j(fvVar, "TLS_PSK_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_PSK_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_PSK_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_RSA_WITH_SEED_CBC_SHA");
        h = fv.j(fvVar, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        i = fv.j(fvVar, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        fv.j(fvVar, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        fv.j(fvVar, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        fv.j(fvVar, "TLS_FALLBACK_SCSV");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_NULL_SHA");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        fv.j(fvVar, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        j = fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        k = fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_anon_WITH_NULL_SHA");
        fv.j(fvVar, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        fv.j(fvVar, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        l = fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        m = fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        fv.j(fvVar, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        n = fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        o = fv.j(fvVar, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        fv.j(fvVar, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        fv.j(fvVar, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        fv.j(fvVar, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        p = fv.j(fvVar, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        q = fv.j(fvVar, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        fv.j(fvVar, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        fv.j(fvVar, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        r = fv.j(fvVar, "TLS_AES_128_GCM_SHA256");
        s = fv.j(fvVar, "TLS_AES_256_GCM_SHA384");
        t = fv.j(fvVar, "TLS_CHACHA20_POLY1305_SHA256");
        fv.j(fvVar, "TLS_AES_128_CCM_SHA256");
        fv.j(fvVar, "TLS_AES_128_CCM_8_SHA256");
    }

    public gr0(String str) {
        this.a = str;
    }

    public final String toString() {
        return this.a;
    }
}
