package defpackage;

import org.slf4j.Marker;

/* JADX INFO: loaded from: classes.dex */
public final class ju9 implements iu9 {
    public static final or9 A;
    public static final or9 B;
    public static final or9 C;
    public static final or9 D;
    public static final or9 E;
    public static final or9 F;
    public static final or9 G;
    public static final or9 H;
    public static final or9 I;
    public static final or9 J;
    public static final or9 K;
    public static final or9 L;
    public static final or9 M;
    public static final or9 N;
    public static final or9 O;
    public static final or9 P;
    public static final or9 Q;
    public static final or9 R;
    public static final or9 S;
    public static final or9 T;
    public static final or9 U;
    public static final or9 V;
    public static final or9 W;
    public static final or9 X;
    public static final or9 Y;
    public static final or9 Z;
    public static final or9 a;
    public static final or9 a0;
    public static final or9 b;
    public static final or9 b0;
    public static final or9 c;
    public static final or9 c0;
    public static final or9 d;
    public static final or9 d0;
    public static final or9 e;
    public static final or9 e0;
    public static final or9 f;
    public static final or9 f0;
    public static final or9 g;
    public static final or9 g0;
    public static final or9 h;
    public static final or9 h0;
    public static final or9 i;
    public static final or9 i0;
    public static final or9 j;
    public static final or9 j0;
    public static final or9 k;
    public static final or9 k0;
    public static final or9 l;
    public static final or9 l0;
    public static final or9 m;
    public static final or9 m0;
    public static final or9 n;
    public static final or9 n0;
    public static final or9 o;
    public static final or9 o0;
    public static final or9 p;
    public static final or9 p0;
    public static final or9 q;
    public static final or9 q0;
    public static final or9 r;
    public static final or9 r0;
    public static final or9 s;
    public static final or9 s0;
    public static final or9 t;
    public static final or9 t0;
    public static final or9 u;
    public static final or9 u0;
    public static final or9 v;
    public static final or9 v0;
    public static final or9 w;
    public static final or9 w0;
    public static final or9 x;
    public static final or9 y;
    public static final or9 z;

    static {
        xe1 xe1Var = new xe1(nr9.a(), true, true);
        a = xe1Var.A(10000L, "measurement.ad_id_cache_time");
        b = xe1Var.A(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        c = xe1Var.C("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = xe1Var.A(100L, "measurement.max_bundles_per_iteration");
        e = xe1Var.D("measurement.gbraid_campaign.campaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid");
        f = xe1Var.A(86400000L, "measurement.config.cache_time");
        xe1Var.D("measurement.log_tag", "FA");
        g = xe1Var.D("measurement.config.url_authority", "app-measurement.com");
        h = xe1Var.D("measurement.config.url_scheme", "https");
        i = xe1Var.A(1000L, "measurement.upload.debug_upload_interval");
        xe1Var.C("measurement.config.default_flag_values", true);
        j = xe1Var.A(3600000L, "measurement.session.engagement_interval");
        k = xe1Var.D("measurement.rb.attribution.event_params", "value|currency");
        l = xe1Var.D("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp");
        m = xe1Var.A(605000L, "measurement.upload.google_signal_max_queue_time");
        n = xe1Var.D("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        xe1Var.A(0L, "measurement.id.upload.max_conversions_per_day");
        o = xe1Var.A(4L, "measurement.lifetimevalue.max_currency_tracked");
        p = xe1Var.A(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        q = xe1Var.A(500L, "measurement.upload.max_event_parameter_value_length");
        r = xe1Var.A(100000L, "measurement.store.max_stored_events_per_app");
        s = xe1Var.A(50L, "measurement.experiment.max_ids");
        t = xe1Var.A(200L, "measurement.audience.filter_result_max_count");
        u = xe1Var.A(27L, "measurement.upload.max_item_scoped_custom_parameters");
        v = xe1Var.A(1000L, "measurement.rb.max_trigger_registrations_per_day");
        w = xe1Var.A(0L, "measurement.rb.attribution.max_trigger_uris_queried_at_once");
        x = xe1Var.A(7L, "measurement.rb.attribution.client.min_ad_services_version");
        y = xe1Var.A(60000L, "measurement.alarm_manager.minimum_interval");
        z = xe1Var.A(500L, "measurement.upload.minimum_delay");
        A = xe1Var.A(86400000L, "measurement.monitoring.sample_period_millis");
        B = xe1Var.A(3000L, "measurement.rb.attribution.notify_app_delay_millis");
        C = xe1Var.C("measurement.config.notify_trigger_uris_on_backgrounded", true);
        D = xe1Var.D("measurement.rb.attribution.app_allowlist", "");
        E = xe1Var.A(10000L, "measurement.upload.realtime_upload_interval");
        F = xe1Var.A(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        xe1Var.A(3600000L, "measurement.config.cache_time.service");
        G = xe1Var.A(5000L, "measurement.service_client.idle_disconnect_millis");
        xe1Var.D("measurement.log_tag.service", "FA-SVC");
        H = xe1Var.A(1000L, "measurement.service_client.reconnect_millis");
        xe1Var.D("measurement.sgtm.app_allowlist", Marker.ANY_MARKER);
        I = xe1Var.A(240000L, "measurement.sgtm.batch.long_queuing_threshold");
        J = xe1Var.A(1800000L, "measurement.sgtm.batch.retry_interval");
        K = xe1Var.A(10L, "measurement.sgtm.batch.retry_max_count");
        L = xe1Var.A(21600000L, "measurement.sgtm.batch.retry_max_wait");
        M = xe1Var.D("measurement.sgtm.service_upload_apps_list", "");
        N = xe1Var.D("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        O = xe1Var.A(5L, "measurement.sgtm.upload.batches_retrieval_limit");
        P = xe1Var.A(5000L, "measurement.sgtm.upload.max_queued_batches");
        Q = xe1Var.A(600000L, "measurement.sgtm.upload.min_delay_after_background");
        R = xe1Var.A(1000L, "measurement.sgtm.upload.min_delay_after_broadcast");
        S = xe1Var.A(5000L, "measurement.sgtm.upload.min_delay_after_startup");
        T = xe1Var.A(600000L, "measurement.sgtm.upload.retry_interval");
        U = xe1Var.A(21600000L, "measurement.sgtm.upload.retry_max_wait");
        V = xe1Var.A(86400000L, "measurement.upload.stale_data_deletion_interval");
        W = xe1Var.A(16L, "measurement.rb.attribution.max_retry_delay_seconds");
        X = xe1Var.A(90L, "measurement.rb.attribution.client.min_time_after_boot_seconds");
        Y = xe1Var.D("measurement.rb.attribution.uri_authority", "google-analytics.com");
        Z = xe1Var.A(864000000L, "measurement.rb.attribution.max_queue_time");
        a0 = xe1Var.D("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        b0 = xe1Var.D("measurement.rb.attribution.query_parameters_to_remove", "");
        c0 = xe1Var.D("measurement.rb.attribution.uri_scheme", "https");
        d0 = xe1Var.A(604800000L, "measurement.sdk.attribution.cache.ttl");
        e0 = xe1Var.A(7200000L, "measurement.redaction.app_instance_id.ttl");
        f0 = xe1Var.A(43200000L, "measurement.upload.backoff_period");
        g0 = xe1Var.A(15000L, "measurement.upload.initial_upload_delay_time");
        h0 = xe1Var.A(3600000L, "measurement.upload.interval");
        i0 = xe1Var.A(65536L, "measurement.upload.max_bundle_size");
        j0 = xe1Var.A(100L, "measurement.upload.max_bundles");
        k0 = xe1Var.A(500L, "measurement.upload.max_conversions_per_day");
        l0 = xe1Var.A(1000L, "measurement.upload.max_error_events_per_day");
        m0 = xe1Var.A(1000L, "measurement.upload.max_events_per_bundle");
        n0 = xe1Var.A(100000L, "measurement.upload.max_events_per_day");
        o0 = xe1Var.A(50000L, "measurement.upload.max_public_events_per_day");
        p0 = xe1Var.A(518400000L, "measurement.upload.max_queue_time");
        q0 = xe1Var.A(10L, "measurement.upload.max_realtime_events_per_day");
        r0 = xe1Var.A(65536L, "measurement.upload.max_batch_size");
        s0 = xe1Var.A(6L, "measurement.upload.retry_count");
        t0 = xe1Var.A(1800000L, "measurement.upload.retry_time");
        u0 = xe1Var.D("measurement.upload.url", "https://app-measurement.com/a");
        v0 = xe1Var.A(3600000L, "measurement.upload.window_interval");
        w0 = xe1Var.D("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
