package defpackage;

import com.google.common.collect.j0;

/* JADX INFO: loaded from: classes3.dex */
public final class q91 implements ji1, cl2, s69, ar2, s50, j60, x60, g80, kj2, p04, a56, lt7, xk3, ew0, q60, sk3, td4, hq5, iq5, nu, uk3, xc9 {
    public final w91 a;
    public final s91 b;
    public final q91 c = this;

    public q91(w91 w91Var, s91 s91Var) {
        this.a = w91Var;
        this.b = s91Var;
    }

    public final do3 a() {
        vy2.m(107, "expectedSize");
        j0 j0Var = new j0(107);
        int i = wn5.h;
        Boolean bool = Boolean.TRUE;
        j0Var.c("ir.mservices.market.social.users.followers.AccountFollowersViewModel", bool);
        qm5 qm5Var = y97.j;
        j0Var.c("ir.mservices.market.social.users.following.AccountFollowingViewModel", bool);
        int i2 = gu9.i;
        j0Var.c("ir.mservices.market.vpnService.adGuard.ui.AdGuardViewModel", bool);
        int i3 = gu9.i;
        j0Var.c("ir.mservices.market.app.bookmark.ui.AppBookmarkViewModel", bool);
        int i4 = ub1.e;
        j0Var.c("ir.mservices.market.app.detail.ui.recommendation.AppDetailRecommendationViewModel", bool);
        int i5 = xq2.p;
        j0Var.c("ir.mservices.market.app.detail.ui.AppDetailViewModel", bool);
        int i6 = at2.z;
        j0Var.c("ir.mservices.market.app.appList.AppListViewModel", bool);
        int i7 = dt2.p;
        j0Var.c("ir.mservices.market.app.detail.reivews.AppReviewsViewModel", bool);
        int i8 = tt3.k;
        j0Var.c("ir.mservices.market.app.detail.subReviews.AppSubReviewsViewModel", bool);
        int i9 = wn5.h;
        j0Var.c("ir.mservices.market.appUsage.AppsUsageViewModel", bool);
        int i10 = dt2.p;
        j0Var.c("ir.mservices.market.movie.ui.player.BaseMovieViewModel", bool);
        int i11 = js3.h;
        j0Var.c("ir.mservices.market.myAccount.BaseMyAccountViewModel", bool);
        int i12 = dy3.l;
        j0Var.c("ir.mservices.market.activity.BaseNavigationContentViewModel", bool);
        int i13 = wn5.h;
        j0Var.c("ir.mservices.market.common.search.BaseSearchViewModel", bool);
        int i14 = ml9.h;
        j0Var.c("ir.mservices.market.myAccount.dialog.bio.BioDialogViewModel", bool);
        int i15 = hs9.j;
        j0Var.c("ir.mservices.market.myAccount.dialog.birthday.BirthdayDialogViewModel", bool);
        int i16 = yh0.r;
        j0Var.c("ir.mservices.market.app.bookmark.BookmarkViewModel", bool);
        int i17 = rq4.o;
        j0Var.c("ir.mservices.market.vpnService.cheetah.ui.CheetahViewModel", bool);
        int i18 = ja1.y;
        j0Var.c("ir.mservices.market.common.comment.CommentFlowViewModel", bool);
        int i19 = wq2.p;
        j0Var.c("ir.mservices.market.common.comment.CommentViewModel", bool);
        int i20 = is3.s;
        j0Var.c("ir.mservices.market.myReview.complete.CompleteReviewViewModel", bool);
        int i21 = ja1.y;
        j0Var.c("ir.mservices.market.app.detail.developer.ui.DeveloperViewModel", bool);
        int i22 = c26.q;
        j0Var.c("ir.mservices.market.download.DownloadContentViewModel", bool);
        int i23 = tv8.j;
        j0Var.c("ir.mservices.market.movie.download.quality.DownloadQualityViewModel", bool);
        int i24 = ml9.h;
        j0Var.c("ir.mservices.market.download.app.DownloadViewModel", bool);
        int i25 = m91.k;
        j0Var.c("ir.mservices.market.feedback.FeedbackTransactionViewModel", bool);
        int i26 = ub1.e;
        j0Var.c("ir.mservices.market.feedback.FeedbackViewModel", bool);
        int i27 = ml9.h;
        j0Var.c("ir.mservices.market.setting.fontStyle.ui.FontStyleViewModel", bool);
        int i28 = xq2.p;
        j0Var.c("ir.mservices.market.gateway.ui.GatewayListViewModel", bool);
        int i29 = gu9.i;
        j0Var.c("ir.mservices.market.app.home.HomeViewModel", bool);
        int i30 = bt2.l;
        j0Var.c("ir.mservices.market.movie.ui.ibex.IbexViewModel", bool);
        int i31 = s7.k;
        j0Var.c("ir.mservices.market.app.detail.update.InAppUpdateActivityViewModel", bool);
        int i32 = ml9.h;
        j0Var.c("ir.mservices.market.app.detail.update.InAppUpdateViewModel", bool);
        int i33 = hs9.j;
        j0Var.c("ir.mservices.market.myReview.incomplete.InCompleteReviewViewModel", bool);
        int i34 = y40.o;
        j0Var.c("ir.mservices.market.myAccount.inbox.InboxViewModel", bool);
        int i35 = bt2.l;
        j0Var.c("ir.mservices.market.pika.send.InstalledAppsViewModel", bool);
        int i36 = wn5.h;
        j0Var.c("ir.mservices.market.intro.IntroViewModel", bool);
        int i37 = wq2.p;
        j0Var.c("ir.mservices.market.social.level.LevelViewModel", bool);
        qm5 qm5Var2 = y97.j;
        j0Var.c("ir.mservices.market.login.ui.LoginViewModel", bool);
        int i38 = hs9.j;
        j0Var.c("ir.mservices.market.app.detail.more.ui.MoreDescriptionViewModel", bool);
        int i39 = yh0.r;
        j0Var.c("ir.mservices.market.movie.streamers.moreStreamers.MoreStreamersViewModel", bool);
        int i40 = xq2.p;
        j0Var.c("ir.mservices.market.movie.ui.list.MovieBannerListViewModel", bool);
        int i41 = at2.z;
        j0Var.c("ir.mservices.market.movie.ui.bookmark.MovieBookmarkViewModel", bool);
        int i42 = dt2.p;
        j0Var.c("ir.mservices.market.movie.ui.detail.review.MovieCommentFlowViewModel", bool);
        int i43 = tt3.k;
        j0Var.c("ir.mservices.market.movie.ui.detail.list.MovieDetailMoreListViewModel", bool);
        int i44 = rq4.o;
        j0Var.c("ir.mservices.market.movie.ui.detail.MovieDetailViewModel", bool);
        qm5 qm5Var3 = y97.j;
        j0Var.c("ir.mservices.market.movie.download.core.MovieDownloadViewModel", bool);
        int i45 = wu8.r;
        j0Var.c("ir.mservices.market.movie.ui.home.MovieHomeViewModel", bool);
        int i46 = vy2.n;
        j0Var.c("ir.mservices.market.movie.ui.list.MovieMoreViewModel", bool);
        int i47 = hs9.j;
        j0Var.c("ir.mservices.market.download.movie.MovieRecentDownloadViewModel", bool);
        int i48 = y40.o;
        j0Var.c("ir.mservices.market.movie.ui.detail.review.all.MovieReviewsViewModel", bool);
        int i49 = yh0.r;
        j0Var.c("ir.mservices.market.movie.ui.search.result.MovieSearchResultViewModel", bool);
        int i50 = ja1.y;
        j0Var.c("ir.mservices.market.movie.ui.detail.seasons.MovieSeasonsViewModel", bool);
        int i51 = xq2.p;
        j0Var.c("ir.mservices.market.movie.uri.MovieUriViewModel", bool);
        int i52 = ok4.h;
        j0Var.c("ir.mservices.market.myMarket.MyMarketViewModel", bool);
        int i53 = wn5.h;
        j0Var.c("ir.mservices.market.myReview.MyReviewsContentViewModel", bool);
        int i54 = hs9.j;
        j0Var.c("ir.mservices.market.social.search.MynetSearchViewModel", bool);
        int i55 = y40.o;
        j0Var.c("ir.mservices.market.social.mynet.MynetViewModel", bool);
        int i56 = wn5.h;
        j0Var.c("ir.mservices.market.myAccount.dialog.nickname.NicknameDialogViewModel", bool);
        int i57 = js3.h;
        j0Var.c("ir.mservices.market.social.users.followers.OtherAccountFollowersViewModel", bool);
        int i58 = dy3.l;
        j0Var.c("ir.mservices.market.social.users.following.OtherAccountFollowingViewModel", bool);
        int i59 = zk8.p;
        j0Var.c("ir.mservices.market.social.profile.own.OwnProfileHeaderViewModel", bool);
        int i60 = tv8.j;
        j0Var.c("ir.mservices.market.social.profile.own.OwnProfileViewModel", bool);
        int i61 = vy2.n;
        j0Var.c("ir.mservices.market.app.packages.ui.PackageViewModel", bool);
        int i62 = dt2.p;
        j0Var.c("ir.mservices.market.pika.connect.PikaConnectViewModel", bool);
        int i63 = js3.h;
        j0Var.c("ir.mservices.market.pika.connect.PikaSelectDeviceViewModel", bool);
        int i64 = dy3.l;
        j0Var.c("ir.mservices.market.login.ui.PinViewModel", bool);
        qm5 qm5Var4 = y97.j;
        j0Var.c("ir.mservices.market.app.suggest.detail.ui.PlayDetailViewModel", bool);
        int i65 = rf0.j;
        j0Var.c("ir.mservices.market.social.profile.listMore.app.list.ProfileAppListMoreViewModel", bool);
        int i66 = m91.k;
        j0Var.c("ir.mservices.market.social.profile.list.ProfileListViewModel", bool);
        int i67 = ub1.e;
        j0Var.c("ir.mservices.market.social.profile.listMore.movie.list.ProfileMovieListMoreViewModel", bool);
        int i68 = dt2.p;
        j0Var.c("ir.mservices.market.purchaseTransaction.PurchaseTransactionViewModel", bool);
        int i69 = wn5.h;
        j0Var.c("ir.mservices.market.pika.receive.ReceiveViewModel", bool);
        int i70 = zk8.p;
        j0Var.c("ir.mservices.market.download.recentDownload.RecentDownloadViewModel", bool);
        int i71 = ml9.h;
        j0Var.c("ir.mservices.market.app.recommended.ui.RecommendedViewModel", bool);
        j0Var.c("ir.mservices.market.reels.home.ui.ReelsHomeViewModel", bool);
        j0Var.c("ir.mservices.market.reels.ui.ReelsViewModel", bool);
        j0Var.c("ir.mservices.market.social.requests.RequestViewModel", bool);
        j0Var.c("ir.mservices.market.app.schedule.ui.ScheduleUpdateViewModel", bool);
        j0Var.c("ir.mservices.market.movie.ui.search.SearchIntentViewModel", bool);
        j0Var.c("ir.mservices.market.social.list.search.SearchProfileListViewModel", bool);
        j0Var.c("ir.mservices.market.app.search.result.ui.SearchResultViewModel", bool);
        j0Var.c("ir.mservices.market.search.history.ui.SearchViewModel", bool);
        j0Var.c("ir.mservices.market.securityShield.SecurityShieldViewModel", bool);
        j0Var.c("ir.mservices.market.myAccount.city.SelectCityViewModel", bool);
        j0Var.c("ir.mservices.market.social.list.items.SelectedItemsViewModel", bool);
        j0Var.c("ir.mservices.market.pika.send.SendAppViewModel", bool);
        j0Var.c("ir.mservices.market.setting.SettingViewModel", bool);
        j0Var.c("ir.mservices.market.movie.streamers.movies.StreamerMoviesViewModel", bool);
        j0Var.c("ir.mservices.market.movie.streamers.StreamerProfileViewModel", bool);
        j0Var.c("ir.mservices.market.common.comment.SubmitCommentViewModel", bool);
        j0Var.c("ir.mservices.market.app.suggest.search.ui.SuggestListViewModel", bool);
        j0Var.c("ir.mservices.market.app.survey.SurveyViewModel", bool);
        j0Var.c("ir.mservices.market.setting.themeStyle.ThemeStyleViewModel", bool);
        j0Var.c("ir.mservices.market.togo.TogoViewModel", bool);
        j0Var.c("ir.mservices.market.app.update.common.UpdateLaunchViewModel", bool);
        j0Var.c("ir.mservices.market.app.update.UpdateViewModel", bool);
        j0Var.c("ir.mservices.market.common.uploadImage.UploadImageViewModel", bool);
        j0Var.c("ir.mservices.market.app.url.UrlViewModel", bool);
        j0Var.c("ir.mservices.market.social.profile.user.UserProfileHeaderViewModel", bool);
        j0Var.c("ir.mservices.market.social.profile.user.UserProfileViewModel", bool);
        j0Var.c("ir.mservices.market.social.search.UserSearchResultViewModel", bool);
        j0Var.c("ir.mservices.market.myAccount.dialog.username.UsernameDialogViewModel", bool);
        j0Var.c("ir.mservices.market.social.users.list.UsersListViewModel", bool);
        j0Var.c("ir.mservices.market.versionNote.ui.VersionNoteViewModel", bool);
        j0Var.c("ir.mservices.market.webview.WebViewViewModel", bool);
        j0Var.c("ir.mservices.market.social.welcome.WelcomeViewModel", bool);
        return new do3(new f24(j0Var.a(true)), new qq4(this.a, this.b), false);
    }
}
