package androidx.constraintlayout.widget;

import android.view.ViewGroup;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Constraints;
import defpackage.a31;
import defpackage.b31;
import defpackage.c31;
import defpackage.d31;
import defpackage.e31;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class c {
    public int a;
    public String b;
    public final d31 c;
    public final c31 d;
    public final b31 e;
    public final e31 f;
    public HashMap g;
    public a31 h;

    public c() {
        d31 d31Var = new d31();
        d31Var.a = false;
        d31Var.b = 0;
        d31Var.c = 0;
        d31Var.d = 1.0f;
        d31Var.e = Float.NaN;
        this.c = d31Var;
        c31 c31Var = new c31();
        c31Var.a = false;
        c31Var.b = -1;
        c31Var.c = 0;
        c31Var.d = null;
        c31Var.e = -1;
        c31Var.f = 0;
        c31Var.g = Float.NaN;
        c31Var.h = Float.NaN;
        c31Var.i = Float.NaN;
        c31Var.j = -1;
        c31Var.k = null;
        c31Var.l = -3;
        c31Var.m = -1;
        this.d = c31Var;
        b31 b31Var = new b31();
        b31Var.a = false;
        b31Var.b = false;
        b31Var.e = -1;
        b31Var.f = -1;
        b31Var.g = -1.0f;
        b31Var.h = true;
        b31Var.i = -1;
        b31Var.j = -1;
        b31Var.k = -1;
        b31Var.l = -1;
        b31Var.m = -1;
        b31Var.n = -1;
        b31Var.o = -1;
        b31Var.p = -1;
        b31Var.q = -1;
        b31Var.r = -1;
        b31Var.s = -1;
        b31Var.t = -1;
        b31Var.u = -1;
        b31Var.v = -1;
        b31Var.w = -1;
        b31Var.x = 0.5f;
        b31Var.y = 0.5f;
        b31Var.z = null;
        b31Var.A = -1;
        b31Var.B = 0;
        b31Var.C = 0.0f;
        b31Var.D = -1;
        b31Var.E = -1;
        b31Var.F = -1;
        b31Var.G = 0;
        b31Var.H = 0;
        b31Var.I = 0;
        b31Var.J = 0;
        b31Var.K = 0;
        b31Var.L = 0;
        b31Var.M = 0;
        b31Var.N = Integer.MIN_VALUE;
        b31Var.O = Integer.MIN_VALUE;
        b31Var.P = Integer.MIN_VALUE;
        b31Var.Q = Integer.MIN_VALUE;
        b31Var.R = Integer.MIN_VALUE;
        b31Var.S = Integer.MIN_VALUE;
        b31Var.T = Integer.MIN_VALUE;
        b31Var.U = -1.0f;
        b31Var.V = -1.0f;
        b31Var.W = 0;
        b31Var.X = 0;
        b31Var.Y = 0;
        b31Var.Z = 0;
        b31Var.a0 = 0;
        b31Var.b0 = 0;
        b31Var.c0 = 0;
        b31Var.d0 = 0;
        b31Var.e0 = 1.0f;
        b31Var.f0 = 1.0f;
        b31Var.g0 = -1;
        b31Var.h0 = 0;
        b31Var.i0 = -1;
        b31Var.m0 = false;
        b31Var.n0 = false;
        b31Var.o0 = true;
        b31Var.p0 = 0;
        this.e = b31Var;
        e31 e31Var = new e31();
        e31Var.a = false;
        e31Var.b = 0.0f;
        e31Var.c = 0.0f;
        e31Var.d = 0.0f;
        e31Var.e = 1.0f;
        e31Var.f = 1.0f;
        e31Var.g = Float.NaN;
        e31Var.h = Float.NaN;
        e31Var.i = -1;
        e31Var.j = 0.0f;
        e31Var.k = 0.0f;
        e31Var.l = 0.0f;
        e31Var.m = false;
        e31Var.n = 0.0f;
        this.f = e31Var;
        this.g = new HashMap();
    }

    public final void a(ConstraintLayout.LayoutParams layoutParams) {
        b31 b31Var = this.e;
        layoutParams.e = b31Var.i;
        layoutParams.f = b31Var.j;
        layoutParams.g = b31Var.k;
        layoutParams.h = b31Var.l;
        layoutParams.i = b31Var.m;
        layoutParams.j = b31Var.n;
        layoutParams.k = b31Var.o;
        layoutParams.l = b31Var.p;
        layoutParams.m = b31Var.q;
        layoutParams.n = b31Var.r;
        layoutParams.o = b31Var.s;
        layoutParams.s = b31Var.t;
        layoutParams.t = b31Var.u;
        layoutParams.u = b31Var.v;
        layoutParams.v = b31Var.w;
        ((ViewGroup.MarginLayoutParams) layoutParams).leftMargin = b31Var.G;
        ((ViewGroup.MarginLayoutParams) layoutParams).rightMargin = b31Var.H;
        ((ViewGroup.MarginLayoutParams) layoutParams).topMargin = b31Var.I;
        ((ViewGroup.MarginLayoutParams) layoutParams).bottomMargin = b31Var.J;
        layoutParams.A = b31Var.S;
        layoutParams.B = b31Var.R;
        layoutParams.x = b31Var.O;
        layoutParams.z = b31Var.Q;
        layoutParams.E = b31Var.x;
        layoutParams.F = b31Var.y;
        layoutParams.p = b31Var.A;
        layoutParams.q = b31Var.B;
        layoutParams.r = b31Var.C;
        layoutParams.G = b31Var.z;
        layoutParams.T = b31Var.D;
        layoutParams.U = b31Var.E;
        layoutParams.I = b31Var.U;
        layoutParams.H = b31Var.V;
        layoutParams.K = b31Var.X;
        layoutParams.J = b31Var.W;
        layoutParams.W = b31Var.m0;
        layoutParams.X = b31Var.n0;
        layoutParams.L = b31Var.Y;
        layoutParams.M = b31Var.Z;
        layoutParams.P = b31Var.a0;
        layoutParams.Q = b31Var.b0;
        layoutParams.N = b31Var.c0;
        layoutParams.O = b31Var.d0;
        layoutParams.R = b31Var.e0;
        layoutParams.S = b31Var.f0;
        layoutParams.V = b31Var.F;
        layoutParams.c = b31Var.g;
        layoutParams.a = b31Var.e;
        layoutParams.b = b31Var.f;
        ((ViewGroup.MarginLayoutParams) layoutParams).width = b31Var.c;
        ((ViewGroup.MarginLayoutParams) layoutParams).height = b31Var.d;
        String str = b31Var.l0;
        if (str != null) {
            layoutParams.Y = str;
        }
        layoutParams.Z = b31Var.p0;
        layoutParams.setMarginStart(b31Var.L);
        layoutParams.setMarginEnd(b31Var.K);
        layoutParams.a();
    }

    /* JADX INFO: renamed from: b, reason: merged with bridge method [inline-methods] */
    public final c clone() {
        c cVar = new c();
        cVar.e.a(this.e);
        cVar.d.a(this.d);
        d31 d31Var = this.c;
        boolean z = d31Var.a;
        d31 d31Var2 = cVar.c;
        d31Var2.a = z;
        d31Var2.b = d31Var.b;
        d31Var2.d = d31Var.d;
        d31Var2.e = d31Var.e;
        d31Var2.c = d31Var.c;
        cVar.f.a(this.f);
        cVar.a = this.a;
        cVar.h = this.h;
        return cVar;
    }

    public final void c(int i, ConstraintLayout.LayoutParams layoutParams) {
        this.a = i;
        int i2 = layoutParams.e;
        b31 b31Var = this.e;
        b31Var.i = i2;
        b31Var.j = layoutParams.f;
        b31Var.k = layoutParams.g;
        b31Var.l = layoutParams.h;
        b31Var.m = layoutParams.i;
        b31Var.n = layoutParams.j;
        b31Var.o = layoutParams.k;
        b31Var.p = layoutParams.l;
        b31Var.q = layoutParams.m;
        b31Var.r = layoutParams.n;
        b31Var.s = layoutParams.o;
        b31Var.t = layoutParams.s;
        b31Var.u = layoutParams.t;
        b31Var.v = layoutParams.u;
        b31Var.w = layoutParams.v;
        b31Var.x = layoutParams.E;
        b31Var.y = layoutParams.F;
        b31Var.z = layoutParams.G;
        b31Var.A = layoutParams.p;
        b31Var.B = layoutParams.q;
        b31Var.C = layoutParams.r;
        b31Var.D = layoutParams.T;
        b31Var.E = layoutParams.U;
        b31Var.F = layoutParams.V;
        b31Var.g = layoutParams.c;
        b31Var.e = layoutParams.a;
        b31Var.f = layoutParams.b;
        b31Var.c = ((ViewGroup.MarginLayoutParams) layoutParams).width;
        b31Var.d = ((ViewGroup.MarginLayoutParams) layoutParams).height;
        b31Var.G = ((ViewGroup.MarginLayoutParams) layoutParams).leftMargin;
        b31Var.H = ((ViewGroup.MarginLayoutParams) layoutParams).rightMargin;
        b31Var.I = ((ViewGroup.MarginLayoutParams) layoutParams).topMargin;
        b31Var.J = ((ViewGroup.MarginLayoutParams) layoutParams).bottomMargin;
        b31Var.M = layoutParams.D;
        b31Var.U = layoutParams.I;
        b31Var.V = layoutParams.H;
        b31Var.X = layoutParams.K;
        b31Var.W = layoutParams.J;
        b31Var.m0 = layoutParams.W;
        b31Var.n0 = layoutParams.X;
        b31Var.Y = layoutParams.L;
        b31Var.Z = layoutParams.M;
        b31Var.a0 = layoutParams.P;
        b31Var.b0 = layoutParams.Q;
        b31Var.c0 = layoutParams.N;
        b31Var.d0 = layoutParams.O;
        b31Var.e0 = layoutParams.R;
        b31Var.f0 = layoutParams.S;
        b31Var.l0 = layoutParams.Y;
        b31Var.O = layoutParams.x;
        b31Var.Q = layoutParams.z;
        b31Var.N = layoutParams.w;
        b31Var.P = layoutParams.y;
        b31Var.S = layoutParams.A;
        b31Var.R = layoutParams.B;
        b31Var.T = layoutParams.C;
        b31Var.p0 = layoutParams.Z;
        b31Var.K = layoutParams.getMarginEnd();
        b31Var.L = layoutParams.getMarginStart();
    }

    public final void d(int i, Constraints.LayoutParams layoutParams) {
        c(i, layoutParams);
        this.c.d = layoutParams.r0;
        float f = layoutParams.u0;
        e31 e31Var = this.f;
        e31Var.b = f;
        e31Var.c = layoutParams.v0;
        e31Var.d = layoutParams.w0;
        e31Var.e = layoutParams.x0;
        e31Var.f = layoutParams.y0;
        e31Var.g = layoutParams.z0;
        e31Var.h = layoutParams.A0;
        e31Var.j = layoutParams.B0;
        e31Var.k = layoutParams.C0;
        e31Var.l = layoutParams.D0;
        e31Var.n = layoutParams.t0;
        e31Var.m = layoutParams.s0;
    }
}
