package com.google.android.gms.measurement.internal;

import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import defpackage.rq4;
import defpackage.uy6;
import java.util.List;

/* JADX INFO: loaded from: classes.dex */
public final class zzr extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzr> CREATOR = new zzs();
    public final long zzA;
    public final String zzB;
    public final String zzC;
    public final long zzD;
    public final int zzE;
    public final String zza;
    public final String zzb;
    public final String zzc;
    public final String zzd;
    public final long zze;
    public final long zzf;
    public final String zzg;
    public final boolean zzh;
    public final boolean zzi;
    public final long zzj;
    public final String zzk;
    public final long zzl;
    public final int zzm;
    public final boolean zzn;
    public final boolean zzo;
    public final Boolean zzp;
    public final long zzq;
    public final List zzr;
    public final String zzs;
    public final String zzt;
    public final String zzu;
    public final boolean zzv;
    public final long zzw;
    public final int zzx;
    public final String zzy;
    public final int zzz;

    public zzr(String str, String str2, String str3, long j, String str4, long j2, long j3, String str5, boolean z, boolean z2, String str6, long j4, int i, boolean z3, boolean z4, Boolean bool, long j5, List list, String str7, String str8, String str9, boolean z5, long j6, int i2, String str10, int i3, long j7, String str11, String str12, long j8, int i4) {
        rq4.k(str);
        this.zza = str;
        this.zzb = true == TextUtils.isEmpty(str2) ? null : str2;
        this.zzc = str3;
        this.zzj = j;
        this.zzd = str4;
        this.zze = j2;
        this.zzf = j3;
        this.zzg = str5;
        this.zzh = z;
        this.zzi = z2;
        this.zzk = str6;
        this.zzl = j4;
        this.zzm = i;
        this.zzn = z3;
        this.zzo = z4;
        this.zzp = bool;
        this.zzq = j5;
        this.zzr = list;
        this.zzs = str7;
        this.zzt = str8;
        this.zzu = str9;
        this.zzv = z5;
        this.zzw = j6;
        this.zzx = i2;
        this.zzy = str10;
        this.zzz = i3;
        this.zzA = j7;
        this.zzB = str11;
        this.zzC = str12;
        this.zzD = j8;
        this.zzE = i4;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        String str = this.zza;
        int iJ = uy6.J(20293, parcel);
        uy6.D(parcel, 2, str, false);
        uy6.D(parcel, 3, this.zzb, false);
        uy6.D(parcel, 4, this.zzc, false);
        uy6.D(parcel, 5, this.zzd, false);
        long j = this.zze;
        uy6.I(parcel, 6, 8);
        parcel.writeLong(j);
        long j2 = this.zzf;
        uy6.I(parcel, 7, 8);
        parcel.writeLong(j2);
        uy6.D(parcel, 8, this.zzg, false);
        boolean z = this.zzh;
        uy6.I(parcel, 9, 4);
        parcel.writeInt(z ? 1 : 0);
        boolean z2 = this.zzi;
        uy6.I(parcel, 10, 4);
        parcel.writeInt(z2 ? 1 : 0);
        long j3 = this.zzj;
        uy6.I(parcel, 11, 8);
        parcel.writeLong(j3);
        uy6.D(parcel, 12, this.zzk, false);
        long j4 = this.zzl;
        uy6.I(parcel, 14, 8);
        parcel.writeLong(j4);
        int i2 = this.zzm;
        uy6.I(parcel, 15, 4);
        parcel.writeInt(i2);
        boolean z3 = this.zzn;
        uy6.I(parcel, 16, 4);
        parcel.writeInt(z3 ? 1 : 0);
        boolean z4 = this.zzo;
        uy6.I(parcel, 18, 4);
        parcel.writeInt(z4 ? 1 : 0);
        Boolean bool = this.zzp;
        if (bool != null) {
            uy6.I(parcel, 21, 4);
            parcel.writeInt(bool.booleanValue() ? 1 : 0);
        }
        long j5 = this.zzq;
        uy6.I(parcel, 22, 8);
        parcel.writeLong(j5);
        uy6.F(parcel, 23, this.zzr);
        uy6.D(parcel, 25, this.zzs, false);
        uy6.D(parcel, 26, this.zzt, false);
        uy6.D(parcel, 27, this.zzu, false);
        boolean z5 = this.zzv;
        uy6.I(parcel, 28, 4);
        parcel.writeInt(z5 ? 1 : 0);
        long j6 = this.zzw;
        uy6.I(parcel, 29, 8);
        parcel.writeLong(j6);
        int i3 = this.zzx;
        uy6.I(parcel, 30, 4);
        parcel.writeInt(i3);
        uy6.D(parcel, 31, this.zzy, false);
        int i4 = this.zzz;
        uy6.I(parcel, 32, 4);
        parcel.writeInt(i4);
        long j7 = this.zzA;
        uy6.I(parcel, 34, 8);
        parcel.writeLong(j7);
        uy6.D(parcel, 35, this.zzB, false);
        uy6.D(parcel, 36, this.zzC, false);
        long j8 = this.zzD;
        uy6.I(parcel, 37, 8);
        parcel.writeLong(j8);
        int i5 = this.zzE;
        uy6.I(parcel, 38, 4);
        parcel.writeInt(i5);
        uy6.K(iJ, parcel);
    }

    public zzr(String str, String str2, String str3, String str4, long j, long j2, String str5, boolean z, boolean z2, long j3, String str6, long j4, int i, boolean z3, boolean z4, Boolean bool, long j5, List list, String str7, String str8, String str9, boolean z5, long j6, int i2, String str10, int i3, long j7, String str11, String str12, long j8, int i4) {
        this.zza = str;
        this.zzb = str2;
        this.zzc = str3;
        this.zzj = j3;
        this.zzd = str4;
        this.zze = j;
        this.zzf = j2;
        this.zzg = str5;
        this.zzh = z;
        this.zzi = z2;
        this.zzk = str6;
        this.zzl = j4;
        this.zzm = i;
        this.zzn = z3;
        this.zzo = z4;
        this.zzp = bool;
        this.zzq = j5;
        this.zzr = list;
        this.zzs = str7;
        this.zzt = str8;
        this.zzu = str9;
        this.zzv = z5;
        this.zzw = j6;
        this.zzx = i2;
        this.zzy = str10;
        this.zzz = i3;
        this.zzA = j7;
        this.zzB = str11;
        this.zzC = str12;
        this.zzD = j8;
        this.zzE = i4;
    }
}
